# Scene: picture_medium_03
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3225 -58 0 3241 -58 18 minecraft:white_concrete
fill 3225 -57 0 3241 -49 18 minecraft:white_concrete
fill 3224 -57 0 3224 -49 18 minecraft:white_concrete
fill 3242 -57 0 3242 -49 18 minecraft:white_concrete
fill 3224 -57 -1 3242 -49 -1 minecraft:white_concrete
fill 3224 -57 19 3242 -49 19 minecraft:white_concrete
fill 3226 -57 1 3240 -49 17 minecraft:air
fill 3225 -48 0 3241 -48 18 minecraft:white_concrete
fill 3226 -48 1 3240 -48 1 minecraft:glowstone
fill 3226 -48 17 3240 -48 17 minecraft:glowstone
fill 3226 -48 2 3226 -48 16 minecraft:glowstone
fill 3240 -48 2 3240 -48 16 minecraft:glowstone
fill 3227 -48 2 3239 -48 2 minecraft:glowstone
fill 3227 -48 16 3239 -48 16 minecraft:glowstone
fill 3227 -48 3 3227 -48 15 minecraft:glowstone
fill 3239 -48 3 3239 -48 15 minecraft:glowstone
fill 3228 -48 3 3238 -48 3 minecraft:glowstone
fill 3228 -48 15 3238 -48 15 minecraft:glowstone
fill 3228 -48 4 3228 -48 14 minecraft:glowstone
fill 3238 -48 4 3238 -48 14 minecraft:glowstone
fill 3231 -48 7 3235 -48 11 minecraft:glowstone
fill 3226 -53 1 3240 -53 5 minecraft:glowstone
fill 3226 -52 1 3240 -52 5 minecraft:smooth_stone
fill 3226 -51 6 3240 -51 6 minecraft:oak_fence
fill 3228 -57 2 3231 -57 5 minecraft:yellow_concrete
fill 3233 -52 10 3233 -52 10 minecraft:smooth_stone
setblock 3232 -51 2 minecraft:chest
setblock 3233 -51 5 minecraft:stone_slab[type=bottom]
setblock 3238 -51 4 minecraft:chest
setblock 3234 -51 3 minecraft:bookshelf
setblock 3235 -51 3 minecraft:bookshelf
setblock 3234 -51 4 minecraft:bookshelf
