# Scene: tier_path_hard_02
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 2 of 15 with 3-5 decorations.
fill 1830 -58 0 1852 -58 30 minecraft:white_concrete
fill 1830 -57 0 1852 -52 30 minecraft:white_concrete
fill 1829 -57 0 1829 -52 30 minecraft:white_concrete
fill 1853 -57 0 1853 -52 30 minecraft:white_concrete
fill 1829 -57 -1 1853 -52 -1 minecraft:white_concrete
fill 1829 -57 31 1853 -52 31 minecraft:white_concrete
fill 1831 -57 1 1851 -52 29 minecraft:air
fill 1830 -51 0 1852 -51 30 minecraft:white_concrete
fill 1831 -51 1 1851 -51 1 minecraft:glowstone
fill 1831 -51 29 1851 -51 29 minecraft:glowstone
fill 1831 -51 2 1831 -51 28 minecraft:glowstone
fill 1851 -51 2 1851 -51 28 minecraft:glowstone
fill 1832 -51 2 1850 -51 2 minecraft:glowstone
fill 1832 -51 28 1850 -51 28 minecraft:glowstone
fill 1832 -51 3 1832 -51 27 minecraft:glowstone
fill 1850 -51 3 1850 -51 27 minecraft:glowstone
fill 1833 -51 3 1849 -51 3 minecraft:glowstone
fill 1833 -51 27 1849 -51 27 minecraft:glowstone
fill 1833 -51 4 1833 -51 26 minecraft:glowstone
fill 1849 -51 4 1849 -51 26 minecraft:glowstone
fill 1839 -51 13 1843 -51 17 minecraft:glowstone
fill 1830 -61 0 1852 -58 30 minecraft:white_concrete
fill 1830 -61 0 1852 -58 11 minecraft:white_concrete
fill 1830 -61 18 1852 -58 30 minecraft:white_concrete
fill 1831 -61 12 1851 -58 17 minecraft:air
fill 1830 -61 0 1852 -61 30 minecraft:black_concrete
fill 1840 -58 12 1842 -58 17 minecraft:air
fill 1840 -57 19 1842 -57 19 minecraft:gold_block
setblock 1840 -57 7 minecraft:polished_blackstone_pressure_plate
setblock 1840 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1840 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1841 -57 7 minecraft:polished_blackstone_pressure_plate
setblock 1841 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1841 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1842 -57 7 minecraft:polished_blackstone_pressure_plate
setblock 1842 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1842 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1845 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1850 -57 3 minecraft:chest
setblock 1836 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1841 -57 2 minecraft:bookshelf
setblock 1832 -57 3 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_02/place_command_blocks
