# Scene: picture_easy_02
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2825 -58 0 2841 -58 18 minecraft:white_concrete
fill 2825 -57 0 2841 -49 18 minecraft:white_concrete
fill 2824 -57 0 2824 -49 18 minecraft:white_concrete
fill 2842 -57 0 2842 -49 18 minecraft:white_concrete
fill 2824 -57 -1 2842 -49 -1 minecraft:white_concrete
fill 2824 -57 19 2842 -49 19 minecraft:white_concrete
fill 2826 -57 1 2840 -49 17 minecraft:air
fill 2825 -48 0 2841 -48 18 minecraft:white_concrete
fill 2826 -48 1 2840 -48 1 minecraft:glowstone
fill 2826 -48 17 2840 -48 17 minecraft:glowstone
fill 2826 -48 2 2826 -48 16 minecraft:glowstone
fill 2840 -48 2 2840 -48 16 minecraft:glowstone
fill 2827 -48 2 2839 -48 2 minecraft:glowstone
fill 2827 -48 16 2839 -48 16 minecraft:glowstone
fill 2827 -48 3 2827 -48 15 minecraft:glowstone
fill 2839 -48 3 2839 -48 15 minecraft:glowstone
fill 2828 -48 3 2838 -48 3 minecraft:glowstone
fill 2828 -48 15 2838 -48 15 minecraft:glowstone
fill 2828 -48 4 2828 -48 14 minecraft:glowstone
fill 2838 -48 4 2838 -48 14 minecraft:glowstone
fill 2831 -48 7 2835 -48 11 minecraft:glowstone
fill 2826 -53 1 2840 -53 5 minecraft:glowstone
fill 2826 -52 1 2840 -52 5 minecraft:smooth_stone
fill 2826 -51 6 2840 -51 6 minecraft:oak_fence
fill 2832 -57 1 2836 -57 5 minecraft:orange_concrete
fill 2833 -52 10 2833 -52 10 minecraft:smooth_stone
setblock 2826 -51 2 minecraft:bookshelf
setblock 2828 -51 1 minecraft:crafting_table
setblock 2830 -51 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2838 -51 5 minecraft:furnace
setblock 2828 -51 3 minecraft:crafting_table
