# Scene: tier_path_hard_06
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 6 of 15 with 3-5 decorations.
fill 1951 -58 0 1971 -58 30 minecraft:white_concrete
fill 1951 -57 0 1971 -52 30 minecraft:white_concrete
fill 1950 -57 0 1950 -52 30 minecraft:white_concrete
fill 1972 -57 0 1972 -52 30 minecraft:white_concrete
fill 1950 -57 -1 1972 -52 -1 minecraft:white_concrete
fill 1950 -57 31 1972 -52 31 minecraft:white_concrete
fill 1952 -57 1 1970 -52 29 minecraft:air
fill 1951 -51 0 1971 -51 30 minecraft:white_concrete
fill 1952 -51 1 1970 -51 1 minecraft:glowstone
fill 1952 -51 29 1970 -51 29 minecraft:glowstone
fill 1952 -51 2 1952 -51 28 minecraft:glowstone
fill 1970 -51 2 1970 -51 28 minecraft:glowstone
fill 1953 -51 2 1969 -51 2 minecraft:glowstone
fill 1953 -51 28 1969 -51 28 minecraft:glowstone
fill 1953 -51 3 1953 -51 27 minecraft:glowstone
fill 1969 -51 3 1969 -51 27 minecraft:glowstone
fill 1954 -51 3 1968 -51 3 minecraft:glowstone
fill 1954 -51 27 1968 -51 27 minecraft:glowstone
fill 1954 -51 4 1954 -51 26 minecraft:glowstone
fill 1968 -51 4 1968 -51 26 minecraft:glowstone
fill 1959 -51 13 1963 -51 17 minecraft:glowstone
fill 1951 -61 0 1971 -58 30 minecraft:white_concrete
fill 1951 -61 0 1971 -58 11 minecraft:white_concrete
fill 1951 -61 18 1971 -58 30 minecraft:white_concrete
fill 1952 -61 12 1970 -58 17 minecraft:air
fill 1951 -61 0 1971 -61 30 minecraft:black_concrete
fill 1960 -58 12 1962 -58 17 minecraft:air
fill 1960 -57 19 1962 -57 19 minecraft:gold_block
setblock 1960 -57 7 minecraft:jungle_pressure_plate
setblock 1960 -57 8 minecraft:jungle_pressure_plate
setblock 1960 -57 9 minecraft:jungle_pressure_plate
setblock 1961 -57 7 minecraft:jungle_pressure_plate
setblock 1961 -57 8 minecraft:jungle_pressure_plate
setblock 1961 -57 9 minecraft:jungle_pressure_plate
setblock 1962 -57 7 minecraft:jungle_pressure_plate
setblock 1962 -57 8 minecraft:jungle_pressure_plate
setblock 1962 -57 9 minecraft:jungle_pressure_plate
setblock 1969 -57 5 minecraft:crafting_table
setblock 1953 -57 4 minecraft:furnace
setblock 1953 -57 5 minecraft:chest
setblock 1966 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1954 -57 2 minecraft:bookshelf

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_06/place_command_blocks
