# Scene: tier_elevator_medium_08
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 8 of 15 with 3-5 decorations.
fill 660 -59 0 682 -59 22 minecraft:white_concrete
fill 660 -58 0 682 -53 22 minecraft:white_concrete
fill 659 -58 0 659 -53 22 minecraft:white_concrete
fill 683 -58 0 683 -53 22 minecraft:white_concrete
fill 659 -58 -1 683 -53 -1 minecraft:white_concrete
fill 659 -58 23 683 -53 23 minecraft:white_concrete
fill 661 -58 1 681 -53 21 minecraft:air
fill 660 -52 0 682 -52 22 minecraft:white_concrete
fill 661 -52 1 681 -52 1 minecraft:glowstone
fill 661 -52 21 681 -52 21 minecraft:glowstone
fill 661 -52 2 661 -52 20 minecraft:glowstone
fill 681 -52 2 681 -52 20 minecraft:glowstone
fill 662 -52 2 680 -52 2 minecraft:glowstone
fill 662 -52 20 680 -52 20 minecraft:glowstone
fill 662 -52 3 662 -52 19 minecraft:glowstone
fill 680 -52 3 680 -52 19 minecraft:glowstone
fill 663 -52 3 679 -52 3 minecraft:glowstone
fill 663 -52 19 679 -52 19 minecraft:glowstone
fill 663 -52 4 663 -52 18 minecraft:glowstone
fill 679 -52 4 679 -52 18 minecraft:glowstone
fill 669 -52 9 673 -52 13 minecraft:glowstone
fill 661 -58 11 681 -53 11 minecraft:white_concrete
fill 671 -58 11 672 -56 11 minecraft:black_concrete
setblock 669 -58 5 minecraft:jungle_pressure_plate
setblock 669 -58 6 minecraft:jungle_pressure_plate
setblock 669 -58 7 minecraft:jungle_pressure_plate
setblock 670 -58 5 minecraft:jungle_pressure_plate
setblock 670 -58 6 minecraft:jungle_pressure_plate
setblock 670 -58 7 minecraft:jungle_pressure_plate
setblock 671 -58 5 minecraft:jungle_pressure_plate
setblock 671 -58 6 minecraft:jungle_pressure_plate
setblock 671 -58 7 minecraft:jungle_pressure_plate
setblock 680 -58 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 669 -58 2 minecraft:furnace
setblock 680 -58 6 minecraft:furnace
setblock 662 -58 7 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_08/place_command_blocks
