# Scene: tier_path_hard_13
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 13 of 15 with 3-5 decorations.
fill 2160 -58 0 2181 -58 31 minecraft:white_concrete
fill 2160 -57 0 2181 -52 31 minecraft:white_concrete
fill 2159 -57 0 2159 -52 31 minecraft:white_concrete
fill 2182 -57 0 2182 -52 31 minecraft:white_concrete
fill 2159 -57 -1 2182 -52 -1 minecraft:white_concrete
fill 2159 -57 32 2182 -52 32 minecraft:white_concrete
fill 2161 -57 1 2180 -52 30 minecraft:air
fill 2160 -51 0 2181 -51 31 minecraft:white_concrete
fill 2161 -51 1 2180 -51 1 minecraft:glowstone
fill 2161 -51 30 2180 -51 30 minecraft:glowstone
fill 2161 -51 2 2161 -51 29 minecraft:glowstone
fill 2180 -51 2 2180 -51 29 minecraft:glowstone
fill 2162 -51 2 2179 -51 2 minecraft:glowstone
fill 2162 -51 29 2179 -51 29 minecraft:glowstone
fill 2162 -51 3 2162 -51 28 minecraft:glowstone
fill 2179 -51 3 2179 -51 28 minecraft:glowstone
fill 2163 -51 3 2178 -51 3 minecraft:glowstone
fill 2163 -51 28 2178 -51 28 minecraft:glowstone
fill 2163 -51 4 2163 -51 27 minecraft:glowstone
fill 2178 -51 4 2178 -51 27 minecraft:glowstone
fill 2168 -51 13 2172 -51 17 minecraft:glowstone
fill 2160 -61 0 2181 -58 31 minecraft:white_concrete
fill 2160 -61 0 2181 -58 12 minecraft:white_concrete
fill 2160 -61 19 2181 -58 31 minecraft:white_concrete
fill 2161 -61 13 2180 -58 18 minecraft:air
fill 2160 -61 0 2181 -61 31 minecraft:black_concrete
fill 2169 -58 13 2171 -58 18 minecraft:air
fill 2169 -57 20 2171 -57 20 minecraft:gold_block
setblock 2170 -57 8 minecraft:oak_pressure_plate
setblock 2170 -57 9 minecraft:oak_pressure_plate
setblock 2170 -57 10 minecraft:oak_pressure_plate
setblock 2171 -57 8 minecraft:oak_pressure_plate
setblock 2171 -57 9 minecraft:oak_pressure_plate
setblock 2171 -57 10 minecraft:oak_pressure_plate
setblock 2172 -57 8 minecraft:oak_pressure_plate
setblock 2172 -57 9 minecraft:oak_pressure_plate
setblock 2172 -57 10 minecraft:oak_pressure_plate
setblock 2162 -57 8 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2174 -57 2 minecraft:stone_slab[type=bottom]
setblock 2179 -57 10 minecraft:chest
setblock 2179 -57 4 minecraft:furnace

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_13/place_command_blocks
