# Scene: truck_medium_13
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2651 -58 0 2674 -58 22 minecraft:white_concrete
fill 2651 -57 0 2674 -52 22 minecraft:white_concrete
fill 2650 -57 0 2650 -52 22 minecraft:white_concrete
fill 2675 -57 0 2675 -52 22 minecraft:white_concrete
fill 2650 -57 -1 2675 -52 -1 minecraft:white_concrete
fill 2650 -57 23 2675 -52 23 minecraft:white_concrete
fill 2652 -57 1 2673 -52 21 minecraft:air
fill 2651 -51 0 2674 -51 22 minecraft:white_concrete
fill 2652 -51 1 2673 -51 1 minecraft:glowstone
fill 2652 -51 21 2673 -51 21 minecraft:glowstone
fill 2652 -51 2 2652 -51 20 minecraft:glowstone
fill 2673 -51 2 2673 -51 20 minecraft:glowstone
fill 2653 -51 2 2672 -51 2 minecraft:glowstone
fill 2653 -51 20 2672 -51 20 minecraft:glowstone
fill 2653 -51 3 2653 -51 19 minecraft:glowstone
fill 2672 -51 3 2672 -51 19 minecraft:glowstone
fill 2654 -51 3 2671 -51 3 minecraft:glowstone
fill 2654 -51 19 2671 -51 19 minecraft:glowstone
fill 2654 -51 4 2654 -51 18 minecraft:glowstone
fill 2671 -51 4 2671 -51 18 minecraft:glowstone
fill 2660 -51 9 2664 -51 13 minecraft:glowstone
fill 2662 -58 10 2664 -58 12 minecraft:yellow_concrete
setblock 2672 -57 12 minecraft:chest
setblock 2672 -57 8 minecraft:bookshelf
setblock 2653 -57 20 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2672 -57 5 minecraft:bookshelf
setblock 2672 -57 20 minecraft:bookshelf
setblock 2653 -57 3 minecraft:stone_slab[type=bottom]
setblock 2653 -57 16 minecraft:stone_slab[type=bottom]
setblock 2672 -57 10 minecraft:furnace
setblock 2653 -57 13 minecraft:chest
setblock 2672 -57 14 minecraft:chest
setblock 2672 -57 9 minecraft:furnace
setblock 2672 -57 3 minecraft:chest
setblock 2653 -57 12 minecraft:furnace
setblock 2653 -57 10 minecraft:crafting_table
setblock 2653 -57 14 minecraft:crafting_table
