# Scene: truck_medium_15
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2714 -58 0 2737 -58 22 minecraft:white_concrete
fill 2714 -57 0 2737 -52 22 minecraft:white_concrete
fill 2713 -57 0 2713 -52 22 minecraft:white_concrete
fill 2738 -57 0 2738 -52 22 minecraft:white_concrete
fill 2713 -57 -1 2738 -52 -1 minecraft:white_concrete
fill 2713 -57 23 2738 -52 23 minecraft:white_concrete
fill 2715 -57 1 2736 -52 21 minecraft:air
fill 2714 -51 0 2737 -51 22 minecraft:white_concrete
fill 2715 -51 1 2736 -51 1 minecraft:glowstone
fill 2715 -51 21 2736 -51 21 minecraft:glowstone
fill 2715 -51 2 2715 -51 20 minecraft:glowstone
fill 2736 -51 2 2736 -51 20 minecraft:glowstone
fill 2716 -51 2 2735 -51 2 minecraft:glowstone
fill 2716 -51 20 2735 -51 20 minecraft:glowstone
fill 2716 -51 3 2716 -51 19 minecraft:glowstone
fill 2735 -51 3 2735 -51 19 minecraft:glowstone
fill 2717 -51 3 2734 -51 3 minecraft:glowstone
fill 2717 -51 19 2734 -51 19 minecraft:glowstone
fill 2717 -51 4 2717 -51 18 minecraft:glowstone
fill 2734 -51 4 2734 -51 18 minecraft:glowstone
fill 2723 -51 9 2727 -51 13 minecraft:glowstone
fill 2725 -58 10 2727 -58 12 minecraft:green_concrete
setblock 2716 -57 19 minecraft:furnace
setblock 2735 -57 19 minecraft:crafting_table
setblock 2735 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2716 -57 16 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2716 -57 17 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2735 -57 6 minecraft:stone_slab[type=bottom]
setblock 2716 -57 14 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2716 -57 12 minecraft:bookshelf
setblock 2716 -57 6 minecraft:chest
setblock 2735 -57 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2716 -57 20 minecraft:chest
setblock 2716 -57 11 minecraft:bookshelf
setblock 2716 -57 8 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2735 -57 13 minecraft:crafting_table
setblock 2735 -57 9 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
