# Scene: tier_elevator_medium_12
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 12 of 15 with 3-5 decorations.
fill 781 -59 0 801 -59 22 minecraft:white_concrete
fill 781 -58 0 801 -53 22 minecraft:white_concrete
fill 780 -58 0 780 -53 22 minecraft:white_concrete
fill 802 -58 0 802 -53 22 minecraft:white_concrete
fill 780 -58 -1 802 -53 -1 minecraft:white_concrete
fill 780 -58 23 802 -53 23 minecraft:white_concrete
fill 782 -58 1 800 -53 21 minecraft:air
fill 781 -52 0 801 -52 22 minecraft:white_concrete
fill 782 -52 1 800 -52 1 minecraft:glowstone
fill 782 -52 21 800 -52 21 minecraft:glowstone
fill 782 -52 2 782 -52 20 minecraft:glowstone
fill 800 -52 2 800 -52 20 minecraft:glowstone
fill 783 -52 2 799 -52 2 minecraft:glowstone
fill 783 -52 20 799 -52 20 minecraft:glowstone
fill 783 -52 3 783 -52 19 minecraft:glowstone
fill 799 -52 3 799 -52 19 minecraft:glowstone
fill 784 -52 3 798 -52 3 minecraft:glowstone
fill 784 -52 19 798 -52 19 minecraft:glowstone
fill 784 -52 4 784 -52 18 minecraft:glowstone
fill 798 -52 4 798 -52 18 minecraft:glowstone
fill 789 -52 9 793 -52 13 minecraft:glowstone
fill 782 -58 11 800 -53 11 minecraft:white_concrete
fill 789 -58 11 790 -56 11 minecraft:gray_concrete
setblock 792 -58 5 minecraft:birch_pressure_plate
setblock 792 -58 6 minecraft:birch_pressure_plate
setblock 792 -58 7 minecraft:birch_pressure_plate
setblock 793 -58 5 minecraft:birch_pressure_plate
setblock 793 -58 6 minecraft:birch_pressure_plate
setblock 793 -58 7 minecraft:birch_pressure_plate
setblock 794 -58 5 minecraft:birch_pressure_plate
setblock 794 -58 6 minecraft:birch_pressure_plate
setblock 794 -58 7 minecraft:birch_pressure_plate
setblock 793 -58 2 minecraft:crafting_table
setblock 794 -58 2 minecraft:stone_slab[type=bottom]
setblock 783 -58 9 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_12/place_command_blocks
