# Scene: maze_medium_10
# Auto-generated by multiagent/scene/generate_scenes.py
fill 4544 -58 0 4566 -58 22 minecraft:white_concrete
fill 4544 -57 0 4566 -40 22 minecraft:white_concrete
fill 4543 -57 0 4543 -40 22 minecraft:white_concrete
fill 4567 -57 0 4567 -40 22 minecraft:white_concrete
fill 4543 -57 -1 4567 -40 -1 minecraft:white_concrete
fill 4543 -57 23 4567 -40 23 minecraft:white_concrete
fill 4545 -57 1 4565 -40 21 minecraft:air
fill 4544 -39 0 4566 -39 22 minecraft:white_concrete
fill 4545 -39 1 4565 -39 1 minecraft:glowstone
fill 4545 -39 21 4565 -39 21 minecraft:glowstone
fill 4545 -39 2 4545 -39 20 minecraft:glowstone
fill 4565 -39 2 4565 -39 20 minecraft:glowstone
fill 4546 -39 2 4564 -39 2 minecraft:glowstone
fill 4546 -39 20 4564 -39 20 minecraft:glowstone
fill 4546 -39 3 4546 -39 19 minecraft:glowstone
fill 4564 -39 3 4564 -39 19 minecraft:glowstone
fill 4547 -39 3 4563 -39 3 minecraft:glowstone
fill 4547 -39 19 4563 -39 19 minecraft:glowstone
fill 4547 -39 4 4547 -39 18 minecraft:glowstone
fill 4563 -39 4 4563 -39 18 minecraft:glowstone
fill 4553 -39 9 4557 -39 13 minecraft:glowstone
fill 4544 -51 0 4566 -51 0 minecraft:glowstone
fill 4544 -51 22 4566 -51 22 minecraft:glowstone
fill 4544 -51 1 4544 -51 21 minecraft:glowstone
fill 4566 -51 1 4566 -51 21 minecraft:glowstone
fill 4548 -57 4 4562 -55 18 minecraft:light_gray_concrete
fill 4548 -57 4 4562 -57 18 minecraft:glowstone
fill 4549 -57 9 4549 -55 9 minecraft:air
fill 4550 -57 9 4550 -55 9 minecraft:air
fill 4551 -57 9 4551 -55 9 minecraft:air
fill 4552 -57 9 4552 -55 9 minecraft:air
fill 4553 -57 9 4553 -55 9 minecraft:air
fill 4554 -57 9 4554 -55 9 minecraft:air
fill 4555 -57 9 4555 -55 9 minecraft:air
fill 4555 -57 10 4555 -55 10 minecraft:air
fill 4555 -57 11 4555 -55 11 minecraft:air
fill 4555 -57 12 4555 -55 12 minecraft:air
fill 4555 -57 13 4555 -55 13 minecraft:air
fill 4555 -57 14 4555 -55 14 minecraft:air
fill 4556 -57 9 4556 -55 9 minecraft:air
fill 4556 -57 10 4556 -55 10 minecraft:air
fill 4556 -57 11 4556 -55 11 minecraft:air
fill 4556 -57 12 4556 -55 12 minecraft:air
fill 4556 -57 13 4556 -55 13 minecraft:air
fill 4556 -57 14 4556 -55 14 minecraft:air
fill 4557 -57 9 4557 -55 9 minecraft:air
fill 4557 -57 10 4557 -55 10 minecraft:air
fill 4558 -57 9 4558 -55 9 minecraft:air
fill 4558 -57 10 4558 -55 10 minecraft:air
fill 4559 -57 9 4559 -55 9 minecraft:air
fill 4559 -57 10 4559 -55 10 minecraft:air
fill 4560 -57 9 4560 -55 9 minecraft:air
fill 4560 -57 10 4560 -55 10 minecraft:air
fill 4559 -58 9 4560 -58 10 minecraft:white_concrete
fill 4555 -58 13 4556 -58 14 minecraft:magenta_concrete
setblock 4551 -57 9 minecraft:bookshelf
setblock 4555 -57 11 minecraft:furnace
setblock 4556 -57 9 minecraft:chest
setblock 4557 -57 9 minecraft:chest
