# Scene: tier_path_hard_01
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 1 of 15 with 3-5 decorations.
fill 1800 -58 0 1821 -58 31 minecraft:white_concrete
fill 1800 -57 0 1821 -52 31 minecraft:white_concrete
fill 1799 -57 0 1799 -52 31 minecraft:white_concrete
fill 1822 -57 0 1822 -52 31 minecraft:white_concrete
fill 1799 -57 -1 1822 -52 -1 minecraft:white_concrete
fill 1799 -57 32 1822 -52 32 minecraft:white_concrete
fill 1801 -57 1 1820 -52 30 minecraft:air
fill 1800 -51 0 1821 -51 31 minecraft:white_concrete
fill 1801 -51 1 1820 -51 1 minecraft:glowstone
fill 1801 -51 30 1820 -51 30 minecraft:glowstone
fill 1801 -51 2 1801 -51 29 minecraft:glowstone
fill 1820 -51 2 1820 -51 29 minecraft:glowstone
fill 1802 -51 2 1819 -51 2 minecraft:glowstone
fill 1802 -51 29 1819 -51 29 minecraft:glowstone
fill 1802 -51 3 1802 -51 28 minecraft:glowstone
fill 1819 -51 3 1819 -51 28 minecraft:glowstone
fill 1803 -51 3 1818 -51 3 minecraft:glowstone
fill 1803 -51 28 1818 -51 28 minecraft:glowstone
fill 1803 -51 4 1803 -51 27 minecraft:glowstone
fill 1818 -51 4 1818 -51 27 minecraft:glowstone
fill 1808 -51 13 1812 -51 17 minecraft:glowstone
fill 1800 -61 0 1821 -58 31 minecraft:white_concrete
fill 1800 -61 0 1821 -58 12 minecraft:white_concrete
fill 1800 -61 19 1821 -58 31 minecraft:white_concrete
fill 1801 -61 13 1820 -58 18 minecraft:air
fill 1800 -61 0 1821 -61 31 minecraft:black_concrete
fill 1809 -58 13 1811 -58 18 minecraft:air
fill 1809 -57 20 1811 -57 20 minecraft:gold_block
setblock 1810 -57 8 minecraft:stone_pressure_plate
setblock 1810 -57 9 minecraft:stone_pressure_plate
setblock 1810 -57 10 minecraft:stone_pressure_plate
setblock 1811 -57 8 minecraft:stone_pressure_plate
setblock 1811 -57 9 minecraft:stone_pressure_plate
setblock 1811 -57 10 minecraft:stone_pressure_plate
setblock 1812 -57 8 minecraft:stone_pressure_plate
setblock 1812 -57 9 minecraft:stone_pressure_plate
setblock 1812 -57 10 minecraft:stone_pressure_plate
setblock 1810 -57 2 minecraft:bookshelf
setblock 1802 -57 5 minecraft:furnace
setblock 1807 -57 2 minecraft:stone_slab[type=bottom]
setblock 1816 -57 2 minecraft:chest

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_01/place_command_blocks
