# Scene: truck_easy_14
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2210 -58 0 2232 -58 23 minecraft:white_concrete
fill 2210 -57 0 2232 -52 23 minecraft:white_concrete
fill 2209 -57 0 2209 -52 23 minecraft:white_concrete
fill 2233 -57 0 2233 -52 23 minecraft:white_concrete
fill 2209 -57 -1 2233 -52 -1 minecraft:white_concrete
fill 2209 -57 24 2233 -52 24 minecraft:white_concrete
fill 2211 -57 1 2231 -52 22 minecraft:air
fill 2210 -51 0 2232 -51 23 minecraft:white_concrete
fill 2211 -51 1 2231 -51 1 minecraft:glowstone
fill 2211 -51 22 2231 -51 22 minecraft:glowstone
fill 2211 -51 2 2211 -51 21 minecraft:glowstone
fill 2231 -51 2 2231 -51 21 minecraft:glowstone
fill 2212 -51 2 2230 -51 2 minecraft:glowstone
fill 2212 -51 21 2230 -51 21 minecraft:glowstone
fill 2212 -51 3 2212 -51 20 minecraft:glowstone
fill 2230 -51 3 2230 -51 20 minecraft:glowstone
fill 2213 -51 3 2229 -51 3 minecraft:glowstone
fill 2213 -51 20 2229 -51 20 minecraft:glowstone
fill 2213 -51 4 2213 -51 19 minecraft:glowstone
fill 2229 -51 4 2229 -51 19 minecraft:glowstone
fill 2219 -51 9 2223 -51 13 minecraft:glowstone
fill 2220 -58 11 2223 -58 14 minecraft:lime_concrete
setblock 2230 -57 9 minecraft:furnace
setblock 2230 -57 11 minecraft:stone_slab[type=bottom]
setblock 2212 -57 13 minecraft:bookshelf
setblock 2230 -57 15 minecraft:crafting_table
setblock 2212 -57 7 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2230 -57 19 minecraft:crafting_table
setblock 2230 -57 17 minecraft:furnace
setblock 2230 -57 18 minecraft:stone_slab[type=bottom]
setblock 2230 -57 7 minecraft:furnace
setblock 2212 -57 15 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2230 -57 12 minecraft:chest
setblock 2212 -57 17 minecraft:stone_slab[type=bottom]
setblock 2212 -57 20 minecraft:furnace
