# Scene: truck_medium_02
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2305 -58 0 2327 -58 23 minecraft:white_concrete
fill 2305 -57 0 2327 -52 23 minecraft:white_concrete
fill 2304 -57 0 2304 -52 23 minecraft:white_concrete
fill 2328 -57 0 2328 -52 23 minecraft:white_concrete
fill 2304 -57 -1 2328 -52 -1 minecraft:white_concrete
fill 2304 -57 24 2328 -52 24 minecraft:white_concrete
fill 2306 -57 1 2326 -52 22 minecraft:air
fill 2305 -51 0 2327 -51 23 minecraft:white_concrete
fill 2306 -51 1 2326 -51 1 minecraft:glowstone
fill 2306 -51 22 2326 -51 22 minecraft:glowstone
fill 2306 -51 2 2306 -51 21 minecraft:glowstone
fill 2326 -51 2 2326 -51 21 minecraft:glowstone
fill 2307 -51 2 2325 -51 2 minecraft:glowstone
fill 2307 -51 21 2325 -51 21 minecraft:glowstone
fill 2307 -51 3 2307 -51 20 minecraft:glowstone
fill 2325 -51 3 2325 -51 20 minecraft:glowstone
fill 2308 -51 3 2324 -51 3 minecraft:glowstone
fill 2308 -51 20 2324 -51 20 minecraft:glowstone
fill 2308 -51 4 2308 -51 19 minecraft:glowstone
fill 2324 -51 4 2324 -51 19 minecraft:glowstone
fill 2314 -51 9 2318 -51 13 minecraft:glowstone
fill 2315 -58 11 2317 -58 13 minecraft:orange_concrete
setblock 2325 -57 20 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2307 -57 21 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2325 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2325 -57 14 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2307 -57 10 minecraft:bookshelf
setblock 2325 -57 17 minecraft:crafting_table
setblock 2307 -57 18 minecraft:crafting_table
setblock 2325 -57 13 minecraft:crafting_table
setblock 2307 -57 5 minecraft:stone_slab[type=bottom]
setblock 2307 -57 11 minecraft:furnace
setblock 2307 -57 2 minecraft:chest
setblock 2325 -57 16 minecraft:crafting_table
setblock 2307 -57 17 minecraft:bookshelf
