# Scene: maze_easy_15
# Auto-generated by multiagent/scene/generate_scenes.py
fill 4234 -58 0 4256 -58 22 minecraft:white_concrete
fill 4234 -57 0 4256 -40 22 minecraft:white_concrete
fill 4233 -57 0 4233 -40 22 minecraft:white_concrete
fill 4257 -57 0 4257 -40 22 minecraft:white_concrete
fill 4233 -57 -1 4257 -40 -1 minecraft:white_concrete
fill 4233 -57 23 4257 -40 23 minecraft:white_concrete
fill 4235 -57 1 4255 -40 21 minecraft:air
fill 4234 -39 0 4256 -39 22 minecraft:white_concrete
fill 4235 -39 1 4255 -39 1 minecraft:glowstone
fill 4235 -39 21 4255 -39 21 minecraft:glowstone
fill 4235 -39 2 4235 -39 20 minecraft:glowstone
fill 4255 -39 2 4255 -39 20 minecraft:glowstone
fill 4236 -39 2 4254 -39 2 minecraft:glowstone
fill 4236 -39 20 4254 -39 20 minecraft:glowstone
fill 4236 -39 3 4236 -39 19 minecraft:glowstone
fill 4254 -39 3 4254 -39 19 minecraft:glowstone
fill 4237 -39 3 4253 -39 3 minecraft:glowstone
fill 4237 -39 19 4253 -39 19 minecraft:glowstone
fill 4237 -39 4 4237 -39 18 minecraft:glowstone
fill 4253 -39 4 4253 -39 18 minecraft:glowstone
fill 4243 -39 9 4247 -39 13 minecraft:glowstone
fill 4234 -51 0 4256 -51 0 minecraft:glowstone
fill 4234 -51 22 4256 -51 22 minecraft:glowstone
fill 4234 -51 1 4234 -51 21 minecraft:glowstone
fill 4256 -51 1 4256 -51 21 minecraft:glowstone
fill 4238 -57 4 4252 -55 18 minecraft:light_gray_concrete
fill 4238 -57 4 4252 -57 18 minecraft:glowstone
fill 4247 -57 7 4247 -55 7 minecraft:air
fill 4247 -57 8 4247 -55 8 minecraft:air
fill 4247 -57 9 4247 -55 9 minecraft:air
fill 4247 -57 10 4247 -55 10 minecraft:air
fill 4247 -57 11 4247 -55 11 minecraft:air
fill 4247 -57 12 4247 -55 12 minecraft:air
fill 4247 -57 13 4247 -55 13 minecraft:air
fill 4247 -57 14 4247 -55 14 minecraft:air
fill 4248 -57 7 4248 -55 7 minecraft:air
fill 4248 -57 8 4248 -55 8 minecraft:air
fill 4248 -57 9 4248 -55 9 minecraft:air
fill 4248 -57 10 4248 -55 10 minecraft:air
fill 4248 -57 11 4248 -55 11 minecraft:air
fill 4248 -57 12 4248 -55 12 minecraft:air
fill 4248 -57 13 4248 -55 13 minecraft:air
fill 4248 -57 14 4248 -55 14 minecraft:air
fill 4247 -58 7 4248 -58 8 minecraft:white_concrete
fill 4247 -58 13 4248 -58 14 minecraft:green_concrete
setblock 4248 -57 9 minecraft:furnace
setblock 4248 -57 10 minecraft:stone_slab[type=bottom]
setblock 4248 -57 11 minecraft:crafting_table
