# Scene: truck_hard_02
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2778 -58 0 2800 -58 23 minecraft:white_concrete
fill 2778 -57 0 2800 -52 23 minecraft:white_concrete
fill 2777 -57 0 2777 -52 23 minecraft:white_concrete
fill 2801 -57 0 2801 -52 23 minecraft:white_concrete
fill 2777 -57 -1 2801 -52 -1 minecraft:white_concrete
fill 2777 -57 24 2801 -52 24 minecraft:white_concrete
fill 2779 -57 1 2799 -52 22 minecraft:air
fill 2778 -51 0 2800 -51 23 minecraft:white_concrete
fill 2779 -51 1 2799 -51 1 minecraft:glowstone
fill 2779 -51 22 2799 -51 22 minecraft:glowstone
fill 2779 -51 2 2779 -51 21 minecraft:glowstone
fill 2799 -51 2 2799 -51 21 minecraft:glowstone
fill 2780 -51 2 2798 -51 2 minecraft:glowstone
fill 2780 -51 21 2798 -51 21 minecraft:glowstone
fill 2780 -51 3 2780 -51 20 minecraft:glowstone
fill 2798 -51 3 2798 -51 20 minecraft:glowstone
fill 2781 -51 3 2797 -51 3 minecraft:glowstone
fill 2781 -51 20 2797 -51 20 minecraft:glowstone
fill 2781 -51 4 2781 -51 19 minecraft:glowstone
fill 2797 -51 4 2797 -51 19 minecraft:glowstone
fill 2787 -51 9 2791 -51 13 minecraft:glowstone
fill 2789 -58 12 2790 -58 13 minecraft:orange_concrete
setblock 2780 -57 15 minecraft:crafting_table
setblock 2798 -57 21 minecraft:stone_slab[type=bottom]
setblock 2798 -57 9 minecraft:bookshelf
setblock 2798 -57 11 minecraft:crafting_table
setblock 2780 -57 21 minecraft:crafting_table
setblock 2798 -57 5 minecraft:crafting_table
setblock 2780 -57 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2798 -57 3 minecraft:stone_slab[type=bottom]
setblock 2780 -57 12 minecraft:chest
setblock 2798 -57 12 minecraft:crafting_table
setblock 2798 -57 13 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2780 -57 16 minecraft:furnace
setblock 2780 -57 10 minecraft:chest
