# Scene: truck_medium_11
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2588 -58 0 2611 -58 22 minecraft:white_concrete
fill 2588 -57 0 2611 -52 22 minecraft:white_concrete
fill 2587 -57 0 2587 -52 22 minecraft:white_concrete
fill 2612 -57 0 2612 -52 22 minecraft:white_concrete
fill 2587 -57 -1 2612 -52 -1 minecraft:white_concrete
fill 2587 -57 23 2612 -52 23 minecraft:white_concrete
fill 2589 -57 1 2610 -52 21 minecraft:air
fill 2588 -51 0 2611 -51 22 minecraft:white_concrete
fill 2589 -51 1 2610 -51 1 minecraft:glowstone
fill 2589 -51 21 2610 -51 21 minecraft:glowstone
fill 2589 -51 2 2589 -51 20 minecraft:glowstone
fill 2610 -51 2 2610 -51 20 minecraft:glowstone
fill 2590 -51 2 2609 -51 2 minecraft:glowstone
fill 2590 -51 20 2609 -51 20 minecraft:glowstone
fill 2590 -51 3 2590 -51 19 minecraft:glowstone
fill 2609 -51 3 2609 -51 19 minecraft:glowstone
fill 2591 -51 3 2608 -51 3 minecraft:glowstone
fill 2591 -51 19 2608 -51 19 minecraft:glowstone
fill 2591 -51 4 2591 -51 18 minecraft:glowstone
fill 2608 -51 4 2608 -51 18 minecraft:glowstone
fill 2597 -51 9 2601 -51 13 minecraft:glowstone
fill 2599 -58 10 2601 -58 12 minecraft:red_concrete
setblock 2609 -57 10 minecraft:crafting_table
setblock 2609 -57 2 minecraft:bookshelf
setblock 2609 -57 12 minecraft:furnace
setblock 2609 -57 6 minecraft:bookshelf
setblock 2609 -57 16 minecraft:stone_slab[type=bottom]
setblock 2590 -57 8 minecraft:crafting_table
setblock 2590 -57 2 minecraft:bookshelf
setblock 2609 -57 7 minecraft:chest
setblock 2609 -57 15 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2590 -57 16 minecraft:chest
setblock 2590 -57 13 minecraft:furnace
setblock 2590 -57 14 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2609 -57 3 minecraft:furnace
setblock 2590 -57 12 minecraft:crafting_table
