# Scene: picture_hard_15
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3900 -58 0 3916 -58 18 minecraft:white_concrete
fill 3900 -57 0 3916 -49 18 minecraft:white_concrete
fill 3899 -57 0 3899 -49 18 minecraft:white_concrete
fill 3917 -57 0 3917 -49 18 minecraft:white_concrete
fill 3899 -57 -1 3917 -49 -1 minecraft:white_concrete
fill 3899 -57 19 3917 -49 19 minecraft:white_concrete
fill 3901 -57 1 3915 -49 17 minecraft:air
fill 3900 -48 0 3916 -48 18 minecraft:white_concrete
fill 3901 -48 1 3915 -48 1 minecraft:glowstone
fill 3901 -48 17 3915 -48 17 minecraft:glowstone
fill 3901 -48 2 3901 -48 16 minecraft:glowstone
fill 3915 -48 2 3915 -48 16 minecraft:glowstone
fill 3902 -48 2 3914 -48 2 minecraft:glowstone
fill 3902 -48 16 3914 -48 16 minecraft:glowstone
fill 3902 -48 3 3902 -48 15 minecraft:glowstone
fill 3914 -48 3 3914 -48 15 minecraft:glowstone
fill 3903 -48 3 3913 -48 3 minecraft:glowstone
fill 3903 -48 15 3913 -48 15 minecraft:glowstone
fill 3903 -48 4 3903 -48 14 minecraft:glowstone
fill 3913 -48 4 3913 -48 14 minecraft:glowstone
fill 3906 -48 7 3910 -48 11 minecraft:glowstone
fill 3901 -53 1 3915 -53 5 minecraft:glowstone
fill 3901 -52 1 3915 -52 5 minecraft:smooth_stone
fill 3901 -51 6 3915 -51 6 minecraft:oak_fence
fill 3905 -57 2 3907 -57 4 minecraft:green_concrete
fill 3908 -52 10 3908 -52 10 minecraft:smooth_stone
setblock 3903 -51 2 minecraft:crafting_table
setblock 3913 -51 3 minecraft:chest
setblock 3908 -51 2 minecraft:stone_slab[type=bottom]
setblock 3911 -51 1 minecraft:crafting_table
