# Scene: picture_medium_08
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3350 -58 0 3366 -58 18 minecraft:white_concrete
fill 3350 -57 0 3366 -49 18 minecraft:white_concrete
fill 3349 -57 0 3349 -49 18 minecraft:white_concrete
fill 3367 -57 0 3367 -49 18 minecraft:white_concrete
fill 3349 -57 -1 3367 -49 -1 minecraft:white_concrete
fill 3349 -57 19 3367 -49 19 minecraft:white_concrete
fill 3351 -57 1 3365 -49 17 minecraft:air
fill 3350 -48 0 3366 -48 18 minecraft:white_concrete
fill 3351 -48 1 3365 -48 1 minecraft:glowstone
fill 3351 -48 17 3365 -48 17 minecraft:glowstone
fill 3351 -48 2 3351 -48 16 minecraft:glowstone
fill 3365 -48 2 3365 -48 16 minecraft:glowstone
fill 3352 -48 2 3364 -48 2 minecraft:glowstone
fill 3352 -48 16 3364 -48 16 minecraft:glowstone
fill 3352 -48 3 3352 -48 15 minecraft:glowstone
fill 3364 -48 3 3364 -48 15 minecraft:glowstone
fill 3353 -48 3 3363 -48 3 minecraft:glowstone
fill 3353 -48 15 3363 -48 15 minecraft:glowstone
fill 3353 -48 4 3353 -48 14 minecraft:glowstone
fill 3363 -48 4 3363 -48 14 minecraft:glowstone
fill 3356 -48 7 3360 -48 11 minecraft:glowstone
fill 3351 -53 1 3365 -53 5 minecraft:glowstone
fill 3351 -52 1 3365 -52 5 minecraft:smooth_stone
fill 3351 -51 6 3365 -51 6 minecraft:oak_fence
fill 3357 -57 1 3360 -57 4 minecraft:blue_concrete
fill 3358 -52 10 3358 -52 10 minecraft:smooth_stone
setblock 3354 -51 1 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3356 -51 2 minecraft:chest
setblock 3361 -51 2 minecraft:stone_slab[type=bottom]
setblock 3353 -51 1 minecraft:stone_slab[type=bottom]
