# Scene: tier_elevator_medium_07
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 7 of 15 with 3-5 decorations.
fill 630 -59 0 651 -59 23 minecraft:white_concrete
fill 630 -58 0 651 -53 23 minecraft:white_concrete
fill 629 -58 0 629 -53 23 minecraft:white_concrete
fill 652 -58 0 652 -53 23 minecraft:white_concrete
fill 629 -58 -1 652 -53 -1 minecraft:white_concrete
fill 629 -58 24 652 -53 24 minecraft:white_concrete
fill 631 -58 1 650 -53 22 minecraft:air
fill 630 -52 0 651 -52 23 minecraft:white_concrete
fill 631 -52 1 650 -52 1 minecraft:glowstone
fill 631 -52 22 650 -52 22 minecraft:glowstone
fill 631 -52 2 631 -52 21 minecraft:glowstone
fill 650 -52 2 650 -52 21 minecraft:glowstone
fill 632 -52 2 649 -52 2 minecraft:glowstone
fill 632 -52 21 649 -52 21 minecraft:glowstone
fill 632 -52 3 632 -52 20 minecraft:glowstone
fill 649 -52 3 649 -52 20 minecraft:glowstone
fill 633 -52 3 648 -52 3 minecraft:glowstone
fill 633 -52 20 648 -52 20 minecraft:glowstone
fill 633 -52 4 633 -52 19 minecraft:glowstone
fill 648 -52 4 648 -52 19 minecraft:glowstone
fill 638 -52 9 642 -52 13 minecraft:glowstone
fill 631 -58 12 650 -53 12 minecraft:white_concrete
fill 640 -58 12 641 -56 12 minecraft:gray_concrete
setblock 642 -58 7 minecraft:spruce_pressure_plate
setblock 642 -58 8 minecraft:spruce_pressure_plate
setblock 642 -58 9 minecraft:spruce_pressure_plate
setblock 643 -58 7 minecraft:spruce_pressure_plate
setblock 643 -58 8 minecraft:spruce_pressure_plate
setblock 643 -58 9 minecraft:spruce_pressure_plate
setblock 644 -58 7 minecraft:spruce_pressure_plate
setblock 644 -58 8 minecraft:spruce_pressure_plate
setblock 644 -58 9 minecraft:spruce_pressure_plate
setblock 649 -58 5 minecraft:bookshelf
setblock 648 -58 2 minecraft:crafting_table
setblock 632 -58 7 minecraft:crafting_table

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_07/place_command_blocks
