# Scene: truck_easy_06
# Auto-generated by multiagent/scene/generate_scenes.py
fill 1958 -58 0 1980 -58 23 minecraft:white_concrete
fill 1958 -57 0 1980 -52 23 minecraft:white_concrete
fill 1957 -57 0 1957 -52 23 minecraft:white_concrete
fill 1981 -57 0 1981 -52 23 minecraft:white_concrete
fill 1957 -57 -1 1981 -52 -1 minecraft:white_concrete
fill 1957 -57 24 1981 -52 24 minecraft:white_concrete
fill 1959 -57 1 1979 -52 22 minecraft:air
fill 1958 -51 0 1980 -51 23 minecraft:white_concrete
fill 1959 -51 1 1979 -51 1 minecraft:glowstone
fill 1959 -51 22 1979 -51 22 minecraft:glowstone
fill 1959 -51 2 1959 -51 21 minecraft:glowstone
fill 1979 -51 2 1979 -51 21 minecraft:glowstone
fill 1960 -51 2 1978 -51 2 minecraft:glowstone
fill 1960 -51 21 1978 -51 21 minecraft:glowstone
fill 1960 -51 3 1960 -51 20 minecraft:glowstone
fill 1978 -51 3 1978 -51 20 minecraft:glowstone
fill 1961 -51 3 1977 -51 3 minecraft:glowstone
fill 1961 -51 20 1977 -51 20 minecraft:glowstone
fill 1961 -51 4 1961 -51 19 minecraft:glowstone
fill 1977 -51 4 1977 -51 19 minecraft:glowstone
fill 1967 -51 9 1971 -51 13 minecraft:glowstone
fill 1968 -58 11 1971 -58 14 minecraft:cyan_concrete
setblock 1978 -57 5 minecraft:bookshelf
setblock 1978 -57 10 minecraft:bookshelf
setblock 1978 -57 4 minecraft:stone_slab[type=bottom]
setblock 1978 -57 14 minecraft:bookshelf
setblock 1960 -57 16 minecraft:stone_slab[type=bottom]
setblock 1960 -57 8 minecraft:furnace
setblock 1978 -57 9 minecraft:furnace
setblock 1960 -57 15 minecraft:stone_slab[type=bottom]
setblock 1978 -57 8 minecraft:furnace
setblock 1978 -57 7 minecraft:bookshelf
setblock 1960 -57 18 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1978 -57 20 minecraft:bookshelf
setblock 1978 -57 19 minecraft:chest
setblock 1960 -57 7 minecraft:chest
setblock 1978 -57 15 minecraft:crafting_table
