# Scene: truck_hard_11
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3061 -58 0 3084 -58 22 minecraft:white_concrete
fill 3061 -57 0 3084 -52 22 minecraft:white_concrete
fill 3060 -57 0 3060 -52 22 minecraft:white_concrete
fill 3085 -57 0 3085 -52 22 minecraft:white_concrete
fill 3060 -57 -1 3085 -52 -1 minecraft:white_concrete
fill 3060 -57 23 3085 -52 23 minecraft:white_concrete
fill 3062 -57 1 3083 -52 21 minecraft:air
fill 3061 -51 0 3084 -51 22 minecraft:white_concrete
fill 3062 -51 1 3083 -51 1 minecraft:glowstone
fill 3062 -51 21 3083 -51 21 minecraft:glowstone
fill 3062 -51 2 3062 -51 20 minecraft:glowstone
fill 3083 -51 2 3083 -51 20 minecraft:glowstone
fill 3063 -51 2 3082 -51 2 minecraft:glowstone
fill 3063 -51 20 3082 -51 20 minecraft:glowstone
fill 3063 -51 3 3063 -51 19 minecraft:glowstone
fill 3082 -51 3 3082 -51 19 minecraft:glowstone
fill 3064 -51 3 3081 -51 3 minecraft:glowstone
fill 3064 -51 19 3081 -51 19 minecraft:glowstone
fill 3064 -51 4 3064 -51 18 minecraft:glowstone
fill 3081 -51 4 3081 -51 18 minecraft:glowstone
fill 3070 -51 9 3074 -51 13 minecraft:glowstone
fill 3073 -58 11 3074 -58 12 minecraft:red_concrete
setblock 3082 -57 6 minecraft:furnace
setblock 3063 -57 19 minecraft:crafting_table
setblock 3063 -57 8 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3082 -57 3 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3063 -57 12 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3063 -57 16 minecraft:stone_slab[type=bottom]
setblock 3082 -57 18 minecraft:crafting_table
setblock 3063 -57 14 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3063 -57 13 minecraft:chest
setblock 3082 -57 10 minecraft:stone_slab[type=bottom]
