# Scene: picture_hard_11
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3800 -58 0 3816 -58 18 minecraft:white_concrete
fill 3800 -57 0 3816 -49 18 minecraft:white_concrete
fill 3799 -57 0 3799 -49 18 minecraft:white_concrete
fill 3817 -57 0 3817 -49 18 minecraft:white_concrete
fill 3799 -57 -1 3817 -49 -1 minecraft:white_concrete
fill 3799 -57 19 3817 -49 19 minecraft:white_concrete
fill 3801 -57 1 3815 -49 17 minecraft:air
fill 3800 -48 0 3816 -48 18 minecraft:white_concrete
fill 3801 -48 1 3815 -48 1 minecraft:glowstone
fill 3801 -48 17 3815 -48 17 minecraft:glowstone
fill 3801 -48 2 3801 -48 16 minecraft:glowstone
fill 3815 -48 2 3815 -48 16 minecraft:glowstone
fill 3802 -48 2 3814 -48 2 minecraft:glowstone
fill 3802 -48 16 3814 -48 16 minecraft:glowstone
fill 3802 -48 3 3802 -48 15 minecraft:glowstone
fill 3814 -48 3 3814 -48 15 minecraft:glowstone
fill 3803 -48 3 3813 -48 3 minecraft:glowstone
fill 3803 -48 15 3813 -48 15 minecraft:glowstone
fill 3803 -48 4 3803 -48 14 minecraft:glowstone
fill 3813 -48 4 3813 -48 14 minecraft:glowstone
fill 3806 -48 7 3810 -48 11 minecraft:glowstone
fill 3801 -53 1 3815 -53 5 minecraft:glowstone
fill 3801 -52 1 3815 -52 5 minecraft:smooth_stone
fill 3801 -51 6 3815 -51 6 minecraft:oak_fence
fill 3806 -57 2 3808 -57 4 minecraft:red_concrete
fill 3808 -52 10 3808 -52 10 minecraft:smooth_stone
setblock 3813 -51 4 minecraft:crafting_table
setblock 3812 -51 1 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3804 -51 1 minecraft:chest
setblock 3814 -51 5 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3803 -51 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3804 -51 3 minecraft:crafting_table
