# Scene: truck_medium_09
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2525 -58 0 2548 -58 22 minecraft:white_concrete
fill 2525 -57 0 2548 -52 22 minecraft:white_concrete
fill 2524 -57 0 2524 -52 22 minecraft:white_concrete
fill 2549 -57 0 2549 -52 22 minecraft:white_concrete
fill 2524 -57 -1 2549 -52 -1 minecraft:white_concrete
fill 2524 -57 23 2549 -52 23 minecraft:white_concrete
fill 2526 -57 1 2547 -52 21 minecraft:air
fill 2525 -51 0 2548 -51 22 minecraft:white_concrete
fill 2526 -51 1 2547 -51 1 minecraft:glowstone
fill 2526 -51 21 2547 -51 21 minecraft:glowstone
fill 2526 -51 2 2526 -51 20 minecraft:glowstone
fill 2547 -51 2 2547 -51 20 minecraft:glowstone
fill 2527 -51 2 2546 -51 2 minecraft:glowstone
fill 2527 -51 20 2546 -51 20 minecraft:glowstone
fill 2527 -51 3 2527 -51 19 minecraft:glowstone
fill 2546 -51 3 2546 -51 19 minecraft:glowstone
fill 2528 -51 3 2545 -51 3 minecraft:glowstone
fill 2528 -51 19 2545 -51 19 minecraft:glowstone
fill 2528 -51 4 2528 -51 18 minecraft:glowstone
fill 2545 -51 4 2545 -51 18 minecraft:glowstone
fill 2534 -51 9 2538 -51 13 minecraft:glowstone
fill 2536 -58 10 2538 -58 12 minecraft:purple_concrete
setblock 2546 -57 15 minecraft:furnace
setblock 2546 -57 17 minecraft:chest
setblock 2546 -57 10 minecraft:stone_slab[type=bottom]
setblock 2546 -57 18 minecraft:stone_slab[type=bottom]
setblock 2546 -57 7 minecraft:bookshelf
setblock 2546 -57 8 minecraft:stone_slab[type=bottom]
setblock 2527 -57 5 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2546 -57 12 minecraft:crafting_table
setblock 2546 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2546 -57 5 minecraft:bookshelf
setblock 2546 -57 19 minecraft:bookshelf
