# Scene: tier_path_medium_04
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 4 of 15 with 3-5 decorations.
fill 1440 -58 0 1461 -58 30 minecraft:white_concrete
fill 1440 -57 0 1461 -52 30 minecraft:white_concrete
fill 1439 -57 0 1439 -52 30 minecraft:white_concrete
fill 1462 -57 0 1462 -52 30 minecraft:white_concrete
fill 1439 -57 -1 1462 -52 -1 minecraft:white_concrete
fill 1439 -57 31 1462 -52 31 minecraft:white_concrete
fill 1441 -57 1 1460 -52 29 minecraft:air
fill 1440 -51 0 1461 -51 30 minecraft:white_concrete
fill 1441 -51 1 1460 -51 1 minecraft:glowstone
fill 1441 -51 29 1460 -51 29 minecraft:glowstone
fill 1441 -51 2 1441 -51 28 minecraft:glowstone
fill 1460 -51 2 1460 -51 28 minecraft:glowstone
fill 1442 -51 2 1459 -51 2 minecraft:glowstone
fill 1442 -51 28 1459 -51 28 minecraft:glowstone
fill 1442 -51 3 1442 -51 27 minecraft:glowstone
fill 1459 -51 3 1459 -51 27 minecraft:glowstone
fill 1443 -51 3 1458 -51 3 minecraft:glowstone
fill 1443 -51 27 1458 -51 27 minecraft:glowstone
fill 1443 -51 4 1443 -51 26 minecraft:glowstone
fill 1458 -51 4 1458 -51 26 minecraft:glowstone
fill 1448 -51 13 1452 -51 17 minecraft:glowstone
fill 1440 -61 0 1461 -58 30 minecraft:white_concrete
fill 1440 -61 0 1461 -58 12 minecraft:white_concrete
fill 1440 -61 18 1461 -58 30 minecraft:white_concrete
fill 1441 -61 13 1460 -58 17 minecraft:air
fill 1440 -61 0 1461 -61 30 minecraft:black_concrete
fill 1449 -58 13 1451 -58 17 minecraft:air
fill 1449 -57 19 1451 -57 19 minecraft:gold_block
setblock 1450 -57 8 minecraft:spruce_pressure_plate
setblock 1450 -57 9 minecraft:spruce_pressure_plate
setblock 1450 -57 10 minecraft:spruce_pressure_plate
setblock 1451 -57 8 minecraft:spruce_pressure_plate
setblock 1451 -57 9 minecraft:spruce_pressure_plate
setblock 1451 -57 10 minecraft:spruce_pressure_plate
setblock 1452 -57 8 minecraft:spruce_pressure_plate
setblock 1452 -57 9 minecraft:spruce_pressure_plate
setblock 1452 -57 10 minecraft:spruce_pressure_plate
setblock 1442 -57 9 minecraft:bookshelf
setblock 1457 -57 2 minecraft:furnace
setblock 1454 -57 2 minecraft:bookshelf
setblock 1459 -57 3 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1459 -57 8 minecraft:stone_slab[type=bottom]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_04/place_command_blocks
