# Scene: truck_medium_04
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2368 -58 0 2390 -58 23 minecraft:white_concrete
fill 2368 -57 0 2390 -52 23 minecraft:white_concrete
fill 2367 -57 0 2367 -52 23 minecraft:white_concrete
fill 2391 -57 0 2391 -52 23 minecraft:white_concrete
fill 2367 -57 -1 2391 -52 -1 minecraft:white_concrete
fill 2367 -57 24 2391 -52 24 minecraft:white_concrete
fill 2369 -57 1 2389 -52 22 minecraft:air
fill 2368 -51 0 2390 -51 23 minecraft:white_concrete
fill 2369 -51 1 2389 -51 1 minecraft:glowstone
fill 2369 -51 22 2389 -51 22 minecraft:glowstone
fill 2369 -51 2 2369 -51 21 minecraft:glowstone
fill 2389 -51 2 2389 -51 21 minecraft:glowstone
fill 2370 -51 2 2388 -51 2 minecraft:glowstone
fill 2370 -51 21 2388 -51 21 minecraft:glowstone
fill 2370 -51 3 2370 -51 20 minecraft:glowstone
fill 2388 -51 3 2388 -51 20 minecraft:glowstone
fill 2371 -51 3 2387 -51 3 minecraft:glowstone
fill 2371 -51 20 2387 -51 20 minecraft:glowstone
fill 2371 -51 4 2371 -51 19 minecraft:glowstone
fill 2387 -51 4 2387 -51 19 minecraft:glowstone
fill 2377 -51 9 2381 -51 13 minecraft:glowstone
fill 2378 -58 11 2380 -58 13 minecraft:lime_concrete
setblock 2388 -57 21 minecraft:chest
setblock 2370 -57 21 minecraft:furnace
setblock 2388 -57 12 minecraft:furnace
setblock 2388 -57 11 minecraft:stone_slab[type=bottom]
setblock 2388 -57 7 minecraft:chest
setblock 2370 -57 9 minecraft:bookshelf
setblock 2388 -57 13 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2370 -57 12 minecraft:bookshelf
setblock 2388 -57 9 minecraft:crafting_table
setblock 2370 -57 11 minecraft:furnace
