# Scene: picture_easy_11
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3050 -58 0 3066 -58 18 minecraft:white_concrete
fill 3050 -57 0 3066 -49 18 minecraft:white_concrete
fill 3049 -57 0 3049 -49 18 minecraft:white_concrete
fill 3067 -57 0 3067 -49 18 minecraft:white_concrete
fill 3049 -57 -1 3067 -49 -1 minecraft:white_concrete
fill 3049 -57 19 3067 -49 19 minecraft:white_concrete
fill 3051 -57 1 3065 -49 17 minecraft:air
fill 3050 -48 0 3066 -48 18 minecraft:white_concrete
fill 3051 -48 1 3065 -48 1 minecraft:glowstone
fill 3051 -48 17 3065 -48 17 minecraft:glowstone
fill 3051 -48 2 3051 -48 16 minecraft:glowstone
fill 3065 -48 2 3065 -48 16 minecraft:glowstone
fill 3052 -48 2 3064 -48 2 minecraft:glowstone
fill 3052 -48 16 3064 -48 16 minecraft:glowstone
fill 3052 -48 3 3052 -48 15 minecraft:glowstone
fill 3064 -48 3 3064 -48 15 minecraft:glowstone
fill 3053 -48 3 3063 -48 3 minecraft:glowstone
fill 3053 -48 15 3063 -48 15 minecraft:glowstone
fill 3053 -48 4 3053 -48 14 minecraft:glowstone
fill 3063 -48 4 3063 -48 14 minecraft:glowstone
fill 3056 -48 7 3060 -48 11 minecraft:glowstone
fill 3051 -53 1 3065 -53 5 minecraft:glowstone
fill 3051 -52 1 3065 -52 5 minecraft:smooth_stone
fill 3051 -51 6 3065 -51 6 minecraft:oak_fence
fill 3054 -57 1 3058 -57 5 minecraft:red_concrete
fill 3058 -52 10 3058 -52 10 minecraft:smooth_stone
setblock 3064 -51 3 minecraft:furnace
setblock 3064 -51 4 minecraft:stone_slab[type=bottom]
setblock 3062 -51 1 minecraft:chest
setblock 3062 -51 3 minecraft:chest
setblock 3061 -51 2 minecraft:furnace
setblock 3052 -51 1 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3065 -51 3 minecraft:furnace
