# Scene: truck_medium_08
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2494 -58 0 2516 -58 23 minecraft:white_concrete
fill 2494 -57 0 2516 -52 23 minecraft:white_concrete
fill 2493 -57 0 2493 -52 23 minecraft:white_concrete
fill 2517 -57 0 2517 -52 23 minecraft:white_concrete
fill 2493 -57 -1 2517 -52 -1 minecraft:white_concrete
fill 2493 -57 24 2517 -52 24 minecraft:white_concrete
fill 2495 -57 1 2515 -52 22 minecraft:air
fill 2494 -51 0 2516 -51 23 minecraft:white_concrete
fill 2495 -51 1 2515 -51 1 minecraft:glowstone
fill 2495 -51 22 2515 -51 22 minecraft:glowstone
fill 2495 -51 2 2495 -51 21 minecraft:glowstone
fill 2515 -51 2 2515 -51 21 minecraft:glowstone
fill 2496 -51 2 2514 -51 2 minecraft:glowstone
fill 2496 -51 21 2514 -51 21 minecraft:glowstone
fill 2496 -51 3 2496 -51 20 minecraft:glowstone
fill 2514 -51 3 2514 -51 20 minecraft:glowstone
fill 2497 -51 3 2513 -51 3 minecraft:glowstone
fill 2497 -51 20 2513 -51 20 minecraft:glowstone
fill 2497 -51 4 2497 -51 19 minecraft:glowstone
fill 2513 -51 4 2513 -51 19 minecraft:glowstone
fill 2503 -51 9 2507 -51 13 minecraft:glowstone
fill 2504 -58 11 2506 -58 13 minecraft:blue_concrete
setblock 2496 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2514 -57 18 minecraft:chest
setblock 2496 -57 5 minecraft:bookshelf
setblock 2514 -57 7 minecraft:furnace
setblock 2514 -57 3 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2514 -57 6 minecraft:bookshelf
setblock 2514 -57 20 minecraft:bookshelf
setblock 2496 -57 21 minecraft:chest
setblock 2496 -57 7 minecraft:stone_slab[type=bottom]
setblock 2514 -57 19 minecraft:stone_slab[type=bottom]
