# Scene: maze_medium_13
# Auto-generated by multiagent/scene/generate_scenes.py
fill 4637 -58 0 4659 -58 22 minecraft:white_concrete
fill 4637 -57 0 4659 -40 22 minecraft:white_concrete
fill 4636 -57 0 4636 -40 22 minecraft:white_concrete
fill 4660 -57 0 4660 -40 22 minecraft:white_concrete
fill 4636 -57 -1 4660 -40 -1 minecraft:white_concrete
fill 4636 -57 23 4660 -40 23 minecraft:white_concrete
fill 4638 -57 1 4658 -40 21 minecraft:air
fill 4637 -39 0 4659 -39 22 minecraft:white_concrete
fill 4638 -39 1 4658 -39 1 minecraft:glowstone
fill 4638 -39 21 4658 -39 21 minecraft:glowstone
fill 4638 -39 2 4638 -39 20 minecraft:glowstone
fill 4658 -39 2 4658 -39 20 minecraft:glowstone
fill 4639 -39 2 4657 -39 2 minecraft:glowstone
fill 4639 -39 20 4657 -39 20 minecraft:glowstone
fill 4639 -39 3 4639 -39 19 minecraft:glowstone
fill 4657 -39 3 4657 -39 19 minecraft:glowstone
fill 4640 -39 3 4656 -39 3 minecraft:glowstone
fill 4640 -39 19 4656 -39 19 minecraft:glowstone
fill 4640 -39 4 4640 -39 18 minecraft:glowstone
fill 4656 -39 4 4656 -39 18 minecraft:glowstone
fill 4646 -39 9 4650 -39 13 minecraft:glowstone
fill 4637 -51 0 4659 -51 0 minecraft:glowstone
fill 4637 -51 22 4659 -51 22 minecraft:glowstone
fill 4637 -51 1 4637 -51 21 minecraft:glowstone
fill 4659 -51 1 4659 -51 21 minecraft:glowstone
fill 4641 -57 4 4655 -55 18 minecraft:light_gray_concrete
fill 4641 -57 4 4655 -57 18 minecraft:glowstone
fill 4642 -57 6 4642 -55 6 minecraft:air
fill 4643 -57 6 4643 -55 6 minecraft:air
fill 4643 -57 7 4643 -55 7 minecraft:air
fill 4644 -57 7 4644 -55 7 minecraft:air
fill 4645 -57 7 4645 -55 7 minecraft:air
fill 4646 -57 7 4646 -55 7 minecraft:air
fill 4647 -57 7 4647 -55 7 minecraft:air
fill 4647 -57 8 4647 -55 8 minecraft:air
fill 4647 -57 9 4647 -55 9 minecraft:air
fill 4647 -57 10 4647 -55 10 minecraft:air
fill 4647 -57 11 4647 -55 11 minecraft:air
fill 4647 -57 12 4647 -55 12 minecraft:air
fill 4648 -57 7 4648 -55 7 minecraft:air
fill 4648 -57 8 4648 -55 8 minecraft:air
fill 4648 -57 9 4648 -55 9 minecraft:air
fill 4648 -57 10 4648 -55 10 minecraft:air
fill 4648 -57 11 4648 -55 11 minecraft:air
fill 4648 -57 12 4648 -55 12 minecraft:air
fill 4649 -57 7 4649 -55 7 minecraft:air
fill 4649 -57 8 4649 -55 8 minecraft:air
fill 4650 -57 7 4650 -55 7 minecraft:air
fill 4650 -57 8 4650 -55 8 minecraft:air
fill 4651 -57 7 4651 -55 7 minecraft:air
fill 4651 -57 8 4651 -55 8 minecraft:air
fill 4652 -57 7 4652 -55 7 minecraft:air
fill 4652 -57 8 4652 -55 8 minecraft:air
fill 4651 -58 7 4652 -58 8 minecraft:white_concrete
fill 4647 -58 11 4648 -58 12 minecraft:yellow_concrete
setblock 4643 -57 6 minecraft:chest
setblock 4646 -57 7 minecraft:stone_slab[type=bottom]
setblock 4647 -57 7 minecraft:chest
setblock 4648 -57 9 minecraft:stone_slab[type=bottom]
