# Scene: tier_path_easy_14
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 14 of 15 with 3-5 decorations.
fill 1290 -58 0 1312 -58 30 minecraft:white_concrete
fill 1290 -57 0 1312 -52 30 minecraft:white_concrete
fill 1289 -57 0 1289 -52 30 minecraft:white_concrete
fill 1313 -57 0 1313 -52 30 minecraft:white_concrete
fill 1289 -57 -1 1313 -52 -1 minecraft:white_concrete
fill 1289 -57 31 1313 -52 31 minecraft:white_concrete
fill 1291 -57 1 1311 -52 29 minecraft:air
fill 1290 -51 0 1312 -51 30 minecraft:white_concrete
fill 1291 -51 1 1311 -51 1 minecraft:glowstone
fill 1291 -51 29 1311 -51 29 minecraft:glowstone
fill 1291 -51 2 1291 -51 28 minecraft:glowstone
fill 1311 -51 2 1311 -51 28 minecraft:glowstone
fill 1292 -51 2 1310 -51 2 minecraft:glowstone
fill 1292 -51 28 1310 -51 28 minecraft:glowstone
fill 1292 -51 3 1292 -51 27 minecraft:glowstone
fill 1310 -51 3 1310 -51 27 minecraft:glowstone
fill 1293 -51 3 1309 -51 3 minecraft:glowstone
fill 1293 -51 27 1309 -51 27 minecraft:glowstone
fill 1293 -51 4 1293 -51 26 minecraft:glowstone
fill 1309 -51 4 1309 -51 26 minecraft:glowstone
fill 1299 -51 13 1303 -51 17 minecraft:glowstone
fill 1290 -61 0 1312 -58 30 minecraft:white_concrete
fill 1290 -61 0 1312 -58 12 minecraft:white_concrete
fill 1290 -61 17 1312 -58 30 minecraft:white_concrete
fill 1291 -61 13 1311 -58 16 minecraft:air
fill 1290 -61 0 1312 -61 30 minecraft:black_concrete
fill 1299 -58 13 1302 -58 16 minecraft:air
fill 1299 -57 18 1302 -57 18 minecraft:gold_block
setblock 1300 -57 8 minecraft:spruce_pressure_plate
setblock 1300 -57 9 minecraft:spruce_pressure_plate
setblock 1300 -57 10 minecraft:spruce_pressure_plate
setblock 1300 -57 11 minecraft:spruce_pressure_plate
setblock 1301 -57 8 minecraft:spruce_pressure_plate
setblock 1301 -57 9 minecraft:spruce_pressure_plate
setblock 1301 -57 10 minecraft:spruce_pressure_plate
setblock 1301 -57 11 minecraft:spruce_pressure_plate
setblock 1302 -57 8 minecraft:spruce_pressure_plate
setblock 1302 -57 9 minecraft:spruce_pressure_plate
setblock 1302 -57 10 minecraft:spruce_pressure_plate
setblock 1302 -57 11 minecraft:spruce_pressure_plate
setblock 1303 -57 8 minecraft:spruce_pressure_plate
setblock 1303 -57 9 minecraft:spruce_pressure_plate
setblock 1303 -57 10 minecraft:spruce_pressure_plate
setblock 1303 -57 11 minecraft:spruce_pressure_plate
setblock 1292 -57 5 minecraft:crafting_table
setblock 1292 -57 6 minecraft:furnace
setblock 1302 -57 2 minecraft:crafting_table
setblock 1306 -57 2 minecraft:crafting_table
setblock 1292 -57 9 minecraft:furnace

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_easy_14/place_command_blocks
