# Scene: tier_path_medium_03
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 3 of 15 with 3-5 decorations.
fill 1411 -58 0 1431 -58 31 minecraft:white_concrete
fill 1411 -57 0 1431 -52 31 minecraft:white_concrete
fill 1410 -57 0 1410 -52 31 minecraft:white_concrete
fill 1432 -57 0 1432 -52 31 minecraft:white_concrete
fill 1410 -57 -1 1432 -52 -1 minecraft:white_concrete
fill 1410 -57 32 1432 -52 32 minecraft:white_concrete
fill 1412 -57 1 1430 -52 30 minecraft:air
fill 1411 -51 0 1431 -51 31 minecraft:white_concrete
fill 1412 -51 1 1430 -51 1 minecraft:glowstone
fill 1412 -51 30 1430 -51 30 minecraft:glowstone
fill 1412 -51 2 1412 -51 29 minecraft:glowstone
fill 1430 -51 2 1430 -51 29 minecraft:glowstone
fill 1413 -51 2 1429 -51 2 minecraft:glowstone
fill 1413 -51 29 1429 -51 29 minecraft:glowstone
fill 1413 -51 3 1413 -51 28 minecraft:glowstone
fill 1429 -51 3 1429 -51 28 minecraft:glowstone
fill 1414 -51 3 1428 -51 3 minecraft:glowstone
fill 1414 -51 28 1428 -51 28 minecraft:glowstone
fill 1414 -51 4 1414 -51 27 minecraft:glowstone
fill 1428 -51 4 1428 -51 27 minecraft:glowstone
fill 1419 -51 13 1423 -51 17 minecraft:glowstone
fill 1411 -61 0 1431 -58 31 minecraft:white_concrete
fill 1411 -61 0 1431 -58 12 minecraft:white_concrete
fill 1411 -61 18 1431 -58 31 minecraft:white_concrete
fill 1412 -61 13 1430 -58 17 minecraft:air
fill 1411 -61 0 1431 -61 31 minecraft:black_concrete
fill 1420 -58 13 1422 -58 17 minecraft:air
fill 1420 -57 19 1422 -57 19 minecraft:gold_block
setblock 1420 -57 8 minecraft:oak_pressure_plate
setblock 1420 -57 9 minecraft:oak_pressure_plate
setblock 1420 -57 10 minecraft:oak_pressure_plate
setblock 1421 -57 8 minecraft:oak_pressure_plate
setblock 1421 -57 9 minecraft:oak_pressure_plate
setblock 1421 -57 10 minecraft:oak_pressure_plate
setblock 1422 -57 8 minecraft:oak_pressure_plate
setblock 1422 -57 9 minecraft:oak_pressure_plate
setblock 1422 -57 10 minecraft:oak_pressure_plate
setblock 1418 -57 2 minecraft:chest
setblock 1413 -57 11 minecraft:chest
setblock 1413 -57 2 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_03/place_command_blocks
