# Scene: truck_medium_12
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2620 -58 0 2642 -58 23 minecraft:white_concrete
fill 2620 -57 0 2642 -52 23 minecraft:white_concrete
fill 2619 -57 0 2619 -52 23 minecraft:white_concrete
fill 2643 -57 0 2643 -52 23 minecraft:white_concrete
fill 2619 -57 -1 2643 -52 -1 minecraft:white_concrete
fill 2619 -57 24 2643 -52 24 minecraft:white_concrete
fill 2621 -57 1 2641 -52 22 minecraft:air
fill 2620 -51 0 2642 -51 23 minecraft:white_concrete
fill 2621 -51 1 2641 -51 1 minecraft:glowstone
fill 2621 -51 22 2641 -51 22 minecraft:glowstone
fill 2621 -51 2 2621 -51 21 minecraft:glowstone
fill 2641 -51 2 2641 -51 21 minecraft:glowstone
fill 2622 -51 2 2640 -51 2 minecraft:glowstone
fill 2622 -51 21 2640 -51 21 minecraft:glowstone
fill 2622 -51 3 2622 -51 20 minecraft:glowstone
fill 2640 -51 3 2640 -51 20 minecraft:glowstone
fill 2623 -51 3 2639 -51 3 minecraft:glowstone
fill 2623 -51 20 2639 -51 20 minecraft:glowstone
fill 2623 -51 4 2623 -51 19 minecraft:glowstone
fill 2639 -51 4 2639 -51 19 minecraft:glowstone
fill 2629 -51 9 2633 -51 13 minecraft:glowstone
fill 2630 -58 11 2632 -58 13 minecraft:orange_concrete
setblock 2622 -57 4 minecraft:stone_slab[type=bottom]
setblock 2640 -57 17 minecraft:crafting_table
setblock 2622 -57 7 minecraft:chest
setblock 2622 -57 21 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2622 -57 11 minecraft:chest
setblock 2622 -57 17 minecraft:bookshelf
setblock 2622 -57 8 minecraft:bookshelf
setblock 2640 -57 7 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2622 -57 3 minecraft:furnace
setblock 2622 -57 2 minecraft:chest
setblock 2640 -57 14 minecraft:crafting_table
setblock 2622 -57 18 minecraft:chest
setblock 2640 -57 10 minecraft:chest
setblock 2622 -57 13 minecraft:bookshelf
