# Scene: tier_elevator_medium_09
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 9 of 15 with 3-5 decorations.
fill 691 -59 0 711 -59 23 minecraft:white_concrete
fill 691 -58 0 711 -53 23 minecraft:white_concrete
fill 690 -58 0 690 -53 23 minecraft:white_concrete
fill 712 -58 0 712 -53 23 minecraft:white_concrete
fill 690 -58 -1 712 -53 -1 minecraft:white_concrete
fill 690 -58 24 712 -53 24 minecraft:white_concrete
fill 692 -58 1 710 -53 22 minecraft:air
fill 691 -52 0 711 -52 23 minecraft:white_concrete
fill 692 -52 1 710 -52 1 minecraft:glowstone
fill 692 -52 22 710 -52 22 minecraft:glowstone
fill 692 -52 2 692 -52 21 minecraft:glowstone
fill 710 -52 2 710 -52 21 minecraft:glowstone
fill 693 -52 2 709 -52 2 minecraft:glowstone
fill 693 -52 21 709 -52 21 minecraft:glowstone
fill 693 -52 3 693 -52 20 minecraft:glowstone
fill 709 -52 3 709 -52 20 minecraft:glowstone
fill 694 -52 3 708 -52 3 minecraft:glowstone
fill 694 -52 20 708 -52 20 minecraft:glowstone
fill 694 -52 4 694 -52 19 minecraft:glowstone
fill 708 -52 4 708 -52 19 minecraft:glowstone
fill 699 -52 9 703 -52 13 minecraft:glowstone
fill 692 -58 12 710 -53 12 minecraft:white_concrete
fill 699 -58 12 700 -56 12 minecraft:brown_concrete
setblock 701 -58 7 minecraft:dark_oak_pressure_plate
setblock 701 -58 8 minecraft:dark_oak_pressure_plate
setblock 701 -58 9 minecraft:dark_oak_pressure_plate
setblock 702 -58 7 minecraft:dark_oak_pressure_plate
setblock 702 -58 8 minecraft:dark_oak_pressure_plate
setblock 702 -58 9 minecraft:dark_oak_pressure_plate
setblock 703 -58 7 minecraft:dark_oak_pressure_plate
setblock 703 -58 8 minecraft:dark_oak_pressure_plate
setblock 703 -58 9 minecraft:dark_oak_pressure_plate
setblock 699 -58 2 minecraft:stone_slab[type=bottom]
setblock 700 -58 2 minecraft:crafting_table
setblock 693 -58 7 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 706 -58 2 minecraft:chest

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_09/place_command_blocks
