# Scene: tier_path_hard_07
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 7 of 15 with 3-5 decorations.
fill 1980 -58 0 2001 -58 31 minecraft:white_concrete
fill 1980 -57 0 2001 -52 31 minecraft:white_concrete
fill 1979 -57 0 1979 -52 31 minecraft:white_concrete
fill 2002 -57 0 2002 -52 31 minecraft:white_concrete
fill 1979 -57 -1 2002 -52 -1 minecraft:white_concrete
fill 1979 -57 32 2002 -52 32 minecraft:white_concrete
fill 1981 -57 1 2000 -52 30 minecraft:air
fill 1980 -51 0 2001 -51 31 minecraft:white_concrete
fill 1981 -51 1 2000 -51 1 minecraft:glowstone
fill 1981 -51 30 2000 -51 30 minecraft:glowstone
fill 1981 -51 2 1981 -51 29 minecraft:glowstone
fill 2000 -51 2 2000 -51 29 minecraft:glowstone
fill 1982 -51 2 1999 -51 2 minecraft:glowstone
fill 1982 -51 29 1999 -51 29 minecraft:glowstone
fill 1982 -51 3 1982 -51 28 minecraft:glowstone
fill 1999 -51 3 1999 -51 28 minecraft:glowstone
fill 1983 -51 3 1998 -51 3 minecraft:glowstone
fill 1983 -51 28 1998 -51 28 minecraft:glowstone
fill 1983 -51 4 1983 -51 27 minecraft:glowstone
fill 1998 -51 4 1998 -51 27 minecraft:glowstone
fill 1988 -51 13 1992 -51 17 minecraft:glowstone
fill 1980 -61 0 2001 -58 31 minecraft:white_concrete
fill 1980 -61 0 2001 -58 12 minecraft:white_concrete
fill 1980 -61 19 2001 -58 31 minecraft:white_concrete
fill 1981 -61 13 2000 -58 18 minecraft:air
fill 1980 -61 0 2001 -61 31 minecraft:black_concrete
fill 1989 -58 13 1991 -58 18 minecraft:air
fill 1989 -57 20 1991 -57 20 minecraft:gold_block
setblock 1990 -57 8 minecraft:acacia_pressure_plate
setblock 1990 -57 9 minecraft:acacia_pressure_plate
setblock 1990 -57 10 minecraft:acacia_pressure_plate
setblock 1991 -57 8 minecraft:acacia_pressure_plate
setblock 1991 -57 9 minecraft:acacia_pressure_plate
setblock 1991 -57 10 minecraft:acacia_pressure_plate
setblock 1992 -57 8 minecraft:acacia_pressure_plate
setblock 1992 -57 9 minecraft:acacia_pressure_plate
setblock 1992 -57 10 minecraft:acacia_pressure_plate
setblock 1999 -57 10 minecraft:furnace
setblock 1986 -57 2 minecraft:crafting_table
setblock 1982 -57 9 minecraft:stone_slab[type=bottom]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_07/place_command_blocks
