# Scene: tier_elevator_easy_11
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 11 of 15 with 3-5 decorations.
fill 300 -59 0 322 -59 23 minecraft:white_concrete
fill 300 -58 0 322 -53 23 minecraft:white_concrete
fill 299 -58 0 299 -53 23 minecraft:white_concrete
fill 323 -58 0 323 -53 23 minecraft:white_concrete
fill 299 -58 -1 323 -53 -1 minecraft:white_concrete
fill 299 -58 24 323 -53 24 minecraft:white_concrete
fill 301 -58 1 321 -53 22 minecraft:air
fill 300 -52 0 322 -52 23 minecraft:white_concrete
fill 301 -52 1 321 -52 1 minecraft:glowstone
fill 301 -52 22 321 -52 22 minecraft:glowstone
fill 301 -52 2 301 -52 21 minecraft:glowstone
fill 321 -52 2 321 -52 21 minecraft:glowstone
fill 302 -52 2 320 -52 2 minecraft:glowstone
fill 302 -52 21 320 -52 21 minecraft:glowstone
fill 302 -52 3 302 -52 20 minecraft:glowstone
fill 320 -52 3 320 -52 20 minecraft:glowstone
fill 303 -52 3 319 -52 3 minecraft:glowstone
fill 303 -52 20 319 -52 20 minecraft:glowstone
fill 303 -52 4 303 -52 19 minecraft:glowstone
fill 319 -52 4 319 -52 19 minecraft:glowstone
fill 309 -52 9 313 -52 13 minecraft:glowstone
fill 301 -58 12 321 -53 12 minecraft:white_concrete
fill 311 -58 12 313 -56 12 minecraft:light_gray_concrete
setblock 310 -58 7 minecraft:oak_pressure_plate
setblock 310 -58 8 minecraft:oak_pressure_plate
setblock 310 -58 9 minecraft:oak_pressure_plate
setblock 310 -58 10 minecraft:oak_pressure_plate
setblock 311 -58 7 minecraft:oak_pressure_plate
setblock 311 -58 8 minecraft:oak_pressure_plate
setblock 311 -58 9 minecraft:oak_pressure_plate
setblock 311 -58 10 minecraft:oak_pressure_plate
setblock 312 -58 7 minecraft:oak_pressure_plate
setblock 312 -58 8 minecraft:oak_pressure_plate
setblock 312 -58 9 minecraft:oak_pressure_plate
setblock 312 -58 10 minecraft:oak_pressure_plate
setblock 313 -58 7 minecraft:oak_pressure_plate
setblock 313 -58 8 minecraft:oak_pressure_plate
setblock 313 -58 9 minecraft:oak_pressure_plate
setblock 313 -58 10 minecraft:oak_pressure_plate
setblock 320 -58 3 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 319 -58 2 minecraft:bookshelf
setblock 320 -58 4 minecraft:crafting_table
setblock 320 -58 9 minecraft:furnace
setblock 320 -58 7 minecraft:bookshelf

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_easy_11/place_command_blocks
