# Scene: truck_hard_14
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3156 -58 0 3178 -58 23 minecraft:white_concrete
fill 3156 -57 0 3178 -52 23 minecraft:white_concrete
fill 3155 -57 0 3155 -52 23 minecraft:white_concrete
fill 3179 -57 0 3179 -52 23 minecraft:white_concrete
fill 3155 -57 -1 3179 -52 -1 minecraft:white_concrete
fill 3155 -57 24 3179 -52 24 minecraft:white_concrete
fill 3157 -57 1 3177 -52 22 minecraft:air
fill 3156 -51 0 3178 -51 23 minecraft:white_concrete
fill 3157 -51 1 3177 -51 1 minecraft:glowstone
fill 3157 -51 22 3177 -51 22 minecraft:glowstone
fill 3157 -51 2 3157 -51 21 minecraft:glowstone
fill 3177 -51 2 3177 -51 21 minecraft:glowstone
fill 3158 -51 2 3176 -51 2 minecraft:glowstone
fill 3158 -51 21 3176 -51 21 minecraft:glowstone
fill 3158 -51 3 3158 -51 20 minecraft:glowstone
fill 3176 -51 3 3176 -51 20 minecraft:glowstone
fill 3159 -51 3 3175 -51 3 minecraft:glowstone
fill 3159 -51 20 3175 -51 20 minecraft:glowstone
fill 3159 -51 4 3159 -51 19 minecraft:glowstone
fill 3175 -51 4 3175 -51 19 minecraft:glowstone
fill 3165 -51 9 3169 -51 13 minecraft:glowstone
fill 3167 -58 12 3168 -58 13 minecraft:lime_concrete
setblock 3158 -57 12 minecraft:crafting_table
setblock 3176 -57 5 minecraft:chest
setblock 3176 -57 17 minecraft:furnace
setblock 3158 -57 10 minecraft:bookshelf
setblock 3158 -57 14 minecraft:stone_slab[type=bottom]
setblock 3176 -57 11 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3176 -57 14 minecraft:bookshelf
setblock 3158 -57 16 minecraft:stone_slab[type=bottom]
setblock 3158 -57 11 minecraft:furnace
setblock 3158 -57 7 minecraft:stone_slab[type=bottom]
setblock 3176 -57 19 minecraft:stone_slab[type=bottom]
setblock 3176 -57 20 minecraft:chest
setblock 3176 -57 7 minecraft:stone_slab[type=bottom]
setblock 3158 -57 17 minecraft:furnace
setblock 3158 -57 5 minecraft:stone_slab[type=bottom]
