# Scene: truck_hard_13
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3124 -58 0 3147 -58 22 minecraft:white_concrete
fill 3124 -57 0 3147 -52 22 minecraft:white_concrete
fill 3123 -57 0 3123 -52 22 minecraft:white_concrete
fill 3148 -57 0 3148 -52 22 minecraft:white_concrete
fill 3123 -57 -1 3148 -52 -1 minecraft:white_concrete
fill 3123 -57 23 3148 -52 23 minecraft:white_concrete
fill 3125 -57 1 3146 -52 21 minecraft:air
fill 3124 -51 0 3147 -51 22 minecraft:white_concrete
fill 3125 -51 1 3146 -51 1 minecraft:glowstone
fill 3125 -51 21 3146 -51 21 minecraft:glowstone
fill 3125 -51 2 3125 -51 20 minecraft:glowstone
fill 3146 -51 2 3146 -51 20 minecraft:glowstone
fill 3126 -51 2 3145 -51 2 minecraft:glowstone
fill 3126 -51 20 3145 -51 20 minecraft:glowstone
fill 3126 -51 3 3126 -51 19 minecraft:glowstone
fill 3145 -51 3 3145 -51 19 minecraft:glowstone
fill 3127 -51 3 3144 -51 3 minecraft:glowstone
fill 3127 -51 19 3144 -51 19 minecraft:glowstone
fill 3127 -51 4 3127 -51 18 minecraft:glowstone
fill 3144 -51 4 3144 -51 18 minecraft:glowstone
fill 3133 -51 9 3137 -51 13 minecraft:glowstone
fill 3136 -58 11 3137 -58 12 minecraft:yellow_concrete
setblock 3126 -57 3 minecraft:stone_slab[type=bottom]
setblock 3145 -57 11 minecraft:stone_slab[type=bottom]
setblock 3145 -57 7 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3145 -57 15 minecraft:chest
setblock 3145 -57 19 minecraft:chest
setblock 3145 -57 6 minecraft:crafting_table
setblock 3145 -57 10 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3126 -57 15 minecraft:bookshelf
setblock 3126 -57 6 minecraft:crafting_table
setblock 3145 -57 3 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3126 -57 14 minecraft:furnace
setblock 3145 -57 17 minecraft:bookshelf
setblock 3145 -57 9 minecraft:crafting_table
setblock 3145 -57 18 minecraft:furnace
