# Scene: tier_elevator_medium_14
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 14 of 15 with 3-5 decorations.
fill 840 -59 0 862 -59 22 minecraft:white_concrete
fill 840 -58 0 862 -53 22 minecraft:white_concrete
fill 839 -58 0 839 -53 22 minecraft:white_concrete
fill 863 -58 0 863 -53 22 minecraft:white_concrete
fill 839 -58 -1 863 -53 -1 minecraft:white_concrete
fill 839 -58 23 863 -53 23 minecraft:white_concrete
fill 841 -58 1 861 -53 21 minecraft:air
fill 840 -52 0 862 -52 22 minecraft:white_concrete
fill 841 -52 1 861 -52 1 minecraft:glowstone
fill 841 -52 21 861 -52 21 minecraft:glowstone
fill 841 -52 2 841 -52 20 minecraft:glowstone
fill 861 -52 2 861 -52 20 minecraft:glowstone
fill 842 -52 2 860 -52 2 minecraft:glowstone
fill 842 -52 20 860 -52 20 minecraft:glowstone
fill 842 -52 3 842 -52 19 minecraft:glowstone
fill 860 -52 3 860 -52 19 minecraft:glowstone
fill 843 -52 3 859 -52 3 minecraft:glowstone
fill 843 -52 19 859 -52 19 minecraft:glowstone
fill 843 -52 4 843 -52 18 minecraft:glowstone
fill 859 -52 4 859 -52 18 minecraft:glowstone
fill 849 -52 9 853 -52 13 minecraft:glowstone
fill 841 -58 11 861 -53 11 minecraft:white_concrete
fill 851 -58 11 852 -56 11 minecraft:brown_concrete
setblock 851 -58 5 minecraft:mangrove_pressure_plate
setblock 851 -58 6 minecraft:mangrove_pressure_plate
setblock 851 -58 7 minecraft:mangrove_pressure_plate
setblock 852 -58 5 minecraft:mangrove_pressure_plate
setblock 852 -58 6 minecraft:mangrove_pressure_plate
setblock 852 -58 7 minecraft:mangrove_pressure_plate
setblock 853 -58 5 minecraft:mangrove_pressure_plate
setblock 853 -58 6 minecraft:mangrove_pressure_plate
setblock 853 -58 7 minecraft:mangrove_pressure_plate
setblock 842 -58 6 minecraft:bookshelf
setblock 855 -58 2 minecraft:furnace
setblock 860 -58 6 minecraft:furnace
setblock 842 -58 8 minecraft:bookshelf
setblock 850 -58 2 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_14/place_command_blocks
