# Scene: tier_path_medium_13
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 13 of 15 with 3-5 decorations.
fill 1710 -58 0 1731 -58 31 minecraft:white_concrete
fill 1710 -57 0 1731 -52 31 minecraft:white_concrete
fill 1709 -57 0 1709 -52 31 minecraft:white_concrete
fill 1732 -57 0 1732 -52 31 minecraft:white_concrete
fill 1709 -57 -1 1732 -52 -1 minecraft:white_concrete
fill 1709 -57 32 1732 -52 32 minecraft:white_concrete
fill 1711 -57 1 1730 -52 30 minecraft:air
fill 1710 -51 0 1731 -51 31 minecraft:white_concrete
fill 1711 -51 1 1730 -51 1 minecraft:glowstone
fill 1711 -51 30 1730 -51 30 minecraft:glowstone
fill 1711 -51 2 1711 -51 29 minecraft:glowstone
fill 1730 -51 2 1730 -51 29 minecraft:glowstone
fill 1712 -51 2 1729 -51 2 minecraft:glowstone
fill 1712 -51 29 1729 -51 29 minecraft:glowstone
fill 1712 -51 3 1712 -51 28 minecraft:glowstone
fill 1729 -51 3 1729 -51 28 minecraft:glowstone
fill 1713 -51 3 1728 -51 3 minecraft:glowstone
fill 1713 -51 28 1728 -51 28 minecraft:glowstone
fill 1713 -51 4 1713 -51 27 minecraft:glowstone
fill 1728 -51 4 1728 -51 27 minecraft:glowstone
fill 1718 -51 13 1722 -51 17 minecraft:glowstone
fill 1710 -61 0 1731 -58 31 minecraft:white_concrete
fill 1710 -61 0 1731 -58 12 minecraft:white_concrete
fill 1710 -61 18 1731 -58 31 minecraft:white_concrete
fill 1711 -61 13 1730 -58 17 minecraft:air
fill 1710 -61 0 1731 -61 31 minecraft:black_concrete
fill 1719 -58 13 1721 -58 17 minecraft:air
fill 1719 -57 19 1721 -57 19 minecraft:gold_block
setblock 1720 -57 8 minecraft:oak_pressure_plate
setblock 1720 -57 9 minecraft:oak_pressure_plate
setblock 1720 -57 10 minecraft:oak_pressure_plate
setblock 1721 -57 8 minecraft:oak_pressure_plate
setblock 1721 -57 9 minecraft:oak_pressure_plate
setblock 1721 -57 10 minecraft:oak_pressure_plate
setblock 1722 -57 8 minecraft:oak_pressure_plate
setblock 1722 -57 9 minecraft:oak_pressure_plate
setblock 1722 -57 10 minecraft:oak_pressure_plate
setblock 1712 -57 7 minecraft:furnace
setblock 1729 -57 11 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1729 -57 3 minecraft:crafting_table
setblock 1712 -57 10 minecraft:stone_slab[type=bottom]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_13/place_command_blocks
