# Scene: maze_easy_12
# Auto-generated by multiagent/scene/generate_scenes.py
fill 4141 -58 0 4163 -58 22 minecraft:white_concrete
fill 4141 -57 0 4163 -40 22 minecraft:white_concrete
fill 4140 -57 0 4140 -40 22 minecraft:white_concrete
fill 4164 -57 0 4164 -40 22 minecraft:white_concrete
fill 4140 -57 -1 4164 -40 -1 minecraft:white_concrete
fill 4140 -57 23 4164 -40 23 minecraft:white_concrete
fill 4142 -57 1 4162 -40 21 minecraft:air
fill 4141 -39 0 4163 -39 22 minecraft:white_concrete
fill 4142 -39 1 4162 -39 1 minecraft:glowstone
fill 4142 -39 21 4162 -39 21 minecraft:glowstone
fill 4142 -39 2 4142 -39 20 minecraft:glowstone
fill 4162 -39 2 4162 -39 20 minecraft:glowstone
fill 4143 -39 2 4161 -39 2 minecraft:glowstone
fill 4143 -39 20 4161 -39 20 minecraft:glowstone
fill 4143 -39 3 4143 -39 19 minecraft:glowstone
fill 4161 -39 3 4161 -39 19 minecraft:glowstone
fill 4144 -39 3 4160 -39 3 minecraft:glowstone
fill 4144 -39 19 4160 -39 19 minecraft:glowstone
fill 4144 -39 4 4144 -39 18 minecraft:glowstone
fill 4160 -39 4 4160 -39 18 minecraft:glowstone
fill 4150 -39 9 4154 -39 13 minecraft:glowstone
fill 4141 -51 0 4163 -51 0 minecraft:glowstone
fill 4141 -51 22 4163 -51 22 minecraft:glowstone
fill 4141 -51 1 4141 -51 21 minecraft:glowstone
fill 4163 -51 1 4163 -51 21 minecraft:glowstone
fill 4145 -57 4 4159 -55 18 minecraft:light_gray_concrete
fill 4145 -57 4 4159 -57 18 minecraft:glowstone
fill 4148 -57 7 4148 -55 7 minecraft:air
fill 4148 -57 8 4148 -55 8 minecraft:air
fill 4148 -57 9 4148 -55 9 minecraft:air
fill 4148 -57 10 4148 -55 10 minecraft:air
fill 4148 -57 11 4148 -55 11 minecraft:air
fill 4148 -57 12 4148 -55 12 minecraft:air
fill 4148 -57 13 4148 -55 13 minecraft:air
fill 4148 -57 14 4148 -55 14 minecraft:air
fill 4149 -57 7 4149 -55 7 minecraft:air
fill 4149 -57 8 4149 -55 8 minecraft:air
fill 4149 -57 9 4149 -55 9 minecraft:air
fill 4149 -57 10 4149 -55 10 minecraft:air
fill 4149 -57 11 4149 -55 11 minecraft:air
fill 4149 -57 12 4149 -55 12 minecraft:air
fill 4149 -57 13 4149 -55 13 minecraft:air
fill 4149 -57 14 4149 -55 14 minecraft:air
fill 4148 -58 7 4149 -58 8 minecraft:white_concrete
fill 4148 -58 13 4149 -58 14 minecraft:orange_concrete
setblock 4148 -57 9 minecraft:stone_slab[type=bottom]
setblock 4148 -57 11 minecraft:stone_slab[type=bottom]
setblock 4148 -57 12 minecraft:furnace
