# Scene: tier_elevator_medium_04
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 4 of 15 with 3-5 decorations.
fill 540 -59 0 561 -59 22 minecraft:white_concrete
fill 540 -58 0 561 -53 22 minecraft:white_concrete
fill 539 -58 0 539 -53 22 minecraft:white_concrete
fill 562 -58 0 562 -53 22 minecraft:white_concrete
fill 539 -58 -1 562 -53 -1 minecraft:white_concrete
fill 539 -58 23 562 -53 23 minecraft:white_concrete
fill 541 -58 1 560 -53 21 minecraft:air
fill 540 -52 0 561 -52 22 minecraft:white_concrete
fill 541 -52 1 560 -52 1 minecraft:glowstone
fill 541 -52 21 560 -52 21 minecraft:glowstone
fill 541 -52 2 541 -52 20 minecraft:glowstone
fill 560 -52 2 560 -52 20 minecraft:glowstone
fill 542 -52 2 559 -52 2 minecraft:glowstone
fill 542 -52 20 559 -52 20 minecraft:glowstone
fill 542 -52 3 542 -52 19 minecraft:glowstone
fill 559 -52 3 559 -52 19 minecraft:glowstone
fill 543 -52 3 558 -52 3 minecraft:glowstone
fill 543 -52 19 558 -52 19 minecraft:glowstone
fill 543 -52 4 543 -52 18 minecraft:glowstone
fill 558 -52 4 558 -52 18 minecraft:glowstone
fill 548 -52 9 552 -52 13 minecraft:glowstone
fill 541 -58 11 560 -53 11 minecraft:white_concrete
fill 550 -58 11 551 -56 11 minecraft:brown_concrete
setblock 551 -58 5 minecraft:acacia_pressure_plate
setblock 551 -58 6 minecraft:acacia_pressure_plate
setblock 551 -58 7 minecraft:acacia_pressure_plate
setblock 552 -58 5 minecraft:acacia_pressure_plate
setblock 552 -58 6 minecraft:acacia_pressure_plate
setblock 552 -58 7 minecraft:acacia_pressure_plate
setblock 553 -58 5 minecraft:acacia_pressure_plate
setblock 553 -58 6 minecraft:acacia_pressure_plate
setblock 553 -58 7 minecraft:acacia_pressure_plate
setblock 550 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 554 -58 2 minecraft:furnace
setblock 542 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 543 -58 2 minecraft:furnace

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_04/place_command_blocks
