# Scene: picture_hard_07
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3700 -58 0 3716 -58 18 minecraft:white_concrete
fill 3700 -57 0 3716 -49 18 minecraft:white_concrete
fill 3699 -57 0 3699 -49 18 minecraft:white_concrete
fill 3717 -57 0 3717 -49 18 minecraft:white_concrete
fill 3699 -57 -1 3717 -49 -1 minecraft:white_concrete
fill 3699 -57 19 3717 -49 19 minecraft:white_concrete
fill 3701 -57 1 3715 -49 17 minecraft:air
fill 3700 -48 0 3716 -48 18 minecraft:white_concrete
fill 3701 -48 1 3715 -48 1 minecraft:glowstone
fill 3701 -48 17 3715 -48 17 minecraft:glowstone
fill 3701 -48 2 3701 -48 16 minecraft:glowstone
fill 3715 -48 2 3715 -48 16 minecraft:glowstone
fill 3702 -48 2 3714 -48 2 minecraft:glowstone
fill 3702 -48 16 3714 -48 16 minecraft:glowstone
fill 3702 -48 3 3702 -48 15 minecraft:glowstone
fill 3714 -48 3 3714 -48 15 minecraft:glowstone
fill 3703 -48 3 3713 -48 3 minecraft:glowstone
fill 3703 -48 15 3713 -48 15 minecraft:glowstone
fill 3703 -48 4 3703 -48 14 minecraft:glowstone
fill 3713 -48 4 3713 -48 14 minecraft:glowstone
fill 3706 -48 7 3710 -48 11 minecraft:glowstone
fill 3701 -53 1 3715 -53 5 minecraft:glowstone
fill 3701 -52 1 3715 -52 5 minecraft:smooth_stone
fill 3701 -51 6 3715 -51 6 minecraft:oak_fence
fill 3704 -57 2 3706 -57 4 minecraft:light_blue_concrete
fill 3708 -52 10 3708 -52 10 minecraft:smooth_stone
setblock 3709 -51 5 minecraft:stone_slab[type=bottom]
setblock 3707 -51 1 minecraft:furnace
setblock 3708 -51 3 minecraft:crafting_table
setblock 3712 -51 1 minecraft:stone_slab[type=bottom]
setblock 3714 -51 4 minecraft:bookshelf
