# Scene: tier_path_medium_14
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 14 of 15 with 3-5 decorations.
fill 1740 -58 0 1762 -58 30 minecraft:white_concrete
fill 1740 -57 0 1762 -52 30 minecraft:white_concrete
fill 1739 -57 0 1739 -52 30 minecraft:white_concrete
fill 1763 -57 0 1763 -52 30 minecraft:white_concrete
fill 1739 -57 -1 1763 -52 -1 minecraft:white_concrete
fill 1739 -57 31 1763 -52 31 minecraft:white_concrete
fill 1741 -57 1 1761 -52 29 minecraft:air
fill 1740 -51 0 1762 -51 30 minecraft:white_concrete
fill 1741 -51 1 1761 -51 1 minecraft:glowstone
fill 1741 -51 29 1761 -51 29 minecraft:glowstone
fill 1741 -51 2 1741 -51 28 minecraft:glowstone
fill 1761 -51 2 1761 -51 28 minecraft:glowstone
fill 1742 -51 2 1760 -51 2 minecraft:glowstone
fill 1742 -51 28 1760 -51 28 minecraft:glowstone
fill 1742 -51 3 1742 -51 27 minecraft:glowstone
fill 1760 -51 3 1760 -51 27 minecraft:glowstone
fill 1743 -51 3 1759 -51 3 minecraft:glowstone
fill 1743 -51 27 1759 -51 27 minecraft:glowstone
fill 1743 -51 4 1743 -51 26 minecraft:glowstone
fill 1759 -51 4 1759 -51 26 minecraft:glowstone
fill 1749 -51 13 1753 -51 17 minecraft:glowstone
fill 1740 -61 0 1762 -58 30 minecraft:white_concrete
fill 1740 -61 0 1762 -58 12 minecraft:white_concrete
fill 1740 -61 18 1762 -58 30 minecraft:white_concrete
fill 1741 -61 13 1761 -58 17 minecraft:air
fill 1740 -61 0 1762 -61 30 minecraft:black_concrete
fill 1750 -58 13 1752 -58 17 minecraft:air
fill 1750 -57 19 1752 -57 19 minecraft:gold_block
setblock 1750 -57 8 minecraft:spruce_pressure_plate
setblock 1750 -57 9 minecraft:spruce_pressure_plate
setblock 1750 -57 10 minecraft:spruce_pressure_plate
setblock 1751 -57 8 minecraft:spruce_pressure_plate
setblock 1751 -57 9 minecraft:spruce_pressure_plate
setblock 1751 -57 10 minecraft:spruce_pressure_plate
setblock 1752 -57 8 minecraft:spruce_pressure_plate
setblock 1752 -57 9 minecraft:spruce_pressure_plate
setblock 1752 -57 10 minecraft:spruce_pressure_plate
setblock 1760 -57 9 minecraft:chest
setblock 1760 -57 8 minecraft:bookshelf
setblock 1742 -57 9 minecraft:chest
setblock 1742 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1760 -57 11 minecraft:chest

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_14/place_command_blocks
