# Scene: tier_path_hard_09
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 9 of 15 with 3-5 decorations.
fill 2041 -58 0 2061 -58 31 minecraft:white_concrete
fill 2041 -57 0 2061 -52 31 minecraft:white_concrete
fill 2040 -57 0 2040 -52 31 minecraft:white_concrete
fill 2062 -57 0 2062 -52 31 minecraft:white_concrete
fill 2040 -57 -1 2062 -52 -1 minecraft:white_concrete
fill 2040 -57 32 2062 -52 32 minecraft:white_concrete
fill 2042 -57 1 2060 -52 30 minecraft:air
fill 2041 -51 0 2061 -51 31 minecraft:white_concrete
fill 2042 -51 1 2060 -51 1 minecraft:glowstone
fill 2042 -51 30 2060 -51 30 minecraft:glowstone
fill 2042 -51 2 2042 -51 29 minecraft:glowstone
fill 2060 -51 2 2060 -51 29 minecraft:glowstone
fill 2043 -51 2 2059 -51 2 minecraft:glowstone
fill 2043 -51 29 2059 -51 29 minecraft:glowstone
fill 2043 -51 3 2043 -51 28 minecraft:glowstone
fill 2059 -51 3 2059 -51 28 minecraft:glowstone
fill 2044 -51 3 2058 -51 3 minecraft:glowstone
fill 2044 -51 28 2058 -51 28 minecraft:glowstone
fill 2044 -51 4 2044 -51 27 minecraft:glowstone
fill 2058 -51 4 2058 -51 27 minecraft:glowstone
fill 2049 -51 13 2053 -51 17 minecraft:glowstone
fill 2041 -61 0 2061 -58 31 minecraft:white_concrete
fill 2041 -61 0 2061 -58 12 minecraft:white_concrete
fill 2041 -61 19 2061 -58 31 minecraft:white_concrete
fill 2042 -61 13 2060 -58 18 minecraft:air
fill 2041 -61 0 2061 -61 31 minecraft:black_concrete
fill 2050 -58 13 2052 -58 18 minecraft:air
fill 2050 -57 20 2052 -57 20 minecraft:gold_block
setblock 2050 -57 8 minecraft:mangrove_pressure_plate
setblock 2050 -57 9 minecraft:mangrove_pressure_plate
setblock 2050 -57 10 minecraft:mangrove_pressure_plate
setblock 2051 -57 8 minecraft:mangrove_pressure_plate
setblock 2051 -57 9 minecraft:mangrove_pressure_plate
setblock 2051 -57 10 minecraft:mangrove_pressure_plate
setblock 2052 -57 8 minecraft:mangrove_pressure_plate
setblock 2052 -57 9 minecraft:mangrove_pressure_plate
setblock 2052 -57 10 minecraft:mangrove_pressure_plate
setblock 2050 -57 2 minecraft:bookshelf
setblock 2044 -57 2 minecraft:crafting_table
setblock 2059 -57 6 minecraft:chest
setblock 2059 -57 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2059 -57 5 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_09/place_command_blocks
