# Scene: picture_easy_12
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3075 -58 0 3091 -58 18 minecraft:white_concrete
fill 3075 -57 0 3091 -49 18 minecraft:white_concrete
fill 3074 -57 0 3074 -49 18 minecraft:white_concrete
fill 3092 -57 0 3092 -49 18 minecraft:white_concrete
fill 3074 -57 -1 3092 -49 -1 minecraft:white_concrete
fill 3074 -57 19 3092 -49 19 minecraft:white_concrete
fill 3076 -57 1 3090 -49 17 minecraft:air
fill 3075 -48 0 3091 -48 18 minecraft:white_concrete
fill 3076 -48 1 3090 -48 1 minecraft:glowstone
fill 3076 -48 17 3090 -48 17 minecraft:glowstone
fill 3076 -48 2 3076 -48 16 minecraft:glowstone
fill 3090 -48 2 3090 -48 16 minecraft:glowstone
fill 3077 -48 2 3089 -48 2 minecraft:glowstone
fill 3077 -48 16 3089 -48 16 minecraft:glowstone
fill 3077 -48 3 3077 -48 15 minecraft:glowstone
fill 3089 -48 3 3089 -48 15 minecraft:glowstone
fill 3078 -48 3 3088 -48 3 minecraft:glowstone
fill 3078 -48 15 3088 -48 15 minecraft:glowstone
fill 3078 -48 4 3078 -48 14 minecraft:glowstone
fill 3088 -48 4 3088 -48 14 minecraft:glowstone
fill 3081 -48 7 3085 -48 11 minecraft:glowstone
fill 3076 -53 1 3090 -53 5 minecraft:glowstone
fill 3076 -52 1 3090 -52 5 minecraft:smooth_stone
fill 3076 -51 6 3090 -51 6 minecraft:oak_fence
fill 3085 -57 1 3089 -57 5 minecraft:orange_concrete
fill 3083 -52 10 3083 -52 10 minecraft:smooth_stone
setblock 3080 -51 1 minecraft:furnace
setblock 3084 -51 3 minecraft:furnace
setblock 3077 -51 3 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3084 -51 5 minecraft:chest
setblock 3076 -51 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
