# Scene: truck_medium_06
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2431 -58 0 2453 -58 23 minecraft:white_concrete
fill 2431 -57 0 2453 -52 23 minecraft:white_concrete
fill 2430 -57 0 2430 -52 23 minecraft:white_concrete
fill 2454 -57 0 2454 -52 23 minecraft:white_concrete
fill 2430 -57 -1 2454 -52 -1 minecraft:white_concrete
fill 2430 -57 24 2454 -52 24 minecraft:white_concrete
fill 2432 -57 1 2452 -52 22 minecraft:air
fill 2431 -51 0 2453 -51 23 minecraft:white_concrete
fill 2432 -51 1 2452 -51 1 minecraft:glowstone
fill 2432 -51 22 2452 -51 22 minecraft:glowstone
fill 2432 -51 2 2432 -51 21 minecraft:glowstone
fill 2452 -51 2 2452 -51 21 minecraft:glowstone
fill 2433 -51 2 2451 -51 2 minecraft:glowstone
fill 2433 -51 21 2451 -51 21 minecraft:glowstone
fill 2433 -51 3 2433 -51 20 minecraft:glowstone
fill 2451 -51 3 2451 -51 20 minecraft:glowstone
fill 2434 -51 3 2450 -51 3 minecraft:glowstone
fill 2434 -51 20 2450 -51 20 minecraft:glowstone
fill 2434 -51 4 2434 -51 19 minecraft:glowstone
fill 2450 -51 4 2450 -51 19 minecraft:glowstone
fill 2440 -51 9 2444 -51 13 minecraft:glowstone
fill 2441 -58 11 2443 -58 13 minecraft:cyan_concrete
setblock 2433 -57 7 minecraft:bookshelf
setblock 2433 -57 6 minecraft:stone_slab[type=bottom]
setblock 2433 -57 17 minecraft:crafting_table
setblock 2451 -57 9 minecraft:chest
setblock 2433 -57 2 minecraft:chest
setblock 2433 -57 8 minecraft:bookshelf
setblock 2433 -57 20 minecraft:bookshelf
setblock 2451 -57 18 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2451 -57 20 minecraft:stone_slab[type=bottom]
setblock 2433 -57 4 minecraft:chest
setblock 2451 -57 16 minecraft:furnace
