# Scene: tier_path_medium_12
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 12 of 15 with 3-5 decorations.
fill 1681 -58 0 1701 -58 30 minecraft:white_concrete
fill 1681 -57 0 1701 -52 30 minecraft:white_concrete
fill 1680 -57 0 1680 -52 30 minecraft:white_concrete
fill 1702 -57 0 1702 -52 30 minecraft:white_concrete
fill 1680 -57 -1 1702 -52 -1 minecraft:white_concrete
fill 1680 -57 31 1702 -52 31 minecraft:white_concrete
fill 1682 -57 1 1700 -52 29 minecraft:air
fill 1681 -51 0 1701 -51 30 minecraft:white_concrete
fill 1682 -51 1 1700 -51 1 minecraft:glowstone
fill 1682 -51 29 1700 -51 29 minecraft:glowstone
fill 1682 -51 2 1682 -51 28 minecraft:glowstone
fill 1700 -51 2 1700 -51 28 minecraft:glowstone
fill 1683 -51 2 1699 -51 2 minecraft:glowstone
fill 1683 -51 28 1699 -51 28 minecraft:glowstone
fill 1683 -51 3 1683 -51 27 minecraft:glowstone
fill 1699 -51 3 1699 -51 27 minecraft:glowstone
fill 1684 -51 3 1698 -51 3 minecraft:glowstone
fill 1684 -51 27 1698 -51 27 minecraft:glowstone
fill 1684 -51 4 1684 -51 26 minecraft:glowstone
fill 1698 -51 4 1698 -51 26 minecraft:glowstone
fill 1689 -51 13 1693 -51 17 minecraft:glowstone
fill 1681 -61 0 1701 -58 30 minecraft:white_concrete
fill 1681 -61 0 1701 -58 12 minecraft:white_concrete
fill 1681 -61 18 1701 -58 30 minecraft:white_concrete
fill 1682 -61 13 1700 -58 17 minecraft:air
fill 1681 -61 0 1701 -61 30 minecraft:black_concrete
fill 1690 -58 13 1692 -58 17 minecraft:air
fill 1690 -57 19 1692 -57 19 minecraft:gold_block
setblock 1690 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1690 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1690 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1691 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1691 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1691 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1692 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1692 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1692 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1692 -57 2 minecraft:chest
setblock 1687 -57 2 minecraft:chest
setblock 1694 -57 2 minecraft:chest
setblock 1699 -57 10 minecraft:stone_slab[type=bottom]
setblock 1699 -57 7 minecraft:stone_slab[type=bottom]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_12/place_command_blocks
