# Scene: tier_path_hard_15
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 15 of 15 with 3-5 decorations.
fill 2221 -58 0 2241 -58 31 minecraft:white_concrete
fill 2221 -57 0 2241 -52 31 minecraft:white_concrete
fill 2220 -57 0 2220 -52 31 minecraft:white_concrete
fill 2242 -57 0 2242 -52 31 minecraft:white_concrete
fill 2220 -57 -1 2242 -52 -1 minecraft:white_concrete
fill 2220 -57 32 2242 -52 32 minecraft:white_concrete
fill 2222 -57 1 2240 -52 30 minecraft:air
fill 2221 -51 0 2241 -51 31 minecraft:white_concrete
fill 2222 -51 1 2240 -51 1 minecraft:glowstone
fill 2222 -51 30 2240 -51 30 minecraft:glowstone
fill 2222 -51 2 2222 -51 29 minecraft:glowstone
fill 2240 -51 2 2240 -51 29 minecraft:glowstone
fill 2223 -51 2 2239 -51 2 minecraft:glowstone
fill 2223 -51 29 2239 -51 29 minecraft:glowstone
fill 2223 -51 3 2223 -51 28 minecraft:glowstone
fill 2239 -51 3 2239 -51 28 minecraft:glowstone
fill 2224 -51 3 2238 -51 3 minecraft:glowstone
fill 2224 -51 28 2238 -51 28 minecraft:glowstone
fill 2224 -51 4 2224 -51 27 minecraft:glowstone
fill 2238 -51 4 2238 -51 27 minecraft:glowstone
fill 2229 -51 13 2233 -51 17 minecraft:glowstone
fill 2221 -61 0 2241 -58 31 minecraft:white_concrete
fill 2221 -61 0 2241 -58 12 minecraft:white_concrete
fill 2221 -61 19 2241 -58 31 minecraft:white_concrete
fill 2222 -61 13 2240 -58 18 minecraft:air
fill 2221 -61 0 2241 -61 31 minecraft:black_concrete
fill 2230 -58 13 2232 -58 18 minecraft:air
fill 2230 -57 20 2232 -57 20 minecraft:gold_block
setblock 2230 -57 8 minecraft:birch_pressure_plate
setblock 2230 -57 9 minecraft:birch_pressure_plate
setblock 2230 -57 10 minecraft:birch_pressure_plate
setblock 2231 -57 8 minecraft:birch_pressure_plate
setblock 2231 -57 9 minecraft:birch_pressure_plate
setblock 2231 -57 10 minecraft:birch_pressure_plate
setblock 2232 -57 8 minecraft:birch_pressure_plate
setblock 2232 -57 9 minecraft:birch_pressure_plate
setblock 2232 -57 10 minecraft:birch_pressure_plate
setblock 2233 -57 2 minecraft:chest
setblock 2235 -57 2 minecraft:furnace
setblock 2223 -57 3 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2238 -57 2 minecraft:furnace
setblock 2239 -57 6 minecraft:furnace

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_15/place_command_blocks
