# Scene: truck_medium_03
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2336 -58 0 2359 -58 22 minecraft:white_concrete
fill 2336 -57 0 2359 -52 22 minecraft:white_concrete
fill 2335 -57 0 2335 -52 22 minecraft:white_concrete
fill 2360 -57 0 2360 -52 22 minecraft:white_concrete
fill 2335 -57 -1 2360 -52 -1 minecraft:white_concrete
fill 2335 -57 23 2360 -52 23 minecraft:white_concrete
fill 2337 -57 1 2358 -52 21 minecraft:air
fill 2336 -51 0 2359 -51 22 minecraft:white_concrete
fill 2337 -51 1 2358 -51 1 minecraft:glowstone
fill 2337 -51 21 2358 -51 21 minecraft:glowstone
fill 2337 -51 2 2337 -51 20 minecraft:glowstone
fill 2358 -51 2 2358 -51 20 minecraft:glowstone
fill 2338 -51 2 2357 -51 2 minecraft:glowstone
fill 2338 -51 20 2357 -51 20 minecraft:glowstone
fill 2338 -51 3 2338 -51 19 minecraft:glowstone
fill 2357 -51 3 2357 -51 19 minecraft:glowstone
fill 2339 -51 3 2356 -51 3 minecraft:glowstone
fill 2339 -51 19 2356 -51 19 minecraft:glowstone
fill 2339 -51 4 2339 -51 18 minecraft:glowstone
fill 2356 -51 4 2356 -51 18 minecraft:glowstone
fill 2345 -51 9 2349 -51 13 minecraft:glowstone
fill 2347 -58 10 2349 -58 12 minecraft:yellow_concrete
setblock 2357 -57 8 minecraft:bookshelf
setblock 2338 -57 12 minecraft:bookshelf
setblock 2357 -57 20 minecraft:chest
setblock 2338 -57 4 minecraft:stone_slab[type=bottom]
setblock 2338 -57 10 minecraft:furnace
setblock 2338 -57 18 minecraft:stone_slab[type=bottom]
setblock 2338 -57 7 minecraft:crafting_table
setblock 2338 -57 5 minecraft:chest
setblock 2338 -57 15 minecraft:crafting_table
setblock 2357 -57 17 minecraft:stone_slab[type=bottom]
setblock 2357 -57 10 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2357 -57 6 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
