# Scene: tier_path_medium_10
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 10 of 15 with 3-5 decorations.
fill 1620 -58 0 1641 -58 30 minecraft:white_concrete
fill 1620 -57 0 1641 -52 30 minecraft:white_concrete
fill 1619 -57 0 1619 -52 30 minecraft:white_concrete
fill 1642 -57 0 1642 -52 30 minecraft:white_concrete
fill 1619 -57 -1 1642 -52 -1 minecraft:white_concrete
fill 1619 -57 31 1642 -52 31 minecraft:white_concrete
fill 1621 -57 1 1640 -52 29 minecraft:air
fill 1620 -51 0 1641 -51 30 minecraft:white_concrete
fill 1621 -51 1 1640 -51 1 minecraft:glowstone
fill 1621 -51 29 1640 -51 29 minecraft:glowstone
fill 1621 -51 2 1621 -51 28 minecraft:glowstone
fill 1640 -51 2 1640 -51 28 minecraft:glowstone
fill 1622 -51 2 1639 -51 2 minecraft:glowstone
fill 1622 -51 28 1639 -51 28 minecraft:glowstone
fill 1622 -51 3 1622 -51 27 minecraft:glowstone
fill 1639 -51 3 1639 -51 27 minecraft:glowstone
fill 1623 -51 3 1638 -51 3 minecraft:glowstone
fill 1623 -51 27 1638 -51 27 minecraft:glowstone
fill 1623 -51 4 1623 -51 26 minecraft:glowstone
fill 1638 -51 4 1638 -51 26 minecraft:glowstone
fill 1628 -51 13 1632 -51 17 minecraft:glowstone
fill 1620 -61 0 1641 -58 30 minecraft:white_concrete
fill 1620 -61 0 1641 -58 12 minecraft:white_concrete
fill 1620 -61 18 1641 -58 30 minecraft:white_concrete
fill 1621 -61 13 1640 -58 17 minecraft:air
fill 1620 -61 0 1641 -61 30 minecraft:black_concrete
fill 1629 -58 13 1631 -58 17 minecraft:air
fill 1629 -57 19 1631 -57 19 minecraft:gold_block
setblock 1630 -57 8 minecraft:cherry_pressure_plate
setblock 1630 -57 9 minecraft:cherry_pressure_plate
setblock 1630 -57 10 minecraft:cherry_pressure_plate
setblock 1631 -57 8 minecraft:cherry_pressure_plate
setblock 1631 -57 9 minecraft:cherry_pressure_plate
setblock 1631 -57 10 minecraft:cherry_pressure_plate
setblock 1632 -57 8 minecraft:cherry_pressure_plate
setblock 1632 -57 9 minecraft:cherry_pressure_plate
setblock 1632 -57 10 minecraft:cherry_pressure_plate
setblock 1622 -57 11 minecraft:crafting_table
setblock 1631 -57 2 minecraft:furnace
setblock 1622 -57 3 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_10/place_command_blocks
