# Scene: maze_medium_05
# Auto-generated by multiagent/scene/generate_scenes.py
fill 4389 -58 0 4411 -58 22 minecraft:white_concrete
fill 4389 -57 0 4411 -40 22 minecraft:white_concrete
fill 4388 -57 0 4388 -40 22 minecraft:white_concrete
fill 4412 -57 0 4412 -40 22 minecraft:white_concrete
fill 4388 -57 -1 4412 -40 -1 minecraft:white_concrete
fill 4388 -57 23 4412 -40 23 minecraft:white_concrete
fill 4390 -57 1 4410 -40 21 minecraft:air
fill 4389 -39 0 4411 -39 22 minecraft:white_concrete
fill 4390 -39 1 4410 -39 1 minecraft:glowstone
fill 4390 -39 21 4410 -39 21 minecraft:glowstone
fill 4390 -39 2 4390 -39 20 minecraft:glowstone
fill 4410 -39 2 4410 -39 20 minecraft:glowstone
fill 4391 -39 2 4409 -39 2 minecraft:glowstone
fill 4391 -39 20 4409 -39 20 minecraft:glowstone
fill 4391 -39 3 4391 -39 19 minecraft:glowstone
fill 4409 -39 3 4409 -39 19 minecraft:glowstone
fill 4392 -39 3 4408 -39 3 minecraft:glowstone
fill 4392 -39 19 4408 -39 19 minecraft:glowstone
fill 4392 -39 4 4392 -39 18 minecraft:glowstone
fill 4408 -39 4 4408 -39 18 minecraft:glowstone
fill 4398 -39 9 4402 -39 13 minecraft:glowstone
fill 4389 -51 0 4411 -51 0 minecraft:glowstone
fill 4389 -51 22 4411 -51 22 minecraft:glowstone
fill 4389 -51 1 4389 -51 21 minecraft:glowstone
fill 4411 -51 1 4411 -51 21 minecraft:glowstone
fill 4393 -57 4 4407 -55 18 minecraft:light_gray_concrete
fill 4393 -57 4 4407 -57 18 minecraft:glowstone
fill 4394 -57 7 4394 -55 7 minecraft:air
fill 4394 -57 8 4394 -55 8 minecraft:air
fill 4394 -57 9 4394 -55 9 minecraft:air
fill 4395 -57 9 4395 -55 9 minecraft:air
fill 4396 -57 9 4396 -55 9 minecraft:air
fill 4397 -57 9 4397 -55 9 minecraft:air
fill 4398 -57 9 4398 -55 9 minecraft:air
fill 4398 -57 10 4398 -55 10 minecraft:air
fill 4399 -57 9 4399 -55 9 minecraft:air
fill 4399 -57 10 4399 -55 10 minecraft:air
fill 4400 -57 9 4400 -55 9 minecraft:air
fill 4400 -57 10 4400 -55 10 minecraft:air
fill 4401 -57 9 4401 -55 9 minecraft:air
fill 4401 -57 10 4401 -55 10 minecraft:air
fill 4402 -57 9 4402 -55 9 minecraft:air
fill 4402 -57 10 4402 -55 10 minecraft:air
fill 4402 -57 11 4402 -55 11 minecraft:air
fill 4402 -57 12 4402 -55 12 minecraft:air
fill 4402 -57 13 4402 -55 13 minecraft:air
fill 4402 -57 14 4402 -55 14 minecraft:air
fill 4403 -57 9 4403 -55 9 minecraft:air
fill 4403 -57 10 4403 -55 10 minecraft:air
fill 4403 -57 11 4403 -55 11 minecraft:air
fill 4403 -57 12 4403 -55 12 minecraft:air
fill 4403 -57 13 4403 -55 13 minecraft:air
fill 4403 -57 14 4403 -55 14 minecraft:air
fill 4402 -58 13 4403 -58 14 minecraft:white_concrete
fill 4398 -58 9 4399 -58 10 minecraft:green_concrete
setblock 4394 -57 8 minecraft:furnace
setblock 4396 -57 9 minecraft:stone_slab[type=bottom]
setblock 4400 -57 9 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 4402 -57 12 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
