# Scene: picture_hard_01
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3550 -58 0 3566 -58 18 minecraft:white_concrete
fill 3550 -57 0 3566 -49 18 minecraft:white_concrete
fill 3549 -57 0 3549 -49 18 minecraft:white_concrete
fill 3567 -57 0 3567 -49 18 minecraft:white_concrete
fill 3549 -57 -1 3567 -49 -1 minecraft:white_concrete
fill 3549 -57 19 3567 -49 19 minecraft:white_concrete
fill 3551 -57 1 3565 -49 17 minecraft:air
fill 3550 -48 0 3566 -48 18 minecraft:white_concrete
fill 3551 -48 1 3565 -48 1 minecraft:glowstone
fill 3551 -48 17 3565 -48 17 minecraft:glowstone
fill 3551 -48 2 3551 -48 16 minecraft:glowstone
fill 3565 -48 2 3565 -48 16 minecraft:glowstone
fill 3552 -48 2 3564 -48 2 minecraft:glowstone
fill 3552 -48 16 3564 -48 16 minecraft:glowstone
fill 3552 -48 3 3552 -48 15 minecraft:glowstone
fill 3564 -48 3 3564 -48 15 minecraft:glowstone
fill 3553 -48 3 3563 -48 3 minecraft:glowstone
fill 3553 -48 15 3563 -48 15 minecraft:glowstone
fill 3553 -48 4 3553 -48 14 minecraft:glowstone
fill 3563 -48 4 3563 -48 14 minecraft:glowstone
fill 3556 -48 7 3560 -48 11 minecraft:glowstone
fill 3551 -53 1 3565 -53 5 minecraft:glowstone
fill 3551 -52 1 3565 -52 5 minecraft:smooth_stone
fill 3551 -51 6 3565 -51 6 minecraft:oak_fence
fill 3554 -57 2 3556 -57 4 minecraft:red_concrete
fill 3558 -52 10 3558 -52 10 minecraft:smooth_stone
setblock 3555 -51 5 minecraft:stone_slab[type=bottom]
setblock 3565 -51 2 minecraft:furnace
setblock 3561 -51 4 minecraft:chest
setblock 3557 -51 5 minecraft:stone_slab[type=bottom]
setblock 3560 -51 5 minecraft:stone_slab[type=bottom]
setblock 3551 -51 1 minecraft:crafting_table
