# Scene: picture_medium_05
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3275 -58 0 3291 -58 18 minecraft:white_concrete
fill 3275 -57 0 3291 -49 18 minecraft:white_concrete
fill 3274 -57 0 3274 -49 18 minecraft:white_concrete
fill 3292 -57 0 3292 -49 18 minecraft:white_concrete
fill 3274 -57 -1 3292 -49 -1 minecraft:white_concrete
fill 3274 -57 19 3292 -49 19 minecraft:white_concrete
fill 3276 -57 1 3290 -49 17 minecraft:air
fill 3275 -48 0 3291 -48 18 minecraft:white_concrete
fill 3276 -48 1 3290 -48 1 minecraft:glowstone
fill 3276 -48 17 3290 -48 17 minecraft:glowstone
fill 3276 -48 2 3276 -48 16 minecraft:glowstone
fill 3290 -48 2 3290 -48 16 minecraft:glowstone
fill 3277 -48 2 3289 -48 2 minecraft:glowstone
fill 3277 -48 16 3289 -48 16 minecraft:glowstone
fill 3277 -48 3 3277 -48 15 minecraft:glowstone
fill 3289 -48 3 3289 -48 15 minecraft:glowstone
fill 3278 -48 3 3288 -48 3 minecraft:glowstone
fill 3278 -48 15 3288 -48 15 minecraft:glowstone
fill 3278 -48 4 3278 -48 14 minecraft:glowstone
fill 3288 -48 4 3288 -48 14 minecraft:glowstone
fill 3281 -48 7 3285 -48 11 minecraft:glowstone
fill 3276 -53 1 3290 -53 5 minecraft:glowstone
fill 3276 -52 1 3290 -52 5 minecraft:smooth_stone
fill 3276 -51 6 3290 -51 6 minecraft:oak_fence
fill 3279 -57 2 3282 -57 5 minecraft:green_concrete
fill 3283 -52 10 3283 -52 10 minecraft:smooth_stone
setblock 3283 -51 4 minecraft:crafting_table
setblock 3286 -51 4 minecraft:bookshelf
setblock 3277 -51 2 minecraft:stone_slab[type=bottom]
setblock 3276 -51 3 minecraft:crafting_table
setblock 3288 -51 5 minecraft:crafting_table
setblock 3289 -51 2 minecraft:furnace
setblock 3288 -51 4 minecraft:bookshelf
