# Scene: tier_elevator_hard_01
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 1 of 15 with 3-5 decorations.
fill 900 -59 0 921 -59 23 minecraft:white_concrete
fill 900 -58 0 921 -53 23 minecraft:white_concrete
fill 899 -58 0 899 -53 23 minecraft:white_concrete
fill 922 -58 0 922 -53 23 minecraft:white_concrete
fill 899 -58 -1 922 -53 -1 minecraft:white_concrete
fill 899 -58 24 922 -53 24 minecraft:white_concrete
fill 901 -58 1 920 -53 22 minecraft:air
fill 900 -52 0 921 -52 23 minecraft:white_concrete
fill 901 -52 1 920 -52 1 minecraft:glowstone
fill 901 -52 22 920 -52 22 minecraft:glowstone
fill 901 -52 2 901 -52 21 minecraft:glowstone
fill 920 -52 2 920 -52 21 minecraft:glowstone
fill 902 -52 2 919 -52 2 minecraft:glowstone
fill 902 -52 21 919 -52 21 minecraft:glowstone
fill 902 -52 3 902 -52 20 minecraft:glowstone
fill 919 -52 3 919 -52 20 minecraft:glowstone
fill 903 -52 3 918 -52 3 minecraft:glowstone
fill 903 -52 20 918 -52 20 minecraft:glowstone
fill 903 -52 4 903 -52 19 minecraft:glowstone
fill 918 -52 4 918 -52 19 minecraft:glowstone
fill 908 -52 9 912 -52 13 minecraft:glowstone
fill 901 -58 12 920 -53 12 minecraft:white_concrete
fill 910 -58 12 911 -56 12 minecraft:light_gray_concrete
setblock 910 -58 6 minecraft:stone_pressure_plate
setblock 910 -58 7 minecraft:stone_pressure_plate
setblock 910 -58 8 minecraft:stone_pressure_plate
setblock 911 -58 6 minecraft:stone_pressure_plate
setblock 911 -58 7 minecraft:stone_pressure_plate
setblock 911 -58 8 minecraft:stone_pressure_plate
setblock 912 -58 6 minecraft:stone_pressure_plate
setblock 912 -58 7 minecraft:stone_pressure_plate
setblock 912 -58 8 minecraft:stone_pressure_plate
setblock 917 -58 2 minecraft:crafting_table
setblock 910 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 902 -58 9 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 919 -58 7 minecraft:stone_slab[type=bottom]
setblock 918 -58 2 minecraft:bookshelf

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_01/place_command_blocks
