# Scene: tier_path_medium_02
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 2 of 15 with 3-5 decorations.
fill 1380 -58 0 1402 -58 30 minecraft:white_concrete
fill 1380 -57 0 1402 -52 30 minecraft:white_concrete
fill 1379 -57 0 1379 -52 30 minecraft:white_concrete
fill 1403 -57 0 1403 -52 30 minecraft:white_concrete
fill 1379 -57 -1 1403 -52 -1 minecraft:white_concrete
fill 1379 -57 31 1403 -52 31 minecraft:white_concrete
fill 1381 -57 1 1401 -52 29 minecraft:air
fill 1380 -51 0 1402 -51 30 minecraft:white_concrete
fill 1381 -51 1 1401 -51 1 minecraft:glowstone
fill 1381 -51 29 1401 -51 29 minecraft:glowstone
fill 1381 -51 2 1381 -51 28 minecraft:glowstone
fill 1401 -51 2 1401 -51 28 minecraft:glowstone
fill 1382 -51 2 1400 -51 2 minecraft:glowstone
fill 1382 -51 28 1400 -51 28 minecraft:glowstone
fill 1382 -51 3 1382 -51 27 minecraft:glowstone
fill 1400 -51 3 1400 -51 27 minecraft:glowstone
fill 1383 -51 3 1399 -51 3 minecraft:glowstone
fill 1383 -51 27 1399 -51 27 minecraft:glowstone
fill 1383 -51 4 1383 -51 26 minecraft:glowstone
fill 1399 -51 4 1399 -51 26 minecraft:glowstone
fill 1389 -51 13 1393 -51 17 minecraft:glowstone
fill 1380 -61 0 1402 -58 30 minecraft:white_concrete
fill 1380 -61 0 1402 -58 12 minecraft:white_concrete
fill 1380 -61 18 1402 -58 30 minecraft:white_concrete
fill 1381 -61 13 1401 -58 17 minecraft:air
fill 1380 -61 0 1402 -61 30 minecraft:black_concrete
fill 1390 -58 13 1392 -58 17 minecraft:air
fill 1390 -57 19 1392 -57 19 minecraft:gold_block
setblock 1390 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1390 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1390 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1391 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1391 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1391 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1392 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1392 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1392 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1396 -57 2 minecraft:furnace
setblock 1385 -57 2 minecraft:furnace
setblock 1400 -57 9 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_02/place_command_blocks
