# Scene: tier_path_medium_01
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 1 of 15 with 3-5 decorations.
fill 1350 -58 0 1371 -58 31 minecraft:white_concrete
fill 1350 -57 0 1371 -52 31 minecraft:white_concrete
fill 1349 -57 0 1349 -52 31 minecraft:white_concrete
fill 1372 -57 0 1372 -52 31 minecraft:white_concrete
fill 1349 -57 -1 1372 -52 -1 minecraft:white_concrete
fill 1349 -57 32 1372 -52 32 minecraft:white_concrete
fill 1351 -57 1 1370 -52 30 minecraft:air
fill 1350 -51 0 1371 -51 31 minecraft:white_concrete
fill 1351 -51 1 1370 -51 1 minecraft:glowstone
fill 1351 -51 30 1370 -51 30 minecraft:glowstone
fill 1351 -51 2 1351 -51 29 minecraft:glowstone
fill 1370 -51 2 1370 -51 29 minecraft:glowstone
fill 1352 -51 2 1369 -51 2 minecraft:glowstone
fill 1352 -51 29 1369 -51 29 minecraft:glowstone
fill 1352 -51 3 1352 -51 28 minecraft:glowstone
fill 1369 -51 3 1369 -51 28 minecraft:glowstone
fill 1353 -51 3 1368 -51 3 minecraft:glowstone
fill 1353 -51 28 1368 -51 28 minecraft:glowstone
fill 1353 -51 4 1353 -51 27 minecraft:glowstone
fill 1368 -51 4 1368 -51 27 minecraft:glowstone
fill 1358 -51 13 1362 -51 17 minecraft:glowstone
fill 1350 -61 0 1371 -58 31 minecraft:white_concrete
fill 1350 -61 0 1371 -58 12 minecraft:white_concrete
fill 1350 -61 18 1371 -58 31 minecraft:white_concrete
fill 1351 -61 13 1370 -58 17 minecraft:air
fill 1350 -61 0 1371 -61 31 minecraft:black_concrete
fill 1359 -58 13 1361 -58 17 minecraft:air
fill 1359 -57 19 1361 -57 19 minecraft:gold_block
setblock 1360 -57 8 minecraft:stone_pressure_plate
setblock 1360 -57 9 minecraft:stone_pressure_plate
setblock 1360 -57 10 minecraft:stone_pressure_plate
setblock 1361 -57 8 minecraft:stone_pressure_plate
setblock 1361 -57 9 minecraft:stone_pressure_plate
setblock 1361 -57 10 minecraft:stone_pressure_plate
setblock 1362 -57 8 minecraft:stone_pressure_plate
setblock 1362 -57 9 minecraft:stone_pressure_plate
setblock 1362 -57 10 minecraft:stone_pressure_plate
setblock 1361 -57 2 minecraft:stone_slab[type=bottom]
setblock 1369 -57 10 minecraft:stone_slab[type=bottom]
setblock 1353 -57 2 minecraft:stone_slab[type=bottom]
setblock 1352 -57 9 minecraft:chest

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_01/place_command_blocks
