# Scene: tier_elevator_easy_14
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 14 of 15 with 3-5 decorations.
fill 390 -59 0 412 -59 22 minecraft:white_concrete
fill 390 -58 0 412 -53 22 minecraft:white_concrete
fill 389 -58 0 389 -53 22 minecraft:white_concrete
fill 413 -58 0 413 -53 22 minecraft:white_concrete
fill 389 -58 -1 413 -53 -1 minecraft:white_concrete
fill 389 -58 23 413 -53 23 minecraft:white_concrete
fill 391 -58 1 411 -53 21 minecraft:air
fill 390 -52 0 412 -52 22 minecraft:white_concrete
fill 391 -52 1 411 -52 1 minecraft:glowstone
fill 391 -52 21 411 -52 21 minecraft:glowstone
fill 391 -52 2 391 -52 20 minecraft:glowstone
fill 411 -52 2 411 -52 20 minecraft:glowstone
fill 392 -52 2 410 -52 2 minecraft:glowstone
fill 392 -52 20 410 -52 20 minecraft:glowstone
fill 392 -52 3 392 -52 19 minecraft:glowstone
fill 410 -52 3 410 -52 19 minecraft:glowstone
fill 393 -52 3 409 -52 3 minecraft:glowstone
fill 393 -52 19 409 -52 19 minecraft:glowstone
fill 393 -52 4 393 -52 18 minecraft:glowstone
fill 409 -52 4 409 -52 18 minecraft:glowstone
fill 399 -52 9 403 -52 13 minecraft:glowstone
fill 391 -58 11 411 -53 11 minecraft:white_concrete
fill 401 -58 11 403 -56 11 minecraft:brown_concrete
setblock 401 -58 5 minecraft:mangrove_pressure_plate
setblock 401 -58 6 minecraft:mangrove_pressure_plate
setblock 401 -58 7 minecraft:mangrove_pressure_plate
setblock 401 -58 8 minecraft:mangrove_pressure_plate
setblock 402 -58 5 minecraft:mangrove_pressure_plate
setblock 402 -58 6 minecraft:mangrove_pressure_plate
setblock 402 -58 7 minecraft:mangrove_pressure_plate
setblock 402 -58 8 minecraft:mangrove_pressure_plate
setblock 403 -58 5 minecraft:mangrove_pressure_plate
setblock 403 -58 6 minecraft:mangrove_pressure_plate
setblock 403 -58 7 minecraft:mangrove_pressure_plate
setblock 403 -58 8 minecraft:mangrove_pressure_plate
setblock 404 -58 5 minecraft:mangrove_pressure_plate
setblock 404 -58 6 minecraft:mangrove_pressure_plate
setblock 404 -58 7 minecraft:mangrove_pressure_plate
setblock 404 -58 8 minecraft:mangrove_pressure_plate
setblock 410 -58 5 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 404 -58 2 minecraft:chest
setblock 409 -58 2 minecraft:crafting_table
setblock 392 -58 7 minecraft:bookshelf
setblock 392 -58 2 minecraft:furnace

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_easy_14/place_command_blocks
