# Scene: truck_hard_05
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2872 -58 0 2895 -58 22 minecraft:white_concrete
fill 2872 -57 0 2895 -52 22 minecraft:white_concrete
fill 2871 -57 0 2871 -52 22 minecraft:white_concrete
fill 2896 -57 0 2896 -52 22 minecraft:white_concrete
fill 2871 -57 -1 2896 -52 -1 minecraft:white_concrete
fill 2871 -57 23 2896 -52 23 minecraft:white_concrete
fill 2873 -57 1 2894 -52 21 minecraft:air
fill 2872 -51 0 2895 -51 22 minecraft:white_concrete
fill 2873 -51 1 2894 -51 1 minecraft:glowstone
fill 2873 -51 21 2894 -51 21 minecraft:glowstone
fill 2873 -51 2 2873 -51 20 minecraft:glowstone
fill 2894 -51 2 2894 -51 20 minecraft:glowstone
fill 2874 -51 2 2893 -51 2 minecraft:glowstone
fill 2874 -51 20 2893 -51 20 minecraft:glowstone
fill 2874 -51 3 2874 -51 19 minecraft:glowstone
fill 2893 -51 3 2893 -51 19 minecraft:glowstone
fill 2875 -51 3 2892 -51 3 minecraft:glowstone
fill 2875 -51 19 2892 -51 19 minecraft:glowstone
fill 2875 -51 4 2875 -51 18 minecraft:glowstone
fill 2892 -51 4 2892 -51 18 minecraft:glowstone
fill 2881 -51 9 2885 -51 13 minecraft:glowstone
fill 2884 -58 11 2885 -58 12 minecraft:green_concrete
setblock 2874 -57 17 minecraft:furnace
setblock 2874 -57 7 minecraft:crafting_table
setblock 2893 -57 12 minecraft:furnace
setblock 2893 -57 7 minecraft:furnace
setblock 2874 -57 4 minecraft:crafting_table
setblock 2874 -57 10 minecraft:stone_slab[type=bottom]
setblock 2874 -57 6 minecraft:furnace
setblock 2874 -57 12 minecraft:crafting_table
setblock 2874 -57 15 minecraft:stone_slab[type=bottom]
setblock 2893 -57 4 minecraft:stone_slab[type=bottom]
setblock 2893 -57 15 minecraft:bookshelf
setblock 2874 -57 8 minecraft:stone_slab[type=bottom]
