# Scene: picture_hard_08
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3725 -58 0 3741 -58 18 minecraft:white_concrete
fill 3725 -57 0 3741 -49 18 minecraft:white_concrete
fill 3724 -57 0 3724 -49 18 minecraft:white_concrete
fill 3742 -57 0 3742 -49 18 minecraft:white_concrete
fill 3724 -57 -1 3742 -49 -1 minecraft:white_concrete
fill 3724 -57 19 3742 -49 19 minecraft:white_concrete
fill 3726 -57 1 3740 -49 17 minecraft:air
fill 3725 -48 0 3741 -48 18 minecraft:white_concrete
fill 3726 -48 1 3740 -48 1 minecraft:glowstone
fill 3726 -48 17 3740 -48 17 minecraft:glowstone
fill 3726 -48 2 3726 -48 16 minecraft:glowstone
fill 3740 -48 2 3740 -48 16 minecraft:glowstone
fill 3727 -48 2 3739 -48 2 minecraft:glowstone
fill 3727 -48 16 3739 -48 16 minecraft:glowstone
fill 3727 -48 3 3727 -48 15 minecraft:glowstone
fill 3739 -48 3 3739 -48 15 minecraft:glowstone
fill 3728 -48 3 3738 -48 3 minecraft:glowstone
fill 3728 -48 15 3738 -48 15 minecraft:glowstone
fill 3728 -48 4 3728 -48 14 minecraft:glowstone
fill 3738 -48 4 3738 -48 14 minecraft:glowstone
fill 3731 -48 7 3735 -48 11 minecraft:glowstone
fill 3726 -53 1 3740 -53 5 minecraft:glowstone
fill 3726 -52 1 3740 -52 5 minecraft:smooth_stone
fill 3726 -51 6 3740 -51 6 minecraft:oak_fence
fill 3736 -57 1 3738 -57 3 minecraft:blue_concrete
fill 3733 -52 10 3733 -52 10 minecraft:smooth_stone
setblock 3729 -51 1 minecraft:crafting_table
setblock 3729 -51 4 minecraft:chest
setblock 3732 -51 2 minecraft:furnace
setblock 3740 -51 2 minecraft:furnace
setblock 3734 -51 2 minecraft:bookshelf
