# Scene: tier_elevator_hard_07
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 7 of 15 with 3-5 decorations.
fill 1080 -59 0 1101 -59 23 minecraft:white_concrete
fill 1080 -58 0 1101 -53 23 minecraft:white_concrete
fill 1079 -58 0 1079 -53 23 minecraft:white_concrete
fill 1102 -58 0 1102 -53 23 minecraft:white_concrete
fill 1079 -58 -1 1102 -53 -1 minecraft:white_concrete
fill 1079 -58 24 1102 -53 24 minecraft:white_concrete
fill 1081 -58 1 1100 -53 22 minecraft:air
fill 1080 -52 0 1101 -52 23 minecraft:white_concrete
fill 1081 -52 1 1100 -52 1 minecraft:glowstone
fill 1081 -52 22 1100 -52 22 minecraft:glowstone
fill 1081 -52 2 1081 -52 21 minecraft:glowstone
fill 1100 -52 2 1100 -52 21 minecraft:glowstone
fill 1082 -52 2 1099 -52 2 minecraft:glowstone
fill 1082 -52 21 1099 -52 21 minecraft:glowstone
fill 1082 -52 3 1082 -52 20 minecraft:glowstone
fill 1099 -52 3 1099 -52 20 minecraft:glowstone
fill 1083 -52 3 1098 -52 3 minecraft:glowstone
fill 1083 -52 20 1098 -52 20 minecraft:glowstone
fill 1083 -52 4 1083 -52 19 minecraft:glowstone
fill 1098 -52 4 1098 -52 19 minecraft:glowstone
fill 1088 -52 9 1092 -52 13 minecraft:glowstone
fill 1081 -58 12 1100 -53 12 minecraft:white_concrete
fill 1090 -58 12 1091 -56 12 minecraft:gray_concrete
setblock 1092 -58 6 minecraft:spruce_pressure_plate
setblock 1092 -58 7 minecraft:spruce_pressure_plate
setblock 1092 -58 8 minecraft:spruce_pressure_plate
setblock 1093 -58 6 minecraft:spruce_pressure_plate
setblock 1093 -58 7 minecraft:spruce_pressure_plate
setblock 1093 -58 8 minecraft:spruce_pressure_plate
setblock 1094 -58 6 minecraft:spruce_pressure_plate
setblock 1094 -58 7 minecraft:spruce_pressure_plate
setblock 1094 -58 8 minecraft:spruce_pressure_plate
setblock 1091 -58 2 minecraft:chest
setblock 1099 -58 8 minecraft:bookshelf
setblock 1099 -58 5 minecraft:crafting_table
setblock 1089 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1095 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_07/place_command_blocks
