# Scene: tier_elevator_easy_13
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 13 of 15 with 3-5 decorations.
fill 360 -59 0 381 -59 23 minecraft:white_concrete
fill 360 -58 0 381 -53 23 minecraft:white_concrete
fill 359 -58 0 359 -53 23 minecraft:white_concrete
fill 382 -58 0 382 -53 23 minecraft:white_concrete
fill 359 -58 -1 382 -53 -1 minecraft:white_concrete
fill 359 -58 24 382 -53 24 minecraft:white_concrete
fill 361 -58 1 380 -53 22 minecraft:air
fill 360 -52 0 381 -52 23 minecraft:white_concrete
fill 361 -52 1 380 -52 1 minecraft:glowstone
fill 361 -52 22 380 -52 22 minecraft:glowstone
fill 361 -52 2 361 -52 21 minecraft:glowstone
fill 380 -52 2 380 -52 21 minecraft:glowstone
fill 362 -52 2 379 -52 2 minecraft:glowstone
fill 362 -52 21 379 -52 21 minecraft:glowstone
fill 362 -52 3 362 -52 20 minecraft:glowstone
fill 379 -52 3 379 -52 20 minecraft:glowstone
fill 363 -52 3 378 -52 3 minecraft:glowstone
fill 363 -52 20 378 -52 20 minecraft:glowstone
fill 363 -52 4 363 -52 19 minecraft:glowstone
fill 378 -52 4 378 -52 19 minecraft:glowstone
fill 368 -52 9 372 -52 13 minecraft:glowstone
fill 361 -58 12 380 -53 12 minecraft:white_concrete
fill 370 -58 12 372 -56 12 minecraft:black_concrete
setblock 369 -58 7 minecraft:acacia_pressure_plate
setblock 369 -58 8 minecraft:acacia_pressure_plate
setblock 369 -58 9 minecraft:acacia_pressure_plate
setblock 369 -58 10 minecraft:acacia_pressure_plate
setblock 370 -58 7 minecraft:acacia_pressure_plate
setblock 370 -58 8 minecraft:acacia_pressure_plate
setblock 370 -58 9 minecraft:acacia_pressure_plate
setblock 370 -58 10 minecraft:acacia_pressure_plate
setblock 371 -58 7 minecraft:acacia_pressure_plate
setblock 371 -58 8 minecraft:acacia_pressure_plate
setblock 371 -58 9 minecraft:acacia_pressure_plate
setblock 371 -58 10 minecraft:acacia_pressure_plate
setblock 372 -58 7 minecraft:acacia_pressure_plate
setblock 372 -58 8 minecraft:acacia_pressure_plate
setblock 372 -58 9 minecraft:acacia_pressure_plate
setblock 372 -58 10 minecraft:acacia_pressure_plate
setblock 370 -58 2 minecraft:stone_slab[type=bottom]
setblock 379 -58 4 minecraft:crafting_table
setblock 362 -58 5 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_easy_13/place_command_blocks
