# Scene: maze_medium_08
# Auto-generated by multiagent/scene/generate_scenes.py
fill 4482 -58 0 4504 -58 22 minecraft:white_concrete
fill 4482 -57 0 4504 -40 22 minecraft:white_concrete
fill 4481 -57 0 4481 -40 22 minecraft:white_concrete
fill 4505 -57 0 4505 -40 22 minecraft:white_concrete
fill 4481 -57 -1 4505 -40 -1 minecraft:white_concrete
fill 4481 -57 23 4505 -40 23 minecraft:white_concrete
fill 4483 -57 1 4503 -40 21 minecraft:air
fill 4482 -39 0 4504 -39 22 minecraft:white_concrete
fill 4483 -39 1 4503 -39 1 minecraft:glowstone
fill 4483 -39 21 4503 -39 21 minecraft:glowstone
fill 4483 -39 2 4483 -39 20 minecraft:glowstone
fill 4503 -39 2 4503 -39 20 minecraft:glowstone
fill 4484 -39 2 4502 -39 2 minecraft:glowstone
fill 4484 -39 20 4502 -39 20 minecraft:glowstone
fill 4484 -39 3 4484 -39 19 minecraft:glowstone
fill 4502 -39 3 4502 -39 19 minecraft:glowstone
fill 4485 -39 3 4501 -39 3 minecraft:glowstone
fill 4485 -39 19 4501 -39 19 minecraft:glowstone
fill 4485 -39 4 4485 -39 18 minecraft:glowstone
fill 4501 -39 4 4501 -39 18 minecraft:glowstone
fill 4491 -39 9 4495 -39 13 minecraft:glowstone
fill 4482 -51 0 4504 -51 0 minecraft:glowstone
fill 4482 -51 22 4504 -51 22 minecraft:glowstone
fill 4482 -51 1 4482 -51 21 minecraft:glowstone
fill 4504 -51 1 4504 -51 21 minecraft:glowstone
fill 4486 -57 4 4500 -55 18 minecraft:light_gray_concrete
fill 4486 -57 4 4500 -57 18 minecraft:glowstone
fill 4488 -57 10 4488 -55 10 minecraft:air
fill 4489 -57 10 4489 -55 10 minecraft:air
fill 4490 -57 10 4490 -55 10 minecraft:air
fill 4491 -57 10 4491 -55 10 minecraft:air
fill 4492 -57 10 4492 -55 10 minecraft:air
fill 4493 -57 10 4493 -55 10 minecraft:air
fill 4494 -57 10 4494 -55 10 minecraft:air
fill 4494 -57 11 4494 -55 11 minecraft:air
fill 4494 -57 12 4494 -55 12 minecraft:air
fill 4494 -57 13 4494 -55 13 minecraft:air
fill 4494 -57 14 4494 -55 14 minecraft:air
fill 4494 -57 15 4494 -55 15 minecraft:air
fill 4495 -57 10 4495 -55 10 minecraft:air
fill 4495 -57 11 4495 -55 11 minecraft:air
fill 4495 -57 12 4495 -55 12 minecraft:air
fill 4495 -57 13 4495 -55 13 minecraft:air
fill 4495 -57 14 4495 -55 14 minecraft:air
fill 4495 -57 15 4495 -55 15 minecraft:air
fill 4496 -57 14 4496 -55 14 minecraft:air
fill 4496 -57 15 4496 -55 15 minecraft:air
fill 4497 -57 14 4497 -55 14 minecraft:air
fill 4497 -57 15 4497 -55 15 minecraft:air
fill 4498 -57 14 4498 -55 14 minecraft:air
fill 4498 -57 15 4498 -55 15 minecraft:air
fill 4499 -57 14 4499 -55 14 minecraft:air
fill 4499 -57 15 4499 -55 15 minecraft:air
fill 4498 -58 14 4499 -58 15 minecraft:white_concrete
fill 4494 -58 10 4495 -58 11 minecraft:blue_concrete
setblock 4488 -57 10 minecraft:bookshelf
setblock 4489 -57 10 minecraft:furnace
setblock 4493 -57 10 minecraft:bookshelf
setblock 4497 -57 14 minecraft:stone_slab[type=bottom]
