# Scene: tier_path_hard_12
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 12 of 15 with 3-5 decorations.
fill 2131 -58 0 2151 -58 30 minecraft:white_concrete
fill 2131 -57 0 2151 -52 30 minecraft:white_concrete
fill 2130 -57 0 2130 -52 30 minecraft:white_concrete
fill 2152 -57 0 2152 -52 30 minecraft:white_concrete
fill 2130 -57 -1 2152 -52 -1 minecraft:white_concrete
fill 2130 -57 31 2152 -52 31 minecraft:white_concrete
fill 2132 -57 1 2150 -52 29 minecraft:air
fill 2131 -51 0 2151 -51 30 minecraft:white_concrete
fill 2132 -51 1 2150 -51 1 minecraft:glowstone
fill 2132 -51 29 2150 -51 29 minecraft:glowstone
fill 2132 -51 2 2132 -51 28 minecraft:glowstone
fill 2150 -51 2 2150 -51 28 minecraft:glowstone
fill 2133 -51 2 2149 -51 2 minecraft:glowstone
fill 2133 -51 28 2149 -51 28 minecraft:glowstone
fill 2133 -51 3 2133 -51 27 minecraft:glowstone
fill 2149 -51 3 2149 -51 27 minecraft:glowstone
fill 2134 -51 3 2148 -51 3 minecraft:glowstone
fill 2134 -51 27 2148 -51 27 minecraft:glowstone
fill 2134 -51 4 2134 -51 26 minecraft:glowstone
fill 2148 -51 4 2148 -51 26 minecraft:glowstone
fill 2139 -51 13 2143 -51 17 minecraft:glowstone
fill 2131 -61 0 2151 -58 30 minecraft:white_concrete
fill 2131 -61 0 2151 -58 11 minecraft:white_concrete
fill 2131 -61 18 2151 -58 30 minecraft:white_concrete
fill 2132 -61 12 2150 -58 17 minecraft:air
fill 2131 -61 0 2151 -61 30 minecraft:black_concrete
fill 2140 -58 12 2142 -58 17 minecraft:air
fill 2140 -57 19 2142 -57 19 minecraft:gold_block
setblock 2140 -57 7 minecraft:polished_blackstone_pressure_plate
setblock 2140 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 2140 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 2141 -57 7 minecraft:polished_blackstone_pressure_plate
setblock 2141 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 2141 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 2142 -57 7 minecraft:polished_blackstone_pressure_plate
setblock 2142 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 2142 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 2133 -57 2 minecraft:bookshelf
setblock 2133 -57 7 minecraft:stone_slab[type=bottom]
setblock 2141 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2136 -57 2 minecraft:chest

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_12/place_command_blocks
