# Scene: picture_medium_15
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3525 -58 0 3541 -58 18 minecraft:white_concrete
fill 3525 -57 0 3541 -49 18 minecraft:white_concrete
fill 3524 -57 0 3524 -49 18 minecraft:white_concrete
fill 3542 -57 0 3542 -49 18 minecraft:white_concrete
fill 3524 -57 -1 3542 -49 -1 minecraft:white_concrete
fill 3524 -57 19 3542 -49 19 minecraft:white_concrete
fill 3526 -57 1 3540 -49 17 minecraft:air
fill 3525 -48 0 3541 -48 18 minecraft:white_concrete
fill 3526 -48 1 3540 -48 1 minecraft:glowstone
fill 3526 -48 17 3540 -48 17 minecraft:glowstone
fill 3526 -48 2 3526 -48 16 minecraft:glowstone
fill 3540 -48 2 3540 -48 16 minecraft:glowstone
fill 3527 -48 2 3539 -48 2 minecraft:glowstone
fill 3527 -48 16 3539 -48 16 minecraft:glowstone
fill 3527 -48 3 3527 -48 15 minecraft:glowstone
fill 3539 -48 3 3539 -48 15 minecraft:glowstone
fill 3528 -48 3 3538 -48 3 minecraft:glowstone
fill 3528 -48 15 3538 -48 15 minecraft:glowstone
fill 3528 -48 4 3528 -48 14 minecraft:glowstone
fill 3538 -48 4 3538 -48 14 minecraft:glowstone
fill 3531 -48 7 3535 -48 11 minecraft:glowstone
fill 3526 -53 1 3540 -53 5 minecraft:glowstone
fill 3526 -52 1 3540 -52 5 minecraft:smooth_stone
fill 3526 -51 6 3540 -51 6 minecraft:oak_fence
fill 3527 -57 2 3530 -57 5 minecraft:green_concrete
fill 3533 -52 10 3533 -52 10 minecraft:smooth_stone
setblock 3538 -51 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3536 -51 1 minecraft:bookshelf
setblock 3540 -51 5 minecraft:stone_slab[type=bottom]
setblock 3536 -51 3 minecraft:bookshelf
setblock 3526 -51 3 minecraft:chest
setblock 3533 -51 5 minecraft:chest
