# Scene: truck_easy_03
# Auto-generated by multiagent/scene/generate_scenes.py
fill 1863 -58 0 1886 -58 22 minecraft:white_concrete
fill 1863 -57 0 1886 -52 22 minecraft:white_concrete
fill 1862 -57 0 1862 -52 22 minecraft:white_concrete
fill 1887 -57 0 1887 -52 22 minecraft:white_concrete
fill 1862 -57 -1 1887 -52 -1 minecraft:white_concrete
fill 1862 -57 23 1887 -52 23 minecraft:white_concrete
fill 1864 -57 1 1885 -52 21 minecraft:air
fill 1863 -51 0 1886 -51 22 minecraft:white_concrete
fill 1864 -51 1 1885 -51 1 minecraft:glowstone
fill 1864 -51 21 1885 -51 21 minecraft:glowstone
fill 1864 -51 2 1864 -51 20 minecraft:glowstone
fill 1885 -51 2 1885 -51 20 minecraft:glowstone
fill 1865 -51 2 1884 -51 2 minecraft:glowstone
fill 1865 -51 20 1884 -51 20 minecraft:glowstone
fill 1865 -51 3 1865 -51 19 minecraft:glowstone
fill 1884 -51 3 1884 -51 19 minecraft:glowstone
fill 1866 -51 3 1883 -51 3 minecraft:glowstone
fill 1866 -51 19 1883 -51 19 minecraft:glowstone
fill 1866 -51 4 1866 -51 18 minecraft:glowstone
fill 1883 -51 4 1883 -51 18 minecraft:glowstone
fill 1872 -51 9 1876 -51 13 minecraft:glowstone
fill 1874 -58 10 1877 -58 13 minecraft:yellow_concrete
setblock 1865 -57 4 minecraft:stone_slab[type=bottom]
setblock 1865 -57 14 minecraft:furnace
setblock 1884 -57 2 minecraft:furnace
setblock 1884 -57 4 minecraft:bookshelf
setblock 1865 -57 11 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1884 -57 14 minecraft:bookshelf
setblock 1884 -57 3 minecraft:furnace
setblock 1865 -57 19 minecraft:chest
setblock 1865 -57 9 minecraft:crafting_table
setblock 1865 -57 12 minecraft:stone_slab[type=bottom]
setblock 1884 -57 6 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1884 -57 11 minecraft:furnace
setblock 1865 -57 7 minecraft:bookshelf
setblock 1865 -57 8 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
