# Scene: tier_elevator_medium_02
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 2 of 15 with 3-5 decorations.
fill 480 -59 0 502 -59 22 minecraft:white_concrete
fill 480 -58 0 502 -53 22 minecraft:white_concrete
fill 479 -58 0 479 -53 22 minecraft:white_concrete
fill 503 -58 0 503 -53 22 minecraft:white_concrete
fill 479 -58 -1 503 -53 -1 minecraft:white_concrete
fill 479 -58 23 503 -53 23 minecraft:white_concrete
fill 481 -58 1 501 -53 21 minecraft:air
fill 480 -52 0 502 -52 22 minecraft:white_concrete
fill 481 -52 1 501 -52 1 minecraft:glowstone
fill 481 -52 21 501 -52 21 minecraft:glowstone
fill 481 -52 2 481 -52 20 minecraft:glowstone
fill 501 -52 2 501 -52 20 minecraft:glowstone
fill 482 -52 2 500 -52 2 minecraft:glowstone
fill 482 -52 20 500 -52 20 minecraft:glowstone
fill 482 -52 3 482 -52 19 minecraft:glowstone
fill 500 -52 3 500 -52 19 minecraft:glowstone
fill 483 -52 3 499 -52 3 minecraft:glowstone
fill 483 -52 19 499 -52 19 minecraft:glowstone
fill 483 -52 4 483 -52 18 minecraft:glowstone
fill 499 -52 4 499 -52 18 minecraft:glowstone
fill 489 -52 9 493 -52 13 minecraft:glowstone
fill 481 -58 11 501 -53 11 minecraft:white_concrete
fill 491 -58 11 492 -56 11 minecraft:gray_concrete
setblock 492 -58 5 minecraft:oak_pressure_plate
setblock 492 -58 6 minecraft:oak_pressure_plate
setblock 492 -58 7 minecraft:oak_pressure_plate
setblock 493 -58 5 minecraft:oak_pressure_plate
setblock 493 -58 6 minecraft:oak_pressure_plate
setblock 493 -58 7 minecraft:oak_pressure_plate
setblock 494 -58 5 minecraft:oak_pressure_plate
setblock 494 -58 6 minecraft:oak_pressure_plate
setblock 494 -58 7 minecraft:oak_pressure_plate
setblock 500 -58 9 minecraft:bookshelf
setblock 484 -58 2 minecraft:bookshelf
setblock 493 -58 2 minecraft:furnace
setblock 482 -58 5 minecraft:furnace

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_02/place_command_blocks
