# Scene: picture_hard_03
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3600 -58 0 3616 -58 18 minecraft:white_concrete
fill 3600 -57 0 3616 -49 18 minecraft:white_concrete
fill 3599 -57 0 3599 -49 18 minecraft:white_concrete
fill 3617 -57 0 3617 -49 18 minecraft:white_concrete
fill 3599 -57 -1 3617 -49 -1 minecraft:white_concrete
fill 3599 -57 19 3617 -49 19 minecraft:white_concrete
fill 3601 -57 1 3615 -49 17 minecraft:air
fill 3600 -48 0 3616 -48 18 minecraft:white_concrete
fill 3601 -48 1 3615 -48 1 minecraft:glowstone
fill 3601 -48 17 3615 -48 17 minecraft:glowstone
fill 3601 -48 2 3601 -48 16 minecraft:glowstone
fill 3615 -48 2 3615 -48 16 minecraft:glowstone
fill 3602 -48 2 3614 -48 2 minecraft:glowstone
fill 3602 -48 16 3614 -48 16 minecraft:glowstone
fill 3602 -48 3 3602 -48 15 minecraft:glowstone
fill 3614 -48 3 3614 -48 15 minecraft:glowstone
fill 3603 -48 3 3613 -48 3 minecraft:glowstone
fill 3603 -48 15 3613 -48 15 minecraft:glowstone
fill 3603 -48 4 3603 -48 14 minecraft:glowstone
fill 3613 -48 4 3613 -48 14 minecraft:glowstone
fill 3606 -48 7 3610 -48 11 minecraft:glowstone
fill 3601 -53 1 3615 -53 5 minecraft:glowstone
fill 3601 -52 1 3615 -52 5 minecraft:smooth_stone
fill 3601 -51 6 3615 -51 6 minecraft:oak_fence
fill 3602 -57 2 3604 -57 4 minecraft:yellow_concrete
fill 3608 -52 10 3608 -52 10 minecraft:smooth_stone
setblock 3613 -51 1 minecraft:furnace
setblock 3611 -51 4 minecraft:furnace
setblock 3607 -51 4 minecraft:bookshelf
