# Scene: tier_elevator_hard_03
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 3 of 15 with 3-5 decorations.
fill 961 -59 0 981 -59 23 minecraft:white_concrete
fill 961 -58 0 981 -53 23 minecraft:white_concrete
fill 960 -58 0 960 -53 23 minecraft:white_concrete
fill 982 -58 0 982 -53 23 minecraft:white_concrete
fill 960 -58 -1 982 -53 -1 minecraft:white_concrete
fill 960 -58 24 982 -53 24 minecraft:white_concrete
fill 962 -58 1 980 -53 22 minecraft:air
fill 961 -52 0 981 -52 23 minecraft:white_concrete
fill 962 -52 1 980 -52 1 minecraft:glowstone
fill 962 -52 22 980 -52 22 minecraft:glowstone
fill 962 -52 2 962 -52 21 minecraft:glowstone
fill 980 -52 2 980 -52 21 minecraft:glowstone
fill 963 -52 2 979 -52 2 minecraft:glowstone
fill 963 -52 21 979 -52 21 minecraft:glowstone
fill 963 -52 3 963 -52 20 minecraft:glowstone
fill 979 -52 3 979 -52 20 minecraft:glowstone
fill 964 -52 3 978 -52 3 minecraft:glowstone
fill 964 -52 20 978 -52 20 minecraft:glowstone
fill 964 -52 4 964 -52 19 minecraft:glowstone
fill 978 -52 4 978 -52 19 minecraft:glowstone
fill 969 -52 9 973 -52 13 minecraft:glowstone
fill 962 -58 12 980 -53 12 minecraft:white_concrete
fill 969 -58 12 970 -56 12 minecraft:black_concrete
setblock 969 -58 6 minecraft:birch_pressure_plate
setblock 969 -58 7 minecraft:birch_pressure_plate
setblock 969 -58 8 minecraft:birch_pressure_plate
setblock 970 -58 6 minecraft:birch_pressure_plate
setblock 970 -58 7 minecraft:birch_pressure_plate
setblock 970 -58 8 minecraft:birch_pressure_plate
setblock 971 -58 6 minecraft:birch_pressure_plate
setblock 971 -58 7 minecraft:birch_pressure_plate
setblock 971 -58 8 minecraft:birch_pressure_plate
setblock 979 -58 6 minecraft:chest
setblock 979 -58 3 minecraft:bookshelf
setblock 963 -58 4 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_03/place_command_blocks
