# Scene: maze_medium_14
# Auto-generated by multiagent/scene/generate_scenes.py
fill 4668 -58 0 4690 -58 22 minecraft:white_concrete
fill 4668 -57 0 4690 -40 22 minecraft:white_concrete
fill 4667 -57 0 4667 -40 22 minecraft:white_concrete
fill 4691 -57 0 4691 -40 22 minecraft:white_concrete
fill 4667 -57 -1 4691 -40 -1 minecraft:white_concrete
fill 4667 -57 23 4691 -40 23 minecraft:white_concrete
fill 4669 -57 1 4689 -40 21 minecraft:air
fill 4668 -39 0 4690 -39 22 minecraft:white_concrete
fill 4669 -39 1 4689 -39 1 minecraft:glowstone
fill 4669 -39 21 4689 -39 21 minecraft:glowstone
fill 4669 -39 2 4669 -39 20 minecraft:glowstone
fill 4689 -39 2 4689 -39 20 minecraft:glowstone
fill 4670 -39 2 4688 -39 2 minecraft:glowstone
fill 4670 -39 20 4688 -39 20 minecraft:glowstone
fill 4670 -39 3 4670 -39 19 minecraft:glowstone
fill 4688 -39 3 4688 -39 19 minecraft:glowstone
fill 4671 -39 3 4687 -39 3 minecraft:glowstone
fill 4671 -39 19 4687 -39 19 minecraft:glowstone
fill 4671 -39 4 4671 -39 18 minecraft:glowstone
fill 4687 -39 4 4687 -39 18 minecraft:glowstone
fill 4677 -39 9 4681 -39 13 minecraft:glowstone
fill 4668 -51 0 4690 -51 0 minecraft:glowstone
fill 4668 -51 22 4690 -51 22 minecraft:glowstone
fill 4668 -51 1 4668 -51 21 minecraft:glowstone
fill 4690 -51 1 4690 -51 21 minecraft:glowstone
fill 4672 -57 4 4686 -55 18 minecraft:light_gray_concrete
fill 4672 -57 4 4686 -57 18 minecraft:glowstone
fill 4673 -57 5 4673 -55 5 minecraft:air
fill 4673 -57 6 4673 -55 6 minecraft:air
fill 4673 -57 7 4673 -55 7 minecraft:air
fill 4674 -57 7 4674 -55 7 minecraft:air
fill 4674 -57 8 4674 -55 8 minecraft:air
fill 4675 -57 8 4675 -55 8 minecraft:air
fill 4676 -57 8 4676 -55 8 minecraft:air
fill 4676 -57 9 4676 -55 9 minecraft:air
fill 4677 -57 8 4677 -55 8 minecraft:air
fill 4677 -57 9 4677 -55 9 minecraft:air
fill 4678 -57 8 4678 -55 8 minecraft:air
fill 4678 -57 9 4678 -55 9 minecraft:air
fill 4679 -57 8 4679 -55 8 minecraft:air
fill 4679 -57 9 4679 -55 9 minecraft:air
fill 4680 -57 8 4680 -55 8 minecraft:air
fill 4680 -57 9 4680 -55 9 minecraft:air
fill 4680 -57 10 4680 -55 10 minecraft:air
fill 4680 -57 11 4680 -55 11 minecraft:air
fill 4680 -57 12 4680 -55 12 minecraft:air
fill 4680 -57 13 4680 -55 13 minecraft:air
fill 4681 -57 8 4681 -55 8 minecraft:air
fill 4681 -57 9 4681 -55 9 minecraft:air
fill 4681 -57 10 4681 -55 10 minecraft:air
fill 4681 -57 11 4681 -55 11 minecraft:air
fill 4681 -57 12 4681 -55 12 minecraft:air
fill 4681 -57 13 4681 -55 13 minecraft:air
fill 4676 -58 8 4677 -58 9 minecraft:white_concrete
fill 4680 -58 12 4681 -58 13 minecraft:lime_concrete
setblock 4673 -57 6 minecraft:crafting_table
setblock 4678 -57 8 minecraft:furnace
setblock 4679 -57 8 minecraft:crafting_table
setblock 4680 -57 11 minecraft:crafting_table
