# Scene: truck_easy_01
# Auto-generated by multiagent/scene/generate_scenes.py
fill 1800 -58 0 1823 -58 22 minecraft:white_concrete
fill 1800 -57 0 1823 -52 22 minecraft:white_concrete
fill 1799 -57 0 1799 -52 22 minecraft:white_concrete
fill 1824 -57 0 1824 -52 22 minecraft:white_concrete
fill 1799 -57 -1 1824 -52 -1 minecraft:white_concrete
fill 1799 -57 23 1824 -52 23 minecraft:white_concrete
fill 1801 -57 1 1822 -52 21 minecraft:air
fill 1800 -51 0 1823 -51 22 minecraft:white_concrete
fill 1801 -51 1 1822 -51 1 minecraft:glowstone
fill 1801 -51 21 1822 -51 21 minecraft:glowstone
fill 1801 -51 2 1801 -51 20 minecraft:glowstone
fill 1822 -51 2 1822 -51 20 minecraft:glowstone
fill 1802 -51 2 1821 -51 2 minecraft:glowstone
fill 1802 -51 20 1821 -51 20 minecraft:glowstone
fill 1802 -51 3 1802 -51 19 minecraft:glowstone
fill 1821 -51 3 1821 -51 19 minecraft:glowstone
fill 1803 -51 3 1820 -51 3 minecraft:glowstone
fill 1803 -51 19 1820 -51 19 minecraft:glowstone
fill 1803 -51 4 1803 -51 18 minecraft:glowstone
fill 1820 -51 4 1820 -51 18 minecraft:glowstone
fill 1809 -51 9 1813 -51 13 minecraft:glowstone
fill 1811 -58 10 1814 -58 13 minecraft:red_concrete
setblock 1821 -57 14 minecraft:stone_slab[type=bottom]
setblock 1802 -57 10 minecraft:bookshelf
setblock 1821 -57 15 minecraft:crafting_table
setblock 1821 -57 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1802 -57 14 minecraft:chest
setblock 1821 -57 20 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1821 -57 12 minecraft:stone_slab[type=bottom]
setblock 1802 -57 17 minecraft:bookshelf
setblock 1802 -57 13 minecraft:furnace
setblock 1802 -57 6 minecraft:stone_slab[type=bottom]
setblock 1821 -57 10 minecraft:furnace
setblock 1821 -57 6 minecraft:stone_slab[type=bottom]
