# Scene: tier_path_easy_15
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 15 of 15 with 3-5 decorations.
fill 1321 -58 0 1341 -58 31 minecraft:white_concrete
fill 1321 -57 0 1341 -52 31 minecraft:white_concrete
fill 1320 -57 0 1320 -52 31 minecraft:white_concrete
fill 1342 -57 0 1342 -52 31 minecraft:white_concrete
fill 1320 -57 -1 1342 -52 -1 minecraft:white_concrete
fill 1320 -57 32 1342 -52 32 minecraft:white_concrete
fill 1322 -57 1 1340 -52 30 minecraft:air
fill 1321 -51 0 1341 -51 31 minecraft:white_concrete
fill 1322 -51 1 1340 -51 1 minecraft:glowstone
fill 1322 -51 30 1340 -51 30 minecraft:glowstone
fill 1322 -51 2 1322 -51 29 minecraft:glowstone
fill 1340 -51 2 1340 -51 29 minecraft:glowstone
fill 1323 -51 2 1339 -51 2 minecraft:glowstone
fill 1323 -51 29 1339 -51 29 minecraft:glowstone
fill 1323 -51 3 1323 -51 28 minecraft:glowstone
fill 1339 -51 3 1339 -51 28 minecraft:glowstone
fill 1324 -51 3 1338 -51 3 minecraft:glowstone
fill 1324 -51 28 1338 -51 28 minecraft:glowstone
fill 1324 -51 4 1324 -51 27 minecraft:glowstone
fill 1338 -51 4 1338 -51 27 minecraft:glowstone
fill 1329 -51 13 1333 -51 17 minecraft:glowstone
fill 1321 -61 0 1341 -58 31 minecraft:white_concrete
fill 1321 -61 0 1341 -58 13 minecraft:white_concrete
fill 1321 -61 18 1341 -58 31 minecraft:white_concrete
fill 1322 -61 14 1340 -58 17 minecraft:air
fill 1321 -61 0 1341 -61 31 minecraft:black_concrete
fill 1329 -58 14 1332 -58 17 minecraft:air
fill 1329 -57 19 1332 -57 19 minecraft:gold_block
setblock 1330 -57 9 minecraft:birch_pressure_plate
setblock 1330 -57 10 minecraft:birch_pressure_plate
setblock 1330 -57 11 minecraft:birch_pressure_plate
setblock 1330 -57 12 minecraft:birch_pressure_plate
setblock 1331 -57 9 minecraft:birch_pressure_plate
setblock 1331 -57 10 minecraft:birch_pressure_plate
setblock 1331 -57 11 minecraft:birch_pressure_plate
setblock 1331 -57 12 minecraft:birch_pressure_plate
setblock 1332 -57 9 minecraft:birch_pressure_plate
setblock 1332 -57 10 minecraft:birch_pressure_plate
setblock 1332 -57 11 minecraft:birch_pressure_plate
setblock 1332 -57 12 minecraft:birch_pressure_plate
setblock 1333 -57 9 minecraft:birch_pressure_plate
setblock 1333 -57 10 minecraft:birch_pressure_plate
setblock 1333 -57 11 minecraft:birch_pressure_plate
setblock 1333 -57 12 minecraft:birch_pressure_plate
setblock 1334 -57 2 minecraft:furnace
setblock 1331 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1323 -57 7 minecraft:furnace
setblock 1324 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1323 -57 9 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_easy_15/place_command_blocks
