# Scene: maze_easy_14
# Auto-generated by multiagent/scene/generate_scenes.py
fill 4203 -58 0 4225 -58 22 minecraft:white_concrete
fill 4203 -57 0 4225 -40 22 minecraft:white_concrete
fill 4202 -57 0 4202 -40 22 minecraft:white_concrete
fill 4226 -57 0 4226 -40 22 minecraft:white_concrete
fill 4202 -57 -1 4226 -40 -1 minecraft:white_concrete
fill 4202 -57 23 4226 -40 23 minecraft:white_concrete
fill 4204 -57 1 4224 -40 21 minecraft:air
fill 4203 -39 0 4225 -39 22 minecraft:white_concrete
fill 4204 -39 1 4224 -39 1 minecraft:glowstone
fill 4204 -39 21 4224 -39 21 minecraft:glowstone
fill 4204 -39 2 4204 -39 20 minecraft:glowstone
fill 4224 -39 2 4224 -39 20 minecraft:glowstone
fill 4205 -39 2 4223 -39 2 minecraft:glowstone
fill 4205 -39 20 4223 -39 20 minecraft:glowstone
fill 4205 -39 3 4205 -39 19 minecraft:glowstone
fill 4223 -39 3 4223 -39 19 minecraft:glowstone
fill 4206 -39 3 4222 -39 3 minecraft:glowstone
fill 4206 -39 19 4222 -39 19 minecraft:glowstone
fill 4206 -39 4 4206 -39 18 minecraft:glowstone
fill 4222 -39 4 4222 -39 18 minecraft:glowstone
fill 4212 -39 9 4216 -39 13 minecraft:glowstone
fill 4203 -51 0 4225 -51 0 minecraft:glowstone
fill 4203 -51 22 4225 -51 22 minecraft:glowstone
fill 4203 -51 1 4203 -51 21 minecraft:glowstone
fill 4225 -51 1 4225 -51 21 minecraft:glowstone
fill 4207 -57 4 4221 -55 18 minecraft:light_gray_concrete
fill 4207 -57 4 4221 -57 18 minecraft:glowstone
fill 4209 -57 9 4209 -55 9 minecraft:air
fill 4209 -57 10 4209 -55 10 minecraft:air
fill 4210 -57 9 4210 -55 9 minecraft:air
fill 4210 -57 10 4210 -55 10 minecraft:air
fill 4211 -57 9 4211 -55 9 minecraft:air
fill 4211 -57 10 4211 -55 10 minecraft:air
fill 4212 -57 9 4212 -55 9 minecraft:air
fill 4212 -57 10 4212 -55 10 minecraft:air
fill 4213 -57 9 4213 -55 9 minecraft:air
fill 4213 -57 10 4213 -55 10 minecraft:air
fill 4214 -57 9 4214 -55 9 minecraft:air
fill 4214 -57 10 4214 -55 10 minecraft:air
fill 4215 -57 9 4215 -55 9 minecraft:air
fill 4215 -57 10 4215 -55 10 minecraft:air
fill 4216 -57 9 4216 -55 9 minecraft:air
fill 4216 -57 10 4216 -55 10 minecraft:air
fill 4209 -58 9 4210 -58 10 minecraft:white_concrete
fill 4215 -58 9 4216 -58 10 minecraft:lime_concrete
setblock 4211 -57 10 minecraft:crafting_table
setblock 4212 -57 10 minecraft:stone_slab[type=bottom]
setblock 4213 -57 10 minecraft:furnace
setblock 4214 -57 10 minecraft:crafting_table
