# Scene: picture_hard_14
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3875 -58 0 3891 -58 18 minecraft:white_concrete
fill 3875 -57 0 3891 -49 18 minecraft:white_concrete
fill 3874 -57 0 3874 -49 18 minecraft:white_concrete
fill 3892 -57 0 3892 -49 18 minecraft:white_concrete
fill 3874 -57 -1 3892 -49 -1 minecraft:white_concrete
fill 3874 -57 19 3892 -49 19 minecraft:white_concrete
fill 3876 -57 1 3890 -49 17 minecraft:air
fill 3875 -48 0 3891 -48 18 minecraft:white_concrete
fill 3876 -48 1 3890 -48 1 minecraft:glowstone
fill 3876 -48 17 3890 -48 17 minecraft:glowstone
fill 3876 -48 2 3876 -48 16 minecraft:glowstone
fill 3890 -48 2 3890 -48 16 minecraft:glowstone
fill 3877 -48 2 3889 -48 2 minecraft:glowstone
fill 3877 -48 16 3889 -48 16 minecraft:glowstone
fill 3877 -48 3 3877 -48 15 minecraft:glowstone
fill 3889 -48 3 3889 -48 15 minecraft:glowstone
fill 3878 -48 3 3888 -48 3 minecraft:glowstone
fill 3878 -48 15 3888 -48 15 minecraft:glowstone
fill 3878 -48 4 3878 -48 14 minecraft:glowstone
fill 3888 -48 4 3888 -48 14 minecraft:glowstone
fill 3881 -48 7 3885 -48 11 minecraft:glowstone
fill 3876 -53 1 3890 -53 5 minecraft:glowstone
fill 3876 -52 1 3890 -52 5 minecraft:smooth_stone
fill 3876 -51 6 3890 -51 6 minecraft:oak_fence
fill 3885 -57 1 3887 -57 3 minecraft:lime_concrete
fill 3883 -52 10 3883 -52 10 minecraft:smooth_stone
setblock 3880 -51 4 minecraft:bookshelf
setblock 3876 -51 2 minecraft:stone_slab[type=bottom]
setblock 3887 -51 5 minecraft:furnace
setblock 3884 -51 1 minecraft:stone_slab[type=bottom]
setblock 3881 -51 5 minecraft:bookshelf
setblock 3880 -51 2 minecraft:furnace
