# Scene: picture_hard_13
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3850 -58 0 3866 -58 18 minecraft:white_concrete
fill 3850 -57 0 3866 -49 18 minecraft:white_concrete
fill 3849 -57 0 3849 -49 18 minecraft:white_concrete
fill 3867 -57 0 3867 -49 18 minecraft:white_concrete
fill 3849 -57 -1 3867 -49 -1 minecraft:white_concrete
fill 3849 -57 19 3867 -49 19 minecraft:white_concrete
fill 3851 -57 1 3865 -49 17 minecraft:air
fill 3850 -48 0 3866 -48 18 minecraft:white_concrete
fill 3851 -48 1 3865 -48 1 minecraft:glowstone
fill 3851 -48 17 3865 -48 17 minecraft:glowstone
fill 3851 -48 2 3851 -48 16 minecraft:glowstone
fill 3865 -48 2 3865 -48 16 minecraft:glowstone
fill 3852 -48 2 3864 -48 2 minecraft:glowstone
fill 3852 -48 16 3864 -48 16 minecraft:glowstone
fill 3852 -48 3 3852 -48 15 minecraft:glowstone
fill 3864 -48 3 3864 -48 15 minecraft:glowstone
fill 3853 -48 3 3863 -48 3 minecraft:glowstone
fill 3853 -48 15 3863 -48 15 minecraft:glowstone
fill 3853 -48 4 3853 -48 14 minecraft:glowstone
fill 3863 -48 4 3863 -48 14 minecraft:glowstone
fill 3856 -48 7 3860 -48 11 minecraft:glowstone
fill 3851 -53 1 3865 -53 5 minecraft:glowstone
fill 3851 -52 1 3865 -52 5 minecraft:smooth_stone
fill 3851 -51 6 3865 -51 6 minecraft:oak_fence
fill 3855 -57 2 3857 -57 4 minecraft:yellow_concrete
fill 3858 -52 10 3858 -52 10 minecraft:smooth_stone
setblock 3863 -51 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3852 -51 5 minecraft:stone_slab[type=bottom]
setblock 3854 -51 1 minecraft:bookshelf
setblock 3857 -51 1 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
