# Scene: truck_easy_10
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2084 -58 0 2106 -58 23 minecraft:white_concrete
fill 2084 -57 0 2106 -52 23 minecraft:white_concrete
fill 2083 -57 0 2083 -52 23 minecraft:white_concrete
fill 2107 -57 0 2107 -52 23 minecraft:white_concrete
fill 2083 -57 -1 2107 -52 -1 minecraft:white_concrete
fill 2083 -57 24 2107 -52 24 minecraft:white_concrete
fill 2085 -57 1 2105 -52 22 minecraft:air
fill 2084 -51 0 2106 -51 23 minecraft:white_concrete
fill 2085 -51 1 2105 -51 1 minecraft:glowstone
fill 2085 -51 22 2105 -51 22 minecraft:glowstone
fill 2085 -51 2 2085 -51 21 minecraft:glowstone
fill 2105 -51 2 2105 -51 21 minecraft:glowstone
fill 2086 -51 2 2104 -51 2 minecraft:glowstone
fill 2086 -51 21 2104 -51 21 minecraft:glowstone
fill 2086 -51 3 2086 -51 20 minecraft:glowstone
fill 2104 -51 3 2104 -51 20 minecraft:glowstone
fill 2087 -51 3 2103 -51 3 minecraft:glowstone
fill 2087 -51 20 2103 -51 20 minecraft:glowstone
fill 2087 -51 4 2087 -51 19 minecraft:glowstone
fill 2103 -51 4 2103 -51 19 minecraft:glowstone
fill 2093 -51 9 2097 -51 13 minecraft:glowstone
fill 2094 -58 11 2097 -58 14 minecraft:magenta_concrete
setblock 2104 -57 13 minecraft:bookshelf
setblock 2104 -57 6 minecraft:bookshelf
setblock 2086 -57 2 minecraft:bookshelf
setblock 2086 -57 15 minecraft:furnace
setblock 2104 -57 4 minecraft:crafting_table
setblock 2104 -57 5 minecraft:crafting_table
setblock 2104 -57 11 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2104 -57 8 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2104 -57 3 minecraft:stone_slab[type=bottom]
setblock 2104 -57 7 minecraft:furnace
