# Scene: maze_easy_13
# Auto-generated by multiagent/scene/generate_scenes.py
fill 4172 -58 0 4194 -58 22 minecraft:white_concrete
fill 4172 -57 0 4194 -40 22 minecraft:white_concrete
fill 4171 -57 0 4171 -40 22 minecraft:white_concrete
fill 4195 -57 0 4195 -40 22 minecraft:white_concrete
fill 4171 -57 -1 4195 -40 -1 minecraft:white_concrete
fill 4171 -57 23 4195 -40 23 minecraft:white_concrete
fill 4173 -57 1 4193 -40 21 minecraft:air
fill 4172 -39 0 4194 -39 22 minecraft:white_concrete
fill 4173 -39 1 4193 -39 1 minecraft:glowstone
fill 4173 -39 21 4193 -39 21 minecraft:glowstone
fill 4173 -39 2 4173 -39 20 minecraft:glowstone
fill 4193 -39 2 4193 -39 20 minecraft:glowstone
fill 4174 -39 2 4192 -39 2 minecraft:glowstone
fill 4174 -39 20 4192 -39 20 minecraft:glowstone
fill 4174 -39 3 4174 -39 19 minecraft:glowstone
fill 4192 -39 3 4192 -39 19 minecraft:glowstone
fill 4175 -39 3 4191 -39 3 minecraft:glowstone
fill 4175 -39 19 4191 -39 19 minecraft:glowstone
fill 4175 -39 4 4175 -39 18 minecraft:glowstone
fill 4191 -39 4 4191 -39 18 minecraft:glowstone
fill 4181 -39 9 4185 -39 13 minecraft:glowstone
fill 4172 -51 0 4194 -51 0 minecraft:glowstone
fill 4172 -51 22 4194 -51 22 minecraft:glowstone
fill 4172 -51 1 4172 -51 21 minecraft:glowstone
fill 4194 -51 1 4194 -51 21 minecraft:glowstone
fill 4176 -57 4 4190 -55 18 minecraft:light_gray_concrete
fill 4176 -57 4 4190 -57 18 minecraft:glowstone
fill 4181 -57 6 4181 -55 6 minecraft:air
fill 4181 -57 7 4181 -55 7 minecraft:air
fill 4182 -57 6 4182 -55 6 minecraft:air
fill 4182 -57 7 4182 -55 7 minecraft:air
fill 4183 -57 6 4183 -55 6 minecraft:air
fill 4183 -57 7 4183 -55 7 minecraft:air
fill 4184 -57 6 4184 -55 6 minecraft:air
fill 4184 -57 7 4184 -55 7 minecraft:air
fill 4185 -57 6 4185 -55 6 minecraft:air
fill 4185 -57 7 4185 -55 7 minecraft:air
fill 4186 -57 6 4186 -55 6 minecraft:air
fill 4186 -57 7 4186 -55 7 minecraft:air
fill 4187 -57 6 4187 -55 6 minecraft:air
fill 4187 -57 7 4187 -55 7 minecraft:air
fill 4188 -57 6 4188 -55 6 minecraft:air
fill 4188 -57 7 4188 -55 7 minecraft:air
fill 4181 -58 6 4182 -58 7 minecraft:white_concrete
fill 4187 -58 6 4188 -58 7 minecraft:yellow_concrete
setblock 4183 -57 7 minecraft:chest
setblock 4184 -57 7 minecraft:stone_slab[type=bottom]
setblock 4186 -57 6 minecraft:crafting_table
