# Scene: tier_path_hard_03
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 3 of 15 with 3-5 decorations.
fill 1861 -58 0 1881 -58 31 minecraft:white_concrete
fill 1861 -57 0 1881 -52 31 minecraft:white_concrete
fill 1860 -57 0 1860 -52 31 minecraft:white_concrete
fill 1882 -57 0 1882 -52 31 minecraft:white_concrete
fill 1860 -57 -1 1882 -52 -1 minecraft:white_concrete
fill 1860 -57 32 1882 -52 32 minecraft:white_concrete
fill 1862 -57 1 1880 -52 30 minecraft:air
fill 1861 -51 0 1881 -51 31 minecraft:white_concrete
fill 1862 -51 1 1880 -51 1 minecraft:glowstone
fill 1862 -51 30 1880 -51 30 minecraft:glowstone
fill 1862 -51 2 1862 -51 29 minecraft:glowstone
fill 1880 -51 2 1880 -51 29 minecraft:glowstone
fill 1863 -51 2 1879 -51 2 minecraft:glowstone
fill 1863 -51 29 1879 -51 29 minecraft:glowstone
fill 1863 -51 3 1863 -51 28 minecraft:glowstone
fill 1879 -51 3 1879 -51 28 minecraft:glowstone
fill 1864 -51 3 1878 -51 3 minecraft:glowstone
fill 1864 -51 28 1878 -51 28 minecraft:glowstone
fill 1864 -51 4 1864 -51 27 minecraft:glowstone
fill 1878 -51 4 1878 -51 27 minecraft:glowstone
fill 1869 -51 13 1873 -51 17 minecraft:glowstone
fill 1861 -61 0 1881 -58 31 minecraft:white_concrete
fill 1861 -61 0 1881 -58 12 minecraft:white_concrete
fill 1861 -61 19 1881 -58 31 minecraft:white_concrete
fill 1862 -61 13 1880 -58 18 minecraft:air
fill 1861 -61 0 1881 -61 31 minecraft:black_concrete
fill 1870 -58 13 1872 -58 18 minecraft:air
fill 1870 -57 20 1872 -57 20 minecraft:gold_block
setblock 1870 -57 8 minecraft:oak_pressure_plate
setblock 1870 -57 9 minecraft:oak_pressure_plate
setblock 1870 -57 10 minecraft:oak_pressure_plate
setblock 1871 -57 8 minecraft:oak_pressure_plate
setblock 1871 -57 9 minecraft:oak_pressure_plate
setblock 1871 -57 10 minecraft:oak_pressure_plate
setblock 1872 -57 8 minecraft:oak_pressure_plate
setblock 1872 -57 9 minecraft:oak_pressure_plate
setblock 1872 -57 10 minecraft:oak_pressure_plate
setblock 1863 -57 4 minecraft:chest
setblock 1879 -57 9 minecraft:crafting_table
setblock 1863 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1863 -57 9 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_03/place_command_blocks
