# Scene: tier_elevator_medium_03
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 3 of 15 with 3-5 decorations.
fill 511 -59 0 531 -59 23 minecraft:white_concrete
fill 511 -58 0 531 -53 23 minecraft:white_concrete
fill 510 -58 0 510 -53 23 minecraft:white_concrete
fill 532 -58 0 532 -53 23 minecraft:white_concrete
fill 510 -58 -1 532 -53 -1 minecraft:white_concrete
fill 510 -58 24 532 -53 24 minecraft:white_concrete
fill 512 -58 1 530 -53 22 minecraft:air
fill 511 -52 0 531 -52 23 minecraft:white_concrete
fill 512 -52 1 530 -52 1 minecraft:glowstone
fill 512 -52 22 530 -52 22 minecraft:glowstone
fill 512 -52 2 512 -52 21 minecraft:glowstone
fill 530 -52 2 530 -52 21 minecraft:glowstone
fill 513 -52 2 529 -52 2 minecraft:glowstone
fill 513 -52 21 529 -52 21 minecraft:glowstone
fill 513 -52 3 513 -52 20 minecraft:glowstone
fill 529 -52 3 529 -52 20 minecraft:glowstone
fill 514 -52 3 528 -52 3 minecraft:glowstone
fill 514 -52 20 528 -52 20 minecraft:glowstone
fill 514 -52 4 514 -52 19 minecraft:glowstone
fill 528 -52 4 528 -52 19 minecraft:glowstone
fill 519 -52 9 523 -52 13 minecraft:glowstone
fill 512 -58 12 530 -53 12 minecraft:white_concrete
fill 519 -58 12 520 -56 12 minecraft:black_concrete
setblock 519 -58 7 minecraft:birch_pressure_plate
setblock 519 -58 8 minecraft:birch_pressure_plate
setblock 519 -58 9 minecraft:birch_pressure_plate
setblock 520 -58 7 minecraft:birch_pressure_plate
setblock 520 -58 8 minecraft:birch_pressure_plate
setblock 520 -58 9 minecraft:birch_pressure_plate
setblock 521 -58 7 minecraft:birch_pressure_plate
setblock 521 -58 8 minecraft:birch_pressure_plate
setblock 521 -58 9 minecraft:birch_pressure_plate
setblock 517 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 516 -58 2 minecraft:furnace
setblock 529 -58 9 minecraft:chest
setblock 529 -58 10 minecraft:chest

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_03/place_command_blocks
