# Scene: truck_hard_03
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2809 -58 0 2832 -58 22 minecraft:white_concrete
fill 2809 -57 0 2832 -52 22 minecraft:white_concrete
fill 2808 -57 0 2808 -52 22 minecraft:white_concrete
fill 2833 -57 0 2833 -52 22 minecraft:white_concrete
fill 2808 -57 -1 2833 -52 -1 minecraft:white_concrete
fill 2808 -57 23 2833 -52 23 minecraft:white_concrete
fill 2810 -57 1 2831 -52 21 minecraft:air
fill 2809 -51 0 2832 -51 22 minecraft:white_concrete
fill 2810 -51 1 2831 -51 1 minecraft:glowstone
fill 2810 -51 21 2831 -51 21 minecraft:glowstone
fill 2810 -51 2 2810 -51 20 minecraft:glowstone
fill 2831 -51 2 2831 -51 20 minecraft:glowstone
fill 2811 -51 2 2830 -51 2 minecraft:glowstone
fill 2811 -51 20 2830 -51 20 minecraft:glowstone
fill 2811 -51 3 2811 -51 19 minecraft:glowstone
fill 2830 -51 3 2830 -51 19 minecraft:glowstone
fill 2812 -51 3 2829 -51 3 minecraft:glowstone
fill 2812 -51 19 2829 -51 19 minecraft:glowstone
fill 2812 -51 4 2812 -51 18 minecraft:glowstone
fill 2829 -51 4 2829 -51 18 minecraft:glowstone
fill 2818 -51 9 2822 -51 13 minecraft:glowstone
fill 2821 -58 11 2822 -58 12 minecraft:yellow_concrete
setblock 2830 -57 16 minecraft:furnace
setblock 2811 -57 2 minecraft:stone_slab[type=bottom]
setblock 2811 -57 20 minecraft:furnace
setblock 2811 -57 3 minecraft:bookshelf
setblock 2830 -57 19 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2830 -57 17 minecraft:chest
setblock 2830 -57 13 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2830 -57 7 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2830 -57 9 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2811 -57 6 minecraft:stone_slab[type=bottom]
setblock 2811 -57 5 minecraft:bookshelf
setblock 2811 -57 10 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2811 -57 19 minecraft:stone_slab[type=bottom]
setblock 2830 -57 20 minecraft:bookshelf
setblock 2811 -57 11 minecraft:chest
