# Scene: tier_elevator_easy_12
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 12 of 15 with 3-5 decorations.
fill 331 -59 0 351 -59 22 minecraft:white_concrete
fill 331 -58 0 351 -53 22 minecraft:white_concrete
fill 330 -58 0 330 -53 22 minecraft:white_concrete
fill 352 -58 0 352 -53 22 minecraft:white_concrete
fill 330 -58 -1 352 -53 -1 minecraft:white_concrete
fill 330 -58 23 352 -53 23 minecraft:white_concrete
fill 332 -58 1 350 -53 21 minecraft:air
fill 331 -52 0 351 -52 22 minecraft:white_concrete
fill 332 -52 1 350 -52 1 minecraft:glowstone
fill 332 -52 21 350 -52 21 minecraft:glowstone
fill 332 -52 2 332 -52 20 minecraft:glowstone
fill 350 -52 2 350 -52 20 minecraft:glowstone
fill 333 -52 2 349 -52 2 minecraft:glowstone
fill 333 -52 20 349 -52 20 minecraft:glowstone
fill 333 -52 3 333 -52 19 minecraft:glowstone
fill 349 -52 3 349 -52 19 minecraft:glowstone
fill 334 -52 3 348 -52 3 minecraft:glowstone
fill 334 -52 19 348 -52 19 minecraft:glowstone
fill 334 -52 4 334 -52 18 minecraft:glowstone
fill 348 -52 4 348 -52 18 minecraft:glowstone
fill 339 -52 9 343 -52 13 minecraft:glowstone
fill 332 -58 11 350 -53 11 minecraft:white_concrete
fill 339 -58 11 341 -56 11 minecraft:gray_concrete
setblock 342 -58 5 minecraft:birch_pressure_plate
setblock 342 -58 6 minecraft:birch_pressure_plate
setblock 342 -58 7 minecraft:birch_pressure_plate
setblock 342 -58 8 minecraft:birch_pressure_plate
setblock 343 -58 5 minecraft:birch_pressure_plate
setblock 343 -58 6 minecraft:birch_pressure_plate
setblock 343 -58 7 minecraft:birch_pressure_plate
setblock 343 -58 8 minecraft:birch_pressure_plate
setblock 344 -58 5 minecraft:birch_pressure_plate
setblock 344 -58 6 minecraft:birch_pressure_plate
setblock 344 -58 7 minecraft:birch_pressure_plate
setblock 344 -58 8 minecraft:birch_pressure_plate
setblock 345 -58 5 minecraft:birch_pressure_plate
setblock 345 -58 6 minecraft:birch_pressure_plate
setblock 345 -58 7 minecraft:birch_pressure_plate
setblock 345 -58 8 minecraft:birch_pressure_plate
setblock 349 -58 7 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 348 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 349 -58 9 minecraft:stone_slab[type=bottom]
setblock 333 -58 3 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_easy_12/place_command_blocks
