# Scene: truck_easy_12
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2147 -58 0 2169 -58 23 minecraft:white_concrete
fill 2147 -57 0 2169 -52 23 minecraft:white_concrete
fill 2146 -57 0 2146 -52 23 minecraft:white_concrete
fill 2170 -57 0 2170 -52 23 minecraft:white_concrete
fill 2146 -57 -1 2170 -52 -1 minecraft:white_concrete
fill 2146 -57 24 2170 -52 24 minecraft:white_concrete
fill 2148 -57 1 2168 -52 22 minecraft:air
fill 2147 -51 0 2169 -51 23 minecraft:white_concrete
fill 2148 -51 1 2168 -51 1 minecraft:glowstone
fill 2148 -51 22 2168 -51 22 minecraft:glowstone
fill 2148 -51 2 2148 -51 21 minecraft:glowstone
fill 2168 -51 2 2168 -51 21 minecraft:glowstone
fill 2149 -51 2 2167 -51 2 minecraft:glowstone
fill 2149 -51 21 2167 -51 21 minecraft:glowstone
fill 2149 -51 3 2149 -51 20 minecraft:glowstone
fill 2167 -51 3 2167 -51 20 minecraft:glowstone
fill 2150 -51 3 2166 -51 3 minecraft:glowstone
fill 2150 -51 20 2166 -51 20 minecraft:glowstone
fill 2150 -51 4 2150 -51 19 minecraft:glowstone
fill 2166 -51 4 2166 -51 19 minecraft:glowstone
fill 2156 -51 9 2160 -51 13 minecraft:glowstone
fill 2157 -58 11 2160 -58 14 minecraft:orange_concrete
setblock 2167 -57 6 minecraft:crafting_table
setblock 2149 -57 11 minecraft:chest
setblock 2167 -57 16 minecraft:chest
setblock 2167 -57 10 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2167 -57 7 minecraft:furnace
setblock 2149 -57 8 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2149 -57 17 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2167 -57 13 minecraft:stone_slab[type=bottom]
setblock 2167 -57 3 minecraft:chest
setblock 2167 -57 18 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2149 -57 21 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
