# Scene: picture_hard_09
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3750 -58 0 3766 -58 18 minecraft:white_concrete
fill 3750 -57 0 3766 -49 18 minecraft:white_concrete
fill 3749 -57 0 3749 -49 18 minecraft:white_concrete
fill 3767 -57 0 3767 -49 18 minecraft:white_concrete
fill 3749 -57 -1 3767 -49 -1 minecraft:white_concrete
fill 3749 -57 19 3767 -49 19 minecraft:white_concrete
fill 3751 -57 1 3765 -49 17 minecraft:air
fill 3750 -48 0 3766 -48 18 minecraft:white_concrete
fill 3751 -48 1 3765 -48 1 minecraft:glowstone
fill 3751 -48 17 3765 -48 17 minecraft:glowstone
fill 3751 -48 2 3751 -48 16 minecraft:glowstone
fill 3765 -48 2 3765 -48 16 minecraft:glowstone
fill 3752 -48 2 3764 -48 2 minecraft:glowstone
fill 3752 -48 16 3764 -48 16 minecraft:glowstone
fill 3752 -48 3 3752 -48 15 minecraft:glowstone
fill 3764 -48 3 3764 -48 15 minecraft:glowstone
fill 3753 -48 3 3763 -48 3 minecraft:glowstone
fill 3753 -48 15 3763 -48 15 minecraft:glowstone
fill 3753 -48 4 3753 -48 14 minecraft:glowstone
fill 3763 -48 4 3763 -48 14 minecraft:glowstone
fill 3756 -48 7 3760 -48 11 minecraft:glowstone
fill 3751 -53 1 3765 -53 5 minecraft:glowstone
fill 3751 -52 1 3765 -52 5 minecraft:smooth_stone
fill 3751 -51 6 3765 -51 6 minecraft:oak_fence
fill 3752 -57 2 3754 -57 4 minecraft:purple_concrete
fill 3758 -52 10 3758 -52 10 minecraft:smooth_stone
setblock 3758 -51 4 minecraft:chest
setblock 3764 -51 5 minecraft:bookshelf
setblock 3763 -51 3 minecraft:stone_slab[type=bottom]
setblock 3764 -51 2 minecraft:stone_slab[type=bottom]
setblock 3759 -51 3 minecraft:chest
