# Scene: tier_path_hard_05
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 5 of 15 with 3-5 decorations.
fill 1920 -58 0 1942 -58 31 minecraft:white_concrete
fill 1920 -57 0 1942 -52 31 minecraft:white_concrete
fill 1919 -57 0 1919 -52 31 minecraft:white_concrete
fill 1943 -57 0 1943 -52 31 minecraft:white_concrete
fill 1919 -57 -1 1943 -52 -1 minecraft:white_concrete
fill 1919 -57 32 1943 -52 32 minecraft:white_concrete
fill 1921 -57 1 1941 -52 30 minecraft:air
fill 1920 -51 0 1942 -51 31 minecraft:white_concrete
fill 1921 -51 1 1941 -51 1 minecraft:glowstone
fill 1921 -51 30 1941 -51 30 minecraft:glowstone
fill 1921 -51 2 1921 -51 29 minecraft:glowstone
fill 1941 -51 2 1941 -51 29 minecraft:glowstone
fill 1922 -51 2 1940 -51 2 minecraft:glowstone
fill 1922 -51 29 1940 -51 29 minecraft:glowstone
fill 1922 -51 3 1922 -51 28 minecraft:glowstone
fill 1940 -51 3 1940 -51 28 minecraft:glowstone
fill 1923 -51 3 1939 -51 3 minecraft:glowstone
fill 1923 -51 28 1939 -51 28 minecraft:glowstone
fill 1923 -51 4 1923 -51 27 minecraft:glowstone
fill 1939 -51 4 1939 -51 27 minecraft:glowstone
fill 1929 -51 13 1933 -51 17 minecraft:glowstone
fill 1920 -61 0 1942 -58 31 minecraft:white_concrete
fill 1920 -61 0 1942 -58 12 minecraft:white_concrete
fill 1920 -61 19 1942 -58 31 minecraft:white_concrete
fill 1921 -61 13 1941 -58 18 minecraft:air
fill 1920 -61 0 1942 -61 31 minecraft:black_concrete
fill 1930 -58 13 1932 -58 18 minecraft:air
fill 1930 -57 20 1932 -57 20 minecraft:gold_block
setblock 1930 -57 8 minecraft:birch_pressure_plate
setblock 1930 -57 9 minecraft:birch_pressure_plate
setblock 1930 -57 10 minecraft:birch_pressure_plate
setblock 1931 -57 8 minecraft:birch_pressure_plate
setblock 1931 -57 9 minecraft:birch_pressure_plate
setblock 1931 -57 10 minecraft:birch_pressure_plate
setblock 1932 -57 8 minecraft:birch_pressure_plate
setblock 1932 -57 9 minecraft:birch_pressure_plate
setblock 1932 -57 10 minecraft:birch_pressure_plate
setblock 1936 -57 2 minecraft:bookshelf
setblock 1940 -57 10 minecraft:chest
setblock 1933 -57 2 minecraft:chest
setblock 1940 -57 7 minecraft:furnace
setblock 1924 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_05/place_command_blocks
