# Scene: tier_path_hard_04
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 4 of 15 with 3-5 decorations.
fill 1890 -58 0 1911 -58 30 minecraft:white_concrete
fill 1890 -57 0 1911 -52 30 minecraft:white_concrete
fill 1889 -57 0 1889 -52 30 minecraft:white_concrete
fill 1912 -57 0 1912 -52 30 minecraft:white_concrete
fill 1889 -57 -1 1912 -52 -1 minecraft:white_concrete
fill 1889 -57 31 1912 -52 31 minecraft:white_concrete
fill 1891 -57 1 1910 -52 29 minecraft:air
fill 1890 -51 0 1911 -51 30 minecraft:white_concrete
fill 1891 -51 1 1910 -51 1 minecraft:glowstone
fill 1891 -51 29 1910 -51 29 minecraft:glowstone
fill 1891 -51 2 1891 -51 28 minecraft:glowstone
fill 1910 -51 2 1910 -51 28 minecraft:glowstone
fill 1892 -51 2 1909 -51 2 minecraft:glowstone
fill 1892 -51 28 1909 -51 28 minecraft:glowstone
fill 1892 -51 3 1892 -51 27 minecraft:glowstone
fill 1909 -51 3 1909 -51 27 minecraft:glowstone
fill 1893 -51 3 1908 -51 3 minecraft:glowstone
fill 1893 -51 27 1908 -51 27 minecraft:glowstone
fill 1893 -51 4 1893 -51 26 minecraft:glowstone
fill 1908 -51 4 1908 -51 26 minecraft:glowstone
fill 1898 -51 13 1902 -51 17 minecraft:glowstone
fill 1890 -61 0 1911 -58 30 minecraft:white_concrete
fill 1890 -61 0 1911 -58 11 minecraft:white_concrete
fill 1890 -61 18 1911 -58 30 minecraft:white_concrete
fill 1891 -61 12 1910 -58 17 minecraft:air
fill 1890 -61 0 1911 -61 30 minecraft:black_concrete
fill 1899 -58 12 1901 -58 17 minecraft:air
fill 1899 -57 19 1901 -57 19 minecraft:gold_block
setblock 1900 -57 7 minecraft:spruce_pressure_plate
setblock 1900 -57 8 minecraft:spruce_pressure_plate
setblock 1900 -57 9 minecraft:spruce_pressure_plate
setblock 1901 -57 7 minecraft:spruce_pressure_plate
setblock 1901 -57 8 minecraft:spruce_pressure_plate
setblock 1901 -57 9 minecraft:spruce_pressure_plate
setblock 1902 -57 7 minecraft:spruce_pressure_plate
setblock 1902 -57 8 minecraft:spruce_pressure_plate
setblock 1902 -57 9 minecraft:spruce_pressure_plate
setblock 1892 -57 6 minecraft:crafting_table
setblock 1892 -57 10 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1892 -57 7 minecraft:stone_slab[type=bottom]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_04/place_command_blocks
