# Scene: tier_path_easy_11
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 11 of 15 with 3-5 decorations.
fill 1200 -58 0 1222 -58 31 minecraft:white_concrete
fill 1200 -57 0 1222 -52 31 minecraft:white_concrete
fill 1199 -57 0 1199 -52 31 minecraft:white_concrete
fill 1223 -57 0 1223 -52 31 minecraft:white_concrete
fill 1199 -57 -1 1223 -52 -1 minecraft:white_concrete
fill 1199 -57 32 1223 -52 32 minecraft:white_concrete
fill 1201 -57 1 1221 -52 30 minecraft:air
fill 1200 -51 0 1222 -51 31 minecraft:white_concrete
fill 1201 -51 1 1221 -51 1 minecraft:glowstone
fill 1201 -51 30 1221 -51 30 minecraft:glowstone
fill 1201 -51 2 1201 -51 29 minecraft:glowstone
fill 1221 -51 2 1221 -51 29 minecraft:glowstone
fill 1202 -51 2 1220 -51 2 minecraft:glowstone
fill 1202 -51 29 1220 -51 29 minecraft:glowstone
fill 1202 -51 3 1202 -51 28 minecraft:glowstone
fill 1220 -51 3 1220 -51 28 minecraft:glowstone
fill 1203 -51 3 1219 -51 3 minecraft:glowstone
fill 1203 -51 28 1219 -51 28 minecraft:glowstone
fill 1203 -51 4 1203 -51 27 minecraft:glowstone
fill 1219 -51 4 1219 -51 27 minecraft:glowstone
fill 1209 -51 13 1213 -51 17 minecraft:glowstone
fill 1200 -61 0 1222 -58 31 minecraft:white_concrete
fill 1200 -61 0 1222 -58 13 minecraft:white_concrete
fill 1200 -61 18 1222 -58 31 minecraft:white_concrete
fill 1201 -61 14 1221 -58 17 minecraft:air
fill 1200 -61 0 1222 -61 31 minecraft:black_concrete
fill 1209 -58 14 1212 -58 17 minecraft:air
fill 1209 -57 19 1212 -57 19 minecraft:gold_block
setblock 1210 -57 9 minecraft:stone_pressure_plate
setblock 1210 -57 10 minecraft:stone_pressure_plate
setblock 1210 -57 11 minecraft:stone_pressure_plate
setblock 1210 -57 12 minecraft:stone_pressure_plate
setblock 1211 -57 9 minecraft:stone_pressure_plate
setblock 1211 -57 10 minecraft:stone_pressure_plate
setblock 1211 -57 11 minecraft:stone_pressure_plate
setblock 1211 -57 12 minecraft:stone_pressure_plate
setblock 1212 -57 9 minecraft:stone_pressure_plate
setblock 1212 -57 10 minecraft:stone_pressure_plate
setblock 1212 -57 11 minecraft:stone_pressure_plate
setblock 1212 -57 12 minecraft:stone_pressure_plate
setblock 1213 -57 9 minecraft:stone_pressure_plate
setblock 1213 -57 10 minecraft:stone_pressure_plate
setblock 1213 -57 11 minecraft:stone_pressure_plate
setblock 1213 -57 12 minecraft:stone_pressure_plate
setblock 1202 -57 7 minecraft:chest
setblock 1202 -57 4 minecraft:furnace
setblock 1202 -57 11 minecraft:chest

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_easy_11/place_command_blocks
