# Scene: tier_path_medium_09
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 9 of 15 with 3-5 decorations.
fill 1591 -58 0 1611 -58 31 minecraft:white_concrete
fill 1591 -57 0 1611 -52 31 minecraft:white_concrete
fill 1590 -57 0 1590 -52 31 minecraft:white_concrete
fill 1612 -57 0 1612 -52 31 minecraft:white_concrete
fill 1590 -57 -1 1612 -52 -1 minecraft:white_concrete
fill 1590 -57 32 1612 -52 32 minecraft:white_concrete
fill 1592 -57 1 1610 -52 30 minecraft:air
fill 1591 -51 0 1611 -51 31 minecraft:white_concrete
fill 1592 -51 1 1610 -51 1 minecraft:glowstone
fill 1592 -51 30 1610 -51 30 minecraft:glowstone
fill 1592 -51 2 1592 -51 29 minecraft:glowstone
fill 1610 -51 2 1610 -51 29 minecraft:glowstone
fill 1593 -51 2 1609 -51 2 minecraft:glowstone
fill 1593 -51 29 1609 -51 29 minecraft:glowstone
fill 1593 -51 3 1593 -51 28 minecraft:glowstone
fill 1609 -51 3 1609 -51 28 minecraft:glowstone
fill 1594 -51 3 1608 -51 3 minecraft:glowstone
fill 1594 -51 28 1608 -51 28 minecraft:glowstone
fill 1594 -51 4 1594 -51 27 minecraft:glowstone
fill 1608 -51 4 1608 -51 27 minecraft:glowstone
fill 1599 -51 13 1603 -51 17 minecraft:glowstone
fill 1591 -61 0 1611 -58 31 minecraft:white_concrete
fill 1591 -61 0 1611 -58 12 minecraft:white_concrete
fill 1591 -61 18 1611 -58 31 minecraft:white_concrete
fill 1592 -61 13 1610 -58 17 minecraft:air
fill 1591 -61 0 1611 -61 31 minecraft:black_concrete
fill 1600 -58 13 1602 -58 17 minecraft:air
fill 1600 -57 19 1602 -57 19 minecraft:gold_block
setblock 1600 -57 8 minecraft:mangrove_pressure_plate
setblock 1600 -57 9 minecraft:mangrove_pressure_plate
setblock 1600 -57 10 minecraft:mangrove_pressure_plate
setblock 1601 -57 8 minecraft:mangrove_pressure_plate
setblock 1601 -57 9 minecraft:mangrove_pressure_plate
setblock 1601 -57 10 minecraft:mangrove_pressure_plate
setblock 1602 -57 8 minecraft:mangrove_pressure_plate
setblock 1602 -57 9 minecraft:mangrove_pressure_plate
setblock 1602 -57 10 minecraft:mangrove_pressure_plate
setblock 1597 -57 2 minecraft:furnace
setblock 1593 -57 7 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1599 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1593 -57 10 minecraft:stone_slab[type=bottom]
setblock 1593 -57 11 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_09/place_command_blocks
