# Scene: tier_path_hard_08
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 8 of 15 with 3-5 decorations.
fill 2010 -58 0 2032 -58 30 minecraft:white_concrete
fill 2010 -57 0 2032 -52 30 minecraft:white_concrete
fill 2009 -57 0 2009 -52 30 minecraft:white_concrete
fill 2033 -57 0 2033 -52 30 minecraft:white_concrete
fill 2009 -57 -1 2033 -52 -1 minecraft:white_concrete
fill 2009 -57 31 2033 -52 31 minecraft:white_concrete
fill 2011 -57 1 2031 -52 29 minecraft:air
fill 2010 -51 0 2032 -51 30 minecraft:white_concrete
fill 2011 -51 1 2031 -51 1 minecraft:glowstone
fill 2011 -51 29 2031 -51 29 minecraft:glowstone
fill 2011 -51 2 2011 -51 28 minecraft:glowstone
fill 2031 -51 2 2031 -51 28 minecraft:glowstone
fill 2012 -51 2 2030 -51 2 minecraft:glowstone
fill 2012 -51 28 2030 -51 28 minecraft:glowstone
fill 2012 -51 3 2012 -51 27 minecraft:glowstone
fill 2030 -51 3 2030 -51 27 minecraft:glowstone
fill 2013 -51 3 2029 -51 3 minecraft:glowstone
fill 2013 -51 27 2029 -51 27 minecraft:glowstone
fill 2013 -51 4 2013 -51 26 minecraft:glowstone
fill 2029 -51 4 2029 -51 26 minecraft:glowstone
fill 2019 -51 13 2023 -51 17 minecraft:glowstone
fill 2010 -61 0 2032 -58 30 minecraft:white_concrete
fill 2010 -61 0 2032 -58 11 minecraft:white_concrete
fill 2010 -61 18 2032 -58 30 minecraft:white_concrete
fill 2011 -61 12 2031 -58 17 minecraft:air
fill 2010 -61 0 2032 -61 30 minecraft:black_concrete
fill 2020 -58 12 2022 -58 17 minecraft:air
fill 2020 -57 19 2022 -57 19 minecraft:gold_block
setblock 2020 -57 7 minecraft:dark_oak_pressure_plate
setblock 2020 -57 8 minecraft:dark_oak_pressure_plate
setblock 2020 -57 9 minecraft:dark_oak_pressure_plate
setblock 2021 -57 7 minecraft:dark_oak_pressure_plate
setblock 2021 -57 8 minecraft:dark_oak_pressure_plate
setblock 2021 -57 9 minecraft:dark_oak_pressure_plate
setblock 2022 -57 7 minecraft:dark_oak_pressure_plate
setblock 2022 -57 8 minecraft:dark_oak_pressure_plate
setblock 2022 -57 9 minecraft:dark_oak_pressure_plate
setblock 2030 -57 5 minecraft:stone_slab[type=bottom]
setblock 2015 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2012 -57 4 minecraft:furnace

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_08/place_command_blocks
