# Scene: tier_elevator_medium_01
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 1 of 15 with 3-5 decorations.
fill 450 -59 0 471 -59 23 minecraft:white_concrete
fill 450 -58 0 471 -53 23 minecraft:white_concrete
fill 449 -58 0 449 -53 23 minecraft:white_concrete
fill 472 -58 0 472 -53 23 minecraft:white_concrete
fill 449 -58 -1 472 -53 -1 minecraft:white_concrete
fill 449 -58 24 472 -53 24 minecraft:white_concrete
fill 451 -58 1 470 -53 22 minecraft:air
fill 450 -52 0 471 -52 23 minecraft:white_concrete
fill 451 -52 1 470 -52 1 minecraft:glowstone
fill 451 -52 22 470 -52 22 minecraft:glowstone
fill 451 -52 2 451 -52 21 minecraft:glowstone
fill 470 -52 2 470 -52 21 minecraft:glowstone
fill 452 -52 2 469 -52 2 minecraft:glowstone
fill 452 -52 21 469 -52 21 minecraft:glowstone
fill 452 -52 3 452 -52 20 minecraft:glowstone
fill 469 -52 3 469 -52 20 minecraft:glowstone
fill 453 -52 3 468 -52 3 minecraft:glowstone
fill 453 -52 20 468 -52 20 minecraft:glowstone
fill 453 -52 4 453 -52 19 minecraft:glowstone
fill 468 -52 4 468 -52 19 minecraft:glowstone
fill 458 -52 9 462 -52 13 minecraft:glowstone
fill 451 -58 12 470 -53 12 minecraft:white_concrete
fill 460 -58 12 461 -56 12 minecraft:light_gray_concrete
setblock 460 -58 7 minecraft:stone_pressure_plate
setblock 460 -58 8 minecraft:stone_pressure_plate
setblock 460 -58 9 minecraft:stone_pressure_plate
setblock 461 -58 7 minecraft:stone_pressure_plate
setblock 461 -58 8 minecraft:stone_pressure_plate
setblock 461 -58 9 minecraft:stone_pressure_plate
setblock 462 -58 7 minecraft:stone_pressure_plate
setblock 462 -58 8 minecraft:stone_pressure_plate
setblock 462 -58 9 minecraft:stone_pressure_plate
setblock 459 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 469 -58 9 minecraft:bookshelf
setblock 452 -58 10 minecraft:bookshelf
setblock 461 -58 2 minecraft:bookshelf
setblock 452 -58 8 minecraft:bookshelf

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_01/place_command_blocks
