# Scene: tier_elevator_easy_15
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 15 of 15 with 3-5 decorations.
fill 421 -59 0 441 -59 23 minecraft:white_concrete
fill 421 -58 0 441 -53 23 minecraft:white_concrete
fill 420 -58 0 420 -53 23 minecraft:white_concrete
fill 442 -58 0 442 -53 23 minecraft:white_concrete
fill 420 -58 -1 442 -53 -1 minecraft:white_concrete
fill 420 -58 24 442 -53 24 minecraft:white_concrete
fill 422 -58 1 440 -53 22 minecraft:air
fill 421 -52 0 441 -52 23 minecraft:white_concrete
fill 422 -52 1 440 -52 1 minecraft:glowstone
fill 422 -52 22 440 -52 22 minecraft:glowstone
fill 422 -52 2 422 -52 21 minecraft:glowstone
fill 440 -52 2 440 -52 21 minecraft:glowstone
fill 423 -52 2 439 -52 2 minecraft:glowstone
fill 423 -52 21 439 -52 21 minecraft:glowstone
fill 423 -52 3 423 -52 20 minecraft:glowstone
fill 439 -52 3 439 -52 20 minecraft:glowstone
fill 424 -52 3 438 -52 3 minecraft:glowstone
fill 424 -52 20 438 -52 20 minecraft:glowstone
fill 424 -52 4 424 -52 19 minecraft:glowstone
fill 438 -52 4 438 -52 19 minecraft:glowstone
fill 429 -52 9 433 -52 13 minecraft:glowstone
fill 422 -58 12 440 -53 12 minecraft:white_concrete
fill 429 -58 12 431 -56 12 minecraft:light_blue_concrete
setblock 428 -58 7 minecraft:stone_pressure_plate
setblock 428 -58 8 minecraft:stone_pressure_plate
setblock 428 -58 9 minecraft:stone_pressure_plate
setblock 428 -58 10 minecraft:stone_pressure_plate
setblock 429 -58 7 minecraft:stone_pressure_plate
setblock 429 -58 8 minecraft:stone_pressure_plate
setblock 429 -58 9 minecraft:stone_pressure_plate
setblock 429 -58 10 minecraft:stone_pressure_plate
setblock 430 -58 7 minecraft:stone_pressure_plate
setblock 430 -58 8 minecraft:stone_pressure_plate
setblock 430 -58 9 minecraft:stone_pressure_plate
setblock 430 -58 10 minecraft:stone_pressure_plate
setblock 431 -58 7 minecraft:stone_pressure_plate
setblock 431 -58 8 minecraft:stone_pressure_plate
setblock 431 -58 9 minecraft:stone_pressure_plate
setblock 431 -58 10 minecraft:stone_pressure_plate
setblock 438 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 439 -58 6 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 427 -58 2 minecraft:stone_slab[type=bottom]
setblock 439 -58 5 minecraft:furnace
setblock 439 -58 7 minecraft:crafting_table

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_easy_15/place_command_blocks
