# Scene: truck_medium_07
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2462 -58 0 2485 -58 22 minecraft:white_concrete
fill 2462 -57 0 2485 -52 22 minecraft:white_concrete
fill 2461 -57 0 2461 -52 22 minecraft:white_concrete
fill 2486 -57 0 2486 -52 22 minecraft:white_concrete
fill 2461 -57 -1 2486 -52 -1 minecraft:white_concrete
fill 2461 -57 23 2486 -52 23 minecraft:white_concrete
fill 2463 -57 1 2484 -52 21 minecraft:air
fill 2462 -51 0 2485 -51 22 minecraft:white_concrete
fill 2463 -51 1 2484 -51 1 minecraft:glowstone
fill 2463 -51 21 2484 -51 21 minecraft:glowstone
fill 2463 -51 2 2463 -51 20 minecraft:glowstone
fill 2484 -51 2 2484 -51 20 minecraft:glowstone
fill 2464 -51 2 2483 -51 2 minecraft:glowstone
fill 2464 -51 20 2483 -51 20 minecraft:glowstone
fill 2464 -51 3 2464 -51 19 minecraft:glowstone
fill 2483 -51 3 2483 -51 19 minecraft:glowstone
fill 2465 -51 3 2482 -51 3 minecraft:glowstone
fill 2465 -51 19 2482 -51 19 minecraft:glowstone
fill 2465 -51 4 2465 -51 18 minecraft:glowstone
fill 2482 -51 4 2482 -51 18 minecraft:glowstone
fill 2471 -51 9 2475 -51 13 minecraft:glowstone
fill 2473 -58 10 2475 -58 12 minecraft:light_blue_concrete
setblock 2464 -57 17 minecraft:bookshelf
setblock 2483 -57 20 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2464 -57 12 minecraft:furnace
setblock 2464 -57 15 minecraft:furnace
setblock 2483 -57 19 minecraft:crafting_table
setblock 2464 -57 8 minecraft:chest
setblock 2483 -57 12 minecraft:bookshelf
setblock 2483 -57 7 minecraft:chest
setblock 2483 -57 5 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2464 -57 9 minecraft:crafting_table
setblock 2464 -57 14 minecraft:chest
setblock 2464 -57 7 minecraft:crafting_table
setblock 2483 -57 6 minecraft:bookshelf
setblock 2464 -57 4 minecraft:crafting_table
