# Scene: truck_medium_05
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2399 -58 0 2422 -58 22 minecraft:white_concrete
fill 2399 -57 0 2422 -52 22 minecraft:white_concrete
fill 2398 -57 0 2398 -52 22 minecraft:white_concrete
fill 2423 -57 0 2423 -52 22 minecraft:white_concrete
fill 2398 -57 -1 2423 -52 -1 minecraft:white_concrete
fill 2398 -57 23 2423 -52 23 minecraft:white_concrete
fill 2400 -57 1 2421 -52 21 minecraft:air
fill 2399 -51 0 2422 -51 22 minecraft:white_concrete
fill 2400 -51 1 2421 -51 1 minecraft:glowstone
fill 2400 -51 21 2421 -51 21 minecraft:glowstone
fill 2400 -51 2 2400 -51 20 minecraft:glowstone
fill 2421 -51 2 2421 -51 20 minecraft:glowstone
fill 2401 -51 2 2420 -51 2 minecraft:glowstone
fill 2401 -51 20 2420 -51 20 minecraft:glowstone
fill 2401 -51 3 2401 -51 19 minecraft:glowstone
fill 2420 -51 3 2420 -51 19 minecraft:glowstone
fill 2402 -51 3 2419 -51 3 minecraft:glowstone
fill 2402 -51 19 2419 -51 19 minecraft:glowstone
fill 2402 -51 4 2402 -51 18 minecraft:glowstone
fill 2419 -51 4 2419 -51 18 minecraft:glowstone
fill 2408 -51 9 2412 -51 13 minecraft:glowstone
fill 2410 -58 10 2412 -58 12 minecraft:green_concrete
setblock 2420 -57 5 minecraft:bookshelf
setblock 2401 -57 8 minecraft:stone_slab[type=bottom]
setblock 2420 -57 11 minecraft:stone_slab[type=bottom]
setblock 2401 -57 13 minecraft:bookshelf
setblock 2401 -57 17 minecraft:stone_slab[type=bottom]
setblock 2401 -57 18 minecraft:stone_slab[type=bottom]
setblock 2401 -57 11 minecraft:chest
setblock 2401 -57 6 minecraft:furnace
setblock 2420 -57 12 minecraft:crafting_table
setblock 2401 -57 20 minecraft:bookshelf
setblock 2401 -57 16 minecraft:bookshelf
setblock 2401 -57 3 minecraft:furnace
setblock 2420 -57 20 minecraft:stone_slab[type=bottom]
