# Scene: tier_elevator_medium_11
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 11 of 15 with 3-5 decorations.
fill 750 -59 0 772 -59 23 minecraft:white_concrete
fill 750 -58 0 772 -53 23 minecraft:white_concrete
fill 749 -58 0 749 -53 23 minecraft:white_concrete
fill 773 -58 0 773 -53 23 minecraft:white_concrete
fill 749 -58 -1 773 -53 -1 minecraft:white_concrete
fill 749 -58 24 773 -53 24 minecraft:white_concrete
fill 751 -58 1 771 -53 22 minecraft:air
fill 750 -52 0 772 -52 23 minecraft:white_concrete
fill 751 -52 1 771 -52 1 minecraft:glowstone
fill 751 -52 22 771 -52 22 minecraft:glowstone
fill 751 -52 2 751 -52 21 minecraft:glowstone
fill 771 -52 2 771 -52 21 minecraft:glowstone
fill 752 -52 2 770 -52 2 minecraft:glowstone
fill 752 -52 21 770 -52 21 minecraft:glowstone
fill 752 -52 3 752 -52 20 minecraft:glowstone
fill 770 -52 3 770 -52 20 minecraft:glowstone
fill 753 -52 3 769 -52 3 minecraft:glowstone
fill 753 -52 20 769 -52 20 minecraft:glowstone
fill 753 -52 4 753 -52 19 minecraft:glowstone
fill 769 -52 4 769 -52 19 minecraft:glowstone
fill 759 -52 9 763 -52 13 minecraft:glowstone
fill 751 -58 12 771 -53 12 minecraft:white_concrete
fill 761 -58 12 762 -56 12 minecraft:light_gray_concrete
setblock 760 -58 7 minecraft:oak_pressure_plate
setblock 760 -58 8 minecraft:oak_pressure_plate
setblock 760 -58 9 minecraft:oak_pressure_plate
setblock 761 -58 7 minecraft:oak_pressure_plate
setblock 761 -58 8 minecraft:oak_pressure_plate
setblock 761 -58 9 minecraft:oak_pressure_plate
setblock 762 -58 7 minecraft:oak_pressure_plate
setblock 762 -58 8 minecraft:oak_pressure_plate
setblock 762 -58 9 minecraft:oak_pressure_plate
setblock 761 -58 2 minecraft:crafting_table
setblock 768 -58 2 minecraft:chest
setblock 770 -58 6 minecraft:chest

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_11/place_command_blocks
