# Scene: picture_hard_04
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3625 -58 0 3641 -58 18 minecraft:white_concrete
fill 3625 -57 0 3641 -49 18 minecraft:white_concrete
fill 3624 -57 0 3624 -49 18 minecraft:white_concrete
fill 3642 -57 0 3642 -49 18 minecraft:white_concrete
fill 3624 -57 -1 3642 -49 -1 minecraft:white_concrete
fill 3624 -57 19 3642 -49 19 minecraft:white_concrete
fill 3626 -57 1 3640 -49 17 minecraft:air
fill 3625 -48 0 3641 -48 18 minecraft:white_concrete
fill 3626 -48 1 3640 -48 1 minecraft:glowstone
fill 3626 -48 17 3640 -48 17 minecraft:glowstone
fill 3626 -48 2 3626 -48 16 minecraft:glowstone
fill 3640 -48 2 3640 -48 16 minecraft:glowstone
fill 3627 -48 2 3639 -48 2 minecraft:glowstone
fill 3627 -48 16 3639 -48 16 minecraft:glowstone
fill 3627 -48 3 3627 -48 15 minecraft:glowstone
fill 3639 -48 3 3639 -48 15 minecraft:glowstone
fill 3628 -48 3 3638 -48 3 minecraft:glowstone
fill 3628 -48 15 3638 -48 15 minecraft:glowstone
fill 3628 -48 4 3628 -48 14 minecraft:glowstone
fill 3638 -48 4 3638 -48 14 minecraft:glowstone
fill 3631 -48 7 3635 -48 11 minecraft:glowstone
fill 3626 -53 1 3640 -53 5 minecraft:glowstone
fill 3626 -52 1 3640 -52 5 minecraft:smooth_stone
fill 3626 -51 6 3640 -51 6 minecraft:oak_fence
fill 3633 -57 1 3635 -57 3 minecraft:lime_concrete
fill 3633 -52 10 3633 -52 10 minecraft:smooth_stone
setblock 3631 -51 4 minecraft:stone_slab[type=bottom]
setblock 3636 -51 2 minecraft:crafting_table
setblock 3635 -51 5 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3627 -51 2 minecraft:chest
setblock 3632 -51 1 minecraft:chest
setblock 3638 -51 1 minecraft:furnace
