# Scene: tier_elevator_medium_13
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 13 of 15 with 3-5 decorations.
fill 810 -59 0 831 -59 23 minecraft:white_concrete
fill 810 -58 0 831 -53 23 minecraft:white_concrete
fill 809 -58 0 809 -53 23 minecraft:white_concrete
fill 832 -58 0 832 -53 23 minecraft:white_concrete
fill 809 -58 -1 832 -53 -1 minecraft:white_concrete
fill 809 -58 24 832 -53 24 minecraft:white_concrete
fill 811 -58 1 830 -53 22 minecraft:air
fill 810 -52 0 831 -52 23 minecraft:white_concrete
fill 811 -52 1 830 -52 1 minecraft:glowstone
fill 811 -52 22 830 -52 22 minecraft:glowstone
fill 811 -52 2 811 -52 21 minecraft:glowstone
fill 830 -52 2 830 -52 21 minecraft:glowstone
fill 812 -52 2 829 -52 2 minecraft:glowstone
fill 812 -52 21 829 -52 21 minecraft:glowstone
fill 812 -52 3 812 -52 20 minecraft:glowstone
fill 829 -52 3 829 -52 20 minecraft:glowstone
fill 813 -52 3 828 -52 3 minecraft:glowstone
fill 813 -52 20 828 -52 20 minecraft:glowstone
fill 813 -52 4 813 -52 19 minecraft:glowstone
fill 828 -52 4 828 -52 19 minecraft:glowstone
fill 818 -52 9 822 -52 13 minecraft:glowstone
fill 811 -58 12 830 -53 12 minecraft:white_concrete
fill 820 -58 12 821 -56 12 minecraft:black_concrete
setblock 819 -58 7 minecraft:acacia_pressure_plate
setblock 819 -58 8 minecraft:acacia_pressure_plate
setblock 819 -58 9 minecraft:acacia_pressure_plate
setblock 820 -58 7 minecraft:acacia_pressure_plate
setblock 820 -58 8 minecraft:acacia_pressure_plate
setblock 820 -58 9 minecraft:acacia_pressure_plate
setblock 821 -58 7 minecraft:acacia_pressure_plate
setblock 821 -58 8 minecraft:acacia_pressure_plate
setblock 821 -58 9 minecraft:acacia_pressure_plate
setblock 829 -58 6 minecraft:crafting_table
setblock 818 -58 2 minecraft:furnace
setblock 829 -58 8 minecraft:chest
setblock 813 -58 2 minecraft:bookshelf

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_13/place_command_blocks
