# Scene: tier_elevator_hard_11
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 11 of 15 with 3-5 decorations.
fill 1200 -59 0 1222 -59 23 minecraft:white_concrete
fill 1200 -58 0 1222 -53 23 minecraft:white_concrete
fill 1199 -58 0 1199 -53 23 minecraft:white_concrete
fill 1223 -58 0 1223 -53 23 minecraft:white_concrete
fill 1199 -58 -1 1223 -53 -1 minecraft:white_concrete
fill 1199 -58 24 1223 -53 24 minecraft:white_concrete
fill 1201 -58 1 1221 -53 22 minecraft:air
fill 1200 -52 0 1222 -52 23 minecraft:white_concrete
fill 1201 -52 1 1221 -52 1 minecraft:glowstone
fill 1201 -52 22 1221 -52 22 minecraft:glowstone
fill 1201 -52 2 1201 -52 21 minecraft:glowstone
fill 1221 -52 2 1221 -52 21 minecraft:glowstone
fill 1202 -52 2 1220 -52 2 minecraft:glowstone
fill 1202 -52 21 1220 -52 21 minecraft:glowstone
fill 1202 -52 3 1202 -52 20 minecraft:glowstone
fill 1220 -52 3 1220 -52 20 minecraft:glowstone
fill 1203 -52 3 1219 -52 3 minecraft:glowstone
fill 1203 -52 20 1219 -52 20 minecraft:glowstone
fill 1203 -52 4 1203 -52 19 minecraft:glowstone
fill 1219 -52 4 1219 -52 19 minecraft:glowstone
fill 1209 -52 9 1213 -52 13 minecraft:glowstone
fill 1201 -58 12 1221 -53 12 minecraft:white_concrete
fill 1211 -58 12 1212 -56 12 minecraft:light_gray_concrete
setblock 1210 -58 6 minecraft:oak_pressure_plate
setblock 1210 -58 7 minecraft:oak_pressure_plate
setblock 1210 -58 8 minecraft:oak_pressure_plate
setblock 1211 -58 6 minecraft:oak_pressure_plate
setblock 1211 -58 7 minecraft:oak_pressure_plate
setblock 1211 -58 8 minecraft:oak_pressure_plate
setblock 1212 -58 6 minecraft:oak_pressure_plate
setblock 1212 -58 7 minecraft:oak_pressure_plate
setblock 1212 -58 8 minecraft:oak_pressure_plate
setblock 1202 -58 10 minecraft:chest
setblock 1219 -58 2 minecraft:stone_slab[type=bottom]
setblock 1207 -58 2 minecraft:stone_slab[type=bottom]
setblock 1202 -58 4 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_11/place_command_blocks
