# Scene: truck_hard_15
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3187 -58 0 3210 -58 22 minecraft:white_concrete
fill 3187 -57 0 3210 -52 22 minecraft:white_concrete
fill 3186 -57 0 3186 -52 22 minecraft:white_concrete
fill 3211 -57 0 3211 -52 22 minecraft:white_concrete
fill 3186 -57 -1 3211 -52 -1 minecraft:white_concrete
fill 3186 -57 23 3211 -52 23 minecraft:white_concrete
fill 3188 -57 1 3209 -52 21 minecraft:air
fill 3187 -51 0 3210 -51 22 minecraft:white_concrete
fill 3188 -51 1 3209 -51 1 minecraft:glowstone
fill 3188 -51 21 3209 -51 21 minecraft:glowstone
fill 3188 -51 2 3188 -51 20 minecraft:glowstone
fill 3209 -51 2 3209 -51 20 minecraft:glowstone
fill 3189 -51 2 3208 -51 2 minecraft:glowstone
fill 3189 -51 20 3208 -51 20 minecraft:glowstone
fill 3189 -51 3 3189 -51 19 minecraft:glowstone
fill 3208 -51 3 3208 -51 19 minecraft:glowstone
fill 3190 -51 3 3207 -51 3 minecraft:glowstone
fill 3190 -51 19 3207 -51 19 minecraft:glowstone
fill 3190 -51 4 3190 -51 18 minecraft:glowstone
fill 3207 -51 4 3207 -51 18 minecraft:glowstone
fill 3196 -51 9 3200 -51 13 minecraft:glowstone
fill 3199 -58 11 3200 -58 12 minecraft:green_concrete
setblock 3189 -57 19 minecraft:crafting_table
setblock 3189 -57 20 minecraft:chest
setblock 3208 -57 3 minecraft:furnace
setblock 3208 -57 14 minecraft:stone_slab[type=bottom]
setblock 3189 -57 16 minecraft:stone_slab[type=bottom]
setblock 3208 -57 8 minecraft:furnace
setblock 3189 -57 9 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3208 -57 13 minecraft:stone_slab[type=bottom]
setblock 3208 -57 2 minecraft:furnace
setblock 3189 -57 18 minecraft:bookshelf
setblock 3189 -57 4 minecraft:furnace
setblock 3208 -57 4 minecraft:furnace
setblock 3189 -57 14 minecraft:crafting_table
setblock 3208 -57 7 minecraft:chest
