# Scene: truck_medium_10
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2557 -58 0 2579 -58 23 minecraft:white_concrete
fill 2557 -57 0 2579 -52 23 minecraft:white_concrete
fill 2556 -57 0 2556 -52 23 minecraft:white_concrete
fill 2580 -57 0 2580 -52 23 minecraft:white_concrete
fill 2556 -57 -1 2580 -52 -1 minecraft:white_concrete
fill 2556 -57 24 2580 -52 24 minecraft:white_concrete
fill 2558 -57 1 2578 -52 22 minecraft:air
fill 2557 -51 0 2579 -51 23 minecraft:white_concrete
fill 2558 -51 1 2578 -51 1 minecraft:glowstone
fill 2558 -51 22 2578 -51 22 minecraft:glowstone
fill 2558 -51 2 2558 -51 21 minecraft:glowstone
fill 2578 -51 2 2578 -51 21 minecraft:glowstone
fill 2559 -51 2 2577 -51 2 minecraft:glowstone
fill 2559 -51 21 2577 -51 21 minecraft:glowstone
fill 2559 -51 3 2559 -51 20 minecraft:glowstone
fill 2577 -51 3 2577 -51 20 minecraft:glowstone
fill 2560 -51 3 2576 -51 3 minecraft:glowstone
fill 2560 -51 20 2576 -51 20 minecraft:glowstone
fill 2560 -51 4 2560 -51 19 minecraft:glowstone
fill 2576 -51 4 2576 -51 19 minecraft:glowstone
fill 2566 -51 9 2570 -51 13 minecraft:glowstone
fill 2567 -58 11 2569 -58 13 minecraft:magenta_concrete
setblock 2559 -57 20 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2559 -57 3 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2559 -57 15 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2577 -57 16 minecraft:chest
setblock 2559 -57 2 minecraft:chest
setblock 2559 -57 14 minecraft:crafting_table
setblock 2577 -57 17 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2577 -57 18 minecraft:stone_slab[type=bottom]
setblock 2577 -57 11 minecraft:stone_slab[type=bottom]
setblock 2559 -57 4 minecraft:stone_slab[type=bottom]
setblock 2577 -57 4 minecraft:stone_slab[type=bottom]
setblock 2559 -57 16 minecraft:furnace
setblock 2577 -57 14 minecraft:furnace
setblock 2559 -57 17 minecraft:stone_slab[type=bottom]
