# Scene: tier_elevator_hard_09
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 9 of 15 with 3-5 decorations.
fill 1141 -59 0 1161 -59 23 minecraft:white_concrete
fill 1141 -58 0 1161 -53 23 minecraft:white_concrete
fill 1140 -58 0 1140 -53 23 minecraft:white_concrete
fill 1162 -58 0 1162 -53 23 minecraft:white_concrete
fill 1140 -58 -1 1162 -53 -1 minecraft:white_concrete
fill 1140 -58 24 1162 -53 24 minecraft:white_concrete
fill 1142 -58 1 1160 -53 22 minecraft:air
fill 1141 -52 0 1161 -52 23 minecraft:white_concrete
fill 1142 -52 1 1160 -52 1 minecraft:glowstone
fill 1142 -52 22 1160 -52 22 minecraft:glowstone
fill 1142 -52 2 1142 -52 21 minecraft:glowstone
fill 1160 -52 2 1160 -52 21 minecraft:glowstone
fill 1143 -52 2 1159 -52 2 minecraft:glowstone
fill 1143 -52 21 1159 -52 21 minecraft:glowstone
fill 1143 -52 3 1143 -52 20 minecraft:glowstone
fill 1159 -52 3 1159 -52 20 minecraft:glowstone
fill 1144 -52 3 1158 -52 3 minecraft:glowstone
fill 1144 -52 20 1158 -52 20 minecraft:glowstone
fill 1144 -52 4 1144 -52 19 minecraft:glowstone
fill 1158 -52 4 1158 -52 19 minecraft:glowstone
fill 1149 -52 9 1153 -52 13 minecraft:glowstone
fill 1142 -58 12 1160 -53 12 minecraft:white_concrete
fill 1149 -58 12 1150 -56 12 minecraft:brown_concrete
setblock 1151 -58 6 minecraft:dark_oak_pressure_plate
setblock 1151 -58 7 minecraft:dark_oak_pressure_plate
setblock 1151 -58 8 minecraft:dark_oak_pressure_plate
setblock 1152 -58 6 minecraft:dark_oak_pressure_plate
setblock 1152 -58 7 minecraft:dark_oak_pressure_plate
setblock 1152 -58 8 minecraft:dark_oak_pressure_plate
setblock 1153 -58 6 minecraft:dark_oak_pressure_plate
setblock 1153 -58 7 minecraft:dark_oak_pressure_plate
setblock 1153 -58 8 minecraft:dark_oak_pressure_plate
setblock 1143 -58 9 minecraft:furnace
setblock 1159 -58 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1155 -58 2 minecraft:chest

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_09/place_command_blocks
