# Scene: tier_path_medium_06
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 6 of 15 with 3-5 decorations.
fill 1501 -58 0 1521 -58 30 minecraft:white_concrete
fill 1501 -57 0 1521 -52 30 minecraft:white_concrete
fill 1500 -57 0 1500 -52 30 minecraft:white_concrete
fill 1522 -57 0 1522 -52 30 minecraft:white_concrete
fill 1500 -57 -1 1522 -52 -1 minecraft:white_concrete
fill 1500 -57 31 1522 -52 31 minecraft:white_concrete
fill 1502 -57 1 1520 -52 29 minecraft:air
fill 1501 -51 0 1521 -51 30 minecraft:white_concrete
fill 1502 -51 1 1520 -51 1 minecraft:glowstone
fill 1502 -51 29 1520 -51 29 minecraft:glowstone
fill 1502 -51 2 1502 -51 28 minecraft:glowstone
fill 1520 -51 2 1520 -51 28 minecraft:glowstone
fill 1503 -51 2 1519 -51 2 minecraft:glowstone
fill 1503 -51 28 1519 -51 28 minecraft:glowstone
fill 1503 -51 3 1503 -51 27 minecraft:glowstone
fill 1519 -51 3 1519 -51 27 minecraft:glowstone
fill 1504 -51 3 1518 -51 3 minecraft:glowstone
fill 1504 -51 27 1518 -51 27 minecraft:glowstone
fill 1504 -51 4 1504 -51 26 minecraft:glowstone
fill 1518 -51 4 1518 -51 26 minecraft:glowstone
fill 1509 -51 13 1513 -51 17 minecraft:glowstone
fill 1501 -61 0 1521 -58 30 minecraft:white_concrete
fill 1501 -61 0 1521 -58 12 minecraft:white_concrete
fill 1501 -61 18 1521 -58 30 minecraft:white_concrete
fill 1502 -61 13 1520 -58 17 minecraft:air
fill 1501 -61 0 1521 -61 30 minecraft:black_concrete
fill 1510 -58 13 1512 -58 17 minecraft:air
fill 1510 -57 19 1512 -57 19 minecraft:gold_block
setblock 1510 -57 8 minecraft:jungle_pressure_plate
setblock 1510 -57 9 minecraft:jungle_pressure_plate
setblock 1510 -57 10 minecraft:jungle_pressure_plate
setblock 1511 -57 8 minecraft:jungle_pressure_plate
setblock 1511 -57 9 minecraft:jungle_pressure_plate
setblock 1511 -57 10 minecraft:jungle_pressure_plate
setblock 1512 -57 8 minecraft:jungle_pressure_plate
setblock 1512 -57 9 minecraft:jungle_pressure_plate
setblock 1512 -57 10 minecraft:jungle_pressure_plate
setblock 1516 -57 2 minecraft:crafting_table
setblock 1519 -57 3 minecraft:bookshelf
setblock 1503 -57 3 minecraft:bookshelf
setblock 1519 -57 2 minecraft:furnace
setblock 1519 -57 9 minecraft:chest

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_06/place_command_blocks
