# Scene: truck_easy_15
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2241 -58 0 2264 -58 22 minecraft:white_concrete
fill 2241 -57 0 2264 -52 22 minecraft:white_concrete
fill 2240 -57 0 2240 -52 22 minecraft:white_concrete
fill 2265 -57 0 2265 -52 22 minecraft:white_concrete
fill 2240 -57 -1 2265 -52 -1 minecraft:white_concrete
fill 2240 -57 23 2265 -52 23 minecraft:white_concrete
fill 2242 -57 1 2263 -52 21 minecraft:air
fill 2241 -51 0 2264 -51 22 minecraft:white_concrete
fill 2242 -51 1 2263 -51 1 minecraft:glowstone
fill 2242 -51 21 2263 -51 21 minecraft:glowstone
fill 2242 -51 2 2242 -51 20 minecraft:glowstone
fill 2263 -51 2 2263 -51 20 minecraft:glowstone
fill 2243 -51 2 2262 -51 2 minecraft:glowstone
fill 2243 -51 20 2262 -51 20 minecraft:glowstone
fill 2243 -51 3 2243 -51 19 minecraft:glowstone
fill 2262 -51 3 2262 -51 19 minecraft:glowstone
fill 2244 -51 3 2261 -51 3 minecraft:glowstone
fill 2244 -51 19 2261 -51 19 minecraft:glowstone
fill 2244 -51 4 2244 -51 18 minecraft:glowstone
fill 2261 -51 4 2261 -51 18 minecraft:glowstone
fill 2250 -51 9 2254 -51 13 minecraft:glowstone
fill 2252 -58 10 2255 -58 13 minecraft:green_concrete
setblock 2262 -57 16 minecraft:furnace
setblock 2262 -57 12 minecraft:chest
setblock 2262 -57 8 minecraft:crafting_table
setblock 2262 -57 20 minecraft:crafting_table
setblock 2262 -57 17 minecraft:bookshelf
setblock 2243 -57 3 minecraft:chest
setblock 2243 -57 11 minecraft:chest
setblock 2262 -57 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2262 -57 2 minecraft:furnace
setblock 2262 -57 10 minecraft:furnace
setblock 2262 -57 3 minecraft:bookshelf
setblock 2243 -57 12 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2262 -57 15 minecraft:stone_slab[type=bottom]
setblock 2243 -57 19 minecraft:chest
setblock 2243 -57 4 minecraft:crafting_table
