# Scene: tier_path_medium_05
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 5 of 15 with 3-5 decorations.
fill 1470 -58 0 1492 -58 31 minecraft:white_concrete
fill 1470 -57 0 1492 -52 31 minecraft:white_concrete
fill 1469 -57 0 1469 -52 31 minecraft:white_concrete
fill 1493 -57 0 1493 -52 31 minecraft:white_concrete
fill 1469 -57 -1 1493 -52 -1 minecraft:white_concrete
fill 1469 -57 32 1493 -52 32 minecraft:white_concrete
fill 1471 -57 1 1491 -52 30 minecraft:air
fill 1470 -51 0 1492 -51 31 minecraft:white_concrete
fill 1471 -51 1 1491 -51 1 minecraft:glowstone
fill 1471 -51 30 1491 -51 30 minecraft:glowstone
fill 1471 -51 2 1471 -51 29 minecraft:glowstone
fill 1491 -51 2 1491 -51 29 minecraft:glowstone
fill 1472 -51 2 1490 -51 2 minecraft:glowstone
fill 1472 -51 29 1490 -51 29 minecraft:glowstone
fill 1472 -51 3 1472 -51 28 minecraft:glowstone
fill 1490 -51 3 1490 -51 28 minecraft:glowstone
fill 1473 -51 3 1489 -51 3 minecraft:glowstone
fill 1473 -51 28 1489 -51 28 minecraft:glowstone
fill 1473 -51 4 1473 -51 27 minecraft:glowstone
fill 1489 -51 4 1489 -51 27 minecraft:glowstone
fill 1479 -51 13 1483 -51 17 minecraft:glowstone
fill 1470 -61 0 1492 -58 31 minecraft:white_concrete
fill 1470 -61 0 1492 -58 12 minecraft:white_concrete
fill 1470 -61 18 1492 -58 31 minecraft:white_concrete
fill 1471 -61 13 1491 -58 17 minecraft:air
fill 1470 -61 0 1492 -61 31 minecraft:black_concrete
fill 1480 -58 13 1482 -58 17 minecraft:air
fill 1480 -57 19 1482 -57 19 minecraft:gold_block
setblock 1480 -57 8 minecraft:birch_pressure_plate
setblock 1480 -57 9 minecraft:birch_pressure_plate
setblock 1480 -57 10 minecraft:birch_pressure_plate
setblock 1481 -57 8 minecraft:birch_pressure_plate
setblock 1481 -57 9 minecraft:birch_pressure_plate
setblock 1481 -57 10 minecraft:birch_pressure_plate
setblock 1482 -57 8 minecraft:birch_pressure_plate
setblock 1482 -57 9 minecraft:birch_pressure_plate
setblock 1482 -57 10 minecraft:birch_pressure_plate
setblock 1490 -57 6 minecraft:bookshelf
setblock 1490 -57 7 minecraft:furnace
setblock 1490 -57 9 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_05/place_command_blocks
