# Scene: tier_path_medium_07
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 7 of 15 with 3-5 decorations.
fill 1530 -58 0 1551 -58 31 minecraft:white_concrete
fill 1530 -57 0 1551 -52 31 minecraft:white_concrete
fill 1529 -57 0 1529 -52 31 minecraft:white_concrete
fill 1552 -57 0 1552 -52 31 minecraft:white_concrete
fill 1529 -57 -1 1552 -52 -1 minecraft:white_concrete
fill 1529 -57 32 1552 -52 32 minecraft:white_concrete
fill 1531 -57 1 1550 -52 30 minecraft:air
fill 1530 -51 0 1551 -51 31 minecraft:white_concrete
fill 1531 -51 1 1550 -51 1 minecraft:glowstone
fill 1531 -51 30 1550 -51 30 minecraft:glowstone
fill 1531 -51 2 1531 -51 29 minecraft:glowstone
fill 1550 -51 2 1550 -51 29 minecraft:glowstone
fill 1532 -51 2 1549 -51 2 minecraft:glowstone
fill 1532 -51 29 1549 -51 29 minecraft:glowstone
fill 1532 -51 3 1532 -51 28 minecraft:glowstone
fill 1549 -51 3 1549 -51 28 minecraft:glowstone
fill 1533 -51 3 1548 -51 3 minecraft:glowstone
fill 1533 -51 28 1548 -51 28 minecraft:glowstone
fill 1533 -51 4 1533 -51 27 minecraft:glowstone
fill 1548 -51 4 1548 -51 27 minecraft:glowstone
fill 1538 -51 13 1542 -51 17 minecraft:glowstone
fill 1530 -61 0 1551 -58 31 minecraft:white_concrete
fill 1530 -61 0 1551 -58 12 minecraft:white_concrete
fill 1530 -61 18 1551 -58 31 minecraft:white_concrete
fill 1531 -61 13 1550 -58 17 minecraft:air
fill 1530 -61 0 1551 -61 31 minecraft:black_concrete
fill 1539 -58 13 1541 -58 17 minecraft:air
fill 1539 -57 19 1541 -57 19 minecraft:gold_block
setblock 1540 -57 8 minecraft:acacia_pressure_plate
setblock 1540 -57 9 minecraft:acacia_pressure_plate
setblock 1540 -57 10 minecraft:acacia_pressure_plate
setblock 1541 -57 8 minecraft:acacia_pressure_plate
setblock 1541 -57 9 minecraft:acacia_pressure_plate
setblock 1541 -57 10 minecraft:acacia_pressure_plate
setblock 1542 -57 8 minecraft:acacia_pressure_plate
setblock 1542 -57 9 minecraft:acacia_pressure_plate
setblock 1542 -57 10 minecraft:acacia_pressure_plate
setblock 1538 -57 2 minecraft:chest
setblock 1549 -57 7 minecraft:bookshelf
setblock 1549 -57 6 minecraft:furnace
setblock 1537 -57 2 minecraft:stone_slab[type=bottom]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_07/place_command_blocks
