# Scene: picture_hard_10
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3775 -58 0 3791 -58 18 minecraft:white_concrete
fill 3775 -57 0 3791 -49 18 minecraft:white_concrete
fill 3774 -57 0 3774 -49 18 minecraft:white_concrete
fill 3792 -57 0 3792 -49 18 minecraft:white_concrete
fill 3774 -57 -1 3792 -49 -1 minecraft:white_concrete
fill 3774 -57 19 3792 -49 19 minecraft:white_concrete
fill 3776 -57 1 3790 -49 17 minecraft:air
fill 3775 -48 0 3791 -48 18 minecraft:white_concrete
fill 3776 -48 1 3790 -48 1 minecraft:glowstone
fill 3776 -48 17 3790 -48 17 minecraft:glowstone
fill 3776 -48 2 3776 -48 16 minecraft:glowstone
fill 3790 -48 2 3790 -48 16 minecraft:glowstone
fill 3777 -48 2 3789 -48 2 minecraft:glowstone
fill 3777 -48 16 3789 -48 16 minecraft:glowstone
fill 3777 -48 3 3777 -48 15 minecraft:glowstone
fill 3789 -48 3 3789 -48 15 minecraft:glowstone
fill 3778 -48 3 3788 -48 3 minecraft:glowstone
fill 3778 -48 15 3788 -48 15 minecraft:glowstone
fill 3778 -48 4 3778 -48 14 minecraft:glowstone
fill 3788 -48 4 3788 -48 14 minecraft:glowstone
fill 3781 -48 7 3785 -48 11 minecraft:glowstone
fill 3776 -53 1 3790 -53 5 minecraft:glowstone
fill 3776 -52 1 3790 -52 5 minecraft:smooth_stone
fill 3776 -51 6 3790 -51 6 minecraft:oak_fence
fill 3783 -57 1 3785 -57 3 minecraft:magenta_concrete
fill 3783 -52 10 3783 -52 10 minecraft:smooth_stone
setblock 3781 -51 5 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3783 -51 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3780 -51 3 minecraft:stone_slab[type=bottom]
