# Scene: picture_medium_02
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3200 -58 0 3216 -58 18 minecraft:white_concrete
fill 3200 -57 0 3216 -49 18 minecraft:white_concrete
fill 3199 -57 0 3199 -49 18 minecraft:white_concrete
fill 3217 -57 0 3217 -49 18 minecraft:white_concrete
fill 3199 -57 -1 3217 -49 -1 minecraft:white_concrete
fill 3199 -57 19 3217 -49 19 minecraft:white_concrete
fill 3201 -57 1 3215 -49 17 minecraft:air
fill 3200 -48 0 3216 -48 18 minecraft:white_concrete
fill 3201 -48 1 3215 -48 1 minecraft:glowstone
fill 3201 -48 17 3215 -48 17 minecraft:glowstone
fill 3201 -48 2 3201 -48 16 minecraft:glowstone
fill 3215 -48 2 3215 -48 16 minecraft:glowstone
fill 3202 -48 2 3214 -48 2 minecraft:glowstone
fill 3202 -48 16 3214 -48 16 minecraft:glowstone
fill 3202 -48 3 3202 -48 15 minecraft:glowstone
fill 3214 -48 3 3214 -48 15 minecraft:glowstone
fill 3203 -48 3 3213 -48 3 minecraft:glowstone
fill 3203 -48 15 3213 -48 15 minecraft:glowstone
fill 3203 -48 4 3203 -48 14 minecraft:glowstone
fill 3213 -48 4 3213 -48 14 minecraft:glowstone
fill 3206 -48 7 3210 -48 11 minecraft:glowstone
fill 3201 -53 1 3215 -53 5 minecraft:glowstone
fill 3201 -52 1 3215 -52 5 minecraft:smooth_stone
fill 3201 -51 6 3215 -51 6 minecraft:oak_fence
fill 3210 -57 1 3213 -57 4 minecraft:orange_concrete
fill 3208 -52 10 3208 -52 10 minecraft:smooth_stone
setblock 3206 -51 4 minecraft:furnace
setblock 3201 -51 1 minecraft:furnace
setblock 3215 -51 1 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3206 -51 2 minecraft:furnace
setblock 3203 -51 5 minecraft:furnace
