# Scene: tier_elevator_hard_02
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 2 of 15 with 3-5 decorations.
fill 930 -59 0 952 -59 22 minecraft:white_concrete
fill 930 -58 0 952 -53 22 minecraft:white_concrete
fill 929 -58 0 929 -53 22 minecraft:white_concrete
fill 953 -58 0 953 -53 22 minecraft:white_concrete
fill 929 -58 -1 953 -53 -1 minecraft:white_concrete
fill 929 -58 23 953 -53 23 minecraft:white_concrete
fill 931 -58 1 951 -53 21 minecraft:air
fill 930 -52 0 952 -52 22 minecraft:white_concrete
fill 931 -52 1 951 -52 1 minecraft:glowstone
fill 931 -52 21 951 -52 21 minecraft:glowstone
fill 931 -52 2 931 -52 20 minecraft:glowstone
fill 951 -52 2 951 -52 20 minecraft:glowstone
fill 932 -52 2 950 -52 2 minecraft:glowstone
fill 932 -52 20 950 -52 20 minecraft:glowstone
fill 932 -52 3 932 -52 19 minecraft:glowstone
fill 950 -52 3 950 -52 19 minecraft:glowstone
fill 933 -52 3 949 -52 3 minecraft:glowstone
fill 933 -52 19 949 -52 19 minecraft:glowstone
fill 933 -52 4 933 -52 18 minecraft:glowstone
fill 949 -52 4 949 -52 18 minecraft:glowstone
fill 939 -52 9 943 -52 13 minecraft:glowstone
fill 931 -58 11 951 -53 11 minecraft:white_concrete
fill 941 -58 11 942 -56 11 minecraft:gray_concrete
setblock 942 -58 4 minecraft:oak_pressure_plate
setblock 942 -58 5 minecraft:oak_pressure_plate
setblock 942 -58 6 minecraft:oak_pressure_plate
setblock 943 -58 4 minecraft:oak_pressure_plate
setblock 943 -58 5 minecraft:oak_pressure_plate
setblock 943 -58 6 minecraft:oak_pressure_plate
setblock 944 -58 4 minecraft:oak_pressure_plate
setblock 944 -58 5 minecraft:oak_pressure_plate
setblock 944 -58 6 minecraft:oak_pressure_plate
setblock 932 -58 4 minecraft:bookshelf
setblock 950 -58 7 minecraft:crafting_table
setblock 941 -58 2 minecraft:bookshelf
setblock 949 -58 2 minecraft:furnace

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_02/place_command_blocks
