# Scene: tier_elevator_hard_15
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 15 of 15 with 3-5 decorations.
fill 1321 -59 0 1341 -59 23 minecraft:white_concrete
fill 1321 -58 0 1341 -53 23 minecraft:white_concrete
fill 1320 -58 0 1320 -53 23 minecraft:white_concrete
fill 1342 -58 0 1342 -53 23 minecraft:white_concrete
fill 1320 -58 -1 1342 -53 -1 minecraft:white_concrete
fill 1320 -58 24 1342 -53 24 minecraft:white_concrete
fill 1322 -58 1 1340 -53 22 minecraft:air
fill 1321 -52 0 1341 -52 23 minecraft:white_concrete
fill 1322 -52 1 1340 -52 1 minecraft:glowstone
fill 1322 -52 22 1340 -52 22 minecraft:glowstone
fill 1322 -52 2 1322 -52 21 minecraft:glowstone
fill 1340 -52 2 1340 -52 21 minecraft:glowstone
fill 1323 -52 2 1339 -52 2 minecraft:glowstone
fill 1323 -52 21 1339 -52 21 minecraft:glowstone
fill 1323 -52 3 1323 -52 20 minecraft:glowstone
fill 1339 -52 3 1339 -52 20 minecraft:glowstone
fill 1324 -52 3 1338 -52 3 minecraft:glowstone
fill 1324 -52 20 1338 -52 20 minecraft:glowstone
fill 1324 -52 4 1324 -52 19 minecraft:glowstone
fill 1338 -52 4 1338 -52 19 minecraft:glowstone
fill 1329 -52 9 1333 -52 13 minecraft:glowstone
fill 1322 -58 12 1340 -53 12 minecraft:white_concrete
fill 1329 -58 12 1330 -56 12 minecraft:light_blue_concrete
setblock 1328 -58 6 minecraft:stone_pressure_plate
setblock 1328 -58 7 minecraft:stone_pressure_plate
setblock 1328 -58 8 minecraft:stone_pressure_plate
setblock 1329 -58 6 minecraft:stone_pressure_plate
setblock 1329 -58 7 minecraft:stone_pressure_plate
setblock 1329 -58 8 minecraft:stone_pressure_plate
setblock 1330 -58 6 minecraft:stone_pressure_plate
setblock 1330 -58 7 minecraft:stone_pressure_plate
setblock 1330 -58 8 minecraft:stone_pressure_plate
setblock 1330 -58 2 minecraft:crafting_table
setblock 1336 -58 2 minecraft:bookshelf
setblock 1339 -58 2 minecraft:furnace
setblock 1333 -58 2 minecraft:bookshelf
setblock 1323 -58 7 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_15/place_command_blocks
