# Scene: picture_easy_03
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2850 -58 0 2866 -58 18 minecraft:white_concrete
fill 2850 -57 0 2866 -49 18 minecraft:white_concrete
fill 2849 -57 0 2849 -49 18 minecraft:white_concrete
fill 2867 -57 0 2867 -49 18 minecraft:white_concrete
fill 2849 -57 -1 2867 -49 -1 minecraft:white_concrete
fill 2849 -57 19 2867 -49 19 minecraft:white_concrete
fill 2851 -57 1 2865 -49 17 minecraft:air
fill 2850 -48 0 2866 -48 18 minecraft:white_concrete
fill 2851 -48 1 2865 -48 1 minecraft:glowstone
fill 2851 -48 17 2865 -48 17 minecraft:glowstone
fill 2851 -48 2 2851 -48 16 minecraft:glowstone
fill 2865 -48 2 2865 -48 16 minecraft:glowstone
fill 2852 -48 2 2864 -48 2 minecraft:glowstone
fill 2852 -48 16 2864 -48 16 minecraft:glowstone
fill 2852 -48 3 2852 -48 15 minecraft:glowstone
fill 2864 -48 3 2864 -48 15 minecraft:glowstone
fill 2853 -48 3 2863 -48 3 minecraft:glowstone
fill 2853 -48 15 2863 -48 15 minecraft:glowstone
fill 2853 -48 4 2853 -48 14 minecraft:glowstone
fill 2863 -48 4 2863 -48 14 minecraft:glowstone
fill 2856 -48 7 2860 -48 11 minecraft:glowstone
fill 2851 -53 1 2865 -53 5 minecraft:glowstone
fill 2851 -52 1 2865 -52 5 minecraft:smooth_stone
fill 2851 -51 6 2865 -51 6 minecraft:oak_fence
fill 2855 -57 1 2859 -57 5 minecraft:yellow_concrete
fill 2858 -52 10 2858 -52 10 minecraft:smooth_stone
setblock 2854 -51 4 minecraft:chest
setblock 2863 -51 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2863 -51 2 minecraft:crafting_table
