# Scene: tier_path_medium_11
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 11 of 15 with 3-5 decorations.
fill 1650 -58 0 1672 -58 31 minecraft:white_concrete
fill 1650 -57 0 1672 -52 31 minecraft:white_concrete
fill 1649 -57 0 1649 -52 31 minecraft:white_concrete
fill 1673 -57 0 1673 -52 31 minecraft:white_concrete
fill 1649 -57 -1 1673 -52 -1 minecraft:white_concrete
fill 1649 -57 32 1673 -52 32 minecraft:white_concrete
fill 1651 -57 1 1671 -52 30 minecraft:air
fill 1650 -51 0 1672 -51 31 minecraft:white_concrete
fill 1651 -51 1 1671 -51 1 minecraft:glowstone
fill 1651 -51 30 1671 -51 30 minecraft:glowstone
fill 1651 -51 2 1651 -51 29 minecraft:glowstone
fill 1671 -51 2 1671 -51 29 minecraft:glowstone
fill 1652 -51 2 1670 -51 2 minecraft:glowstone
fill 1652 -51 29 1670 -51 29 minecraft:glowstone
fill 1652 -51 3 1652 -51 28 minecraft:glowstone
fill 1670 -51 3 1670 -51 28 minecraft:glowstone
fill 1653 -51 3 1669 -51 3 minecraft:glowstone
fill 1653 -51 28 1669 -51 28 minecraft:glowstone
fill 1653 -51 4 1653 -51 27 minecraft:glowstone
fill 1669 -51 4 1669 -51 27 minecraft:glowstone
fill 1659 -51 13 1663 -51 17 minecraft:glowstone
fill 1650 -61 0 1672 -58 31 minecraft:white_concrete
fill 1650 -61 0 1672 -58 12 minecraft:white_concrete
fill 1650 -61 18 1672 -58 31 minecraft:white_concrete
fill 1651 -61 13 1671 -58 17 minecraft:air
fill 1650 -61 0 1672 -61 31 minecraft:black_concrete
fill 1660 -58 13 1662 -58 17 minecraft:air
fill 1660 -57 19 1662 -57 19 minecraft:gold_block
setblock 1660 -57 8 minecraft:stone_pressure_plate
setblock 1660 -57 9 minecraft:stone_pressure_plate
setblock 1660 -57 10 minecraft:stone_pressure_plate
setblock 1661 -57 8 minecraft:stone_pressure_plate
setblock 1661 -57 9 minecraft:stone_pressure_plate
setblock 1661 -57 10 minecraft:stone_pressure_plate
setblock 1662 -57 8 minecraft:stone_pressure_plate
setblock 1662 -57 9 minecraft:stone_pressure_plate
setblock 1662 -57 10 minecraft:stone_pressure_plate
setblock 1659 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1662 -57 2 minecraft:stone_slab[type=bottom]
setblock 1652 -57 10 minecraft:bookshelf

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_11/place_command_blocks
