# Scene: tier_path_easy_12
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 12 of 15 with 3-5 decorations.
fill 1231 -58 0 1251 -58 30 minecraft:white_concrete
fill 1231 -57 0 1251 -52 30 minecraft:white_concrete
fill 1230 -57 0 1230 -52 30 minecraft:white_concrete
fill 1252 -57 0 1252 -52 30 minecraft:white_concrete
fill 1230 -57 -1 1252 -52 -1 minecraft:white_concrete
fill 1230 -57 31 1252 -52 31 minecraft:white_concrete
fill 1232 -57 1 1250 -52 29 minecraft:air
fill 1231 -51 0 1251 -51 30 minecraft:white_concrete
fill 1232 -51 1 1250 -51 1 minecraft:glowstone
fill 1232 -51 29 1250 -51 29 minecraft:glowstone
fill 1232 -51 2 1232 -51 28 minecraft:glowstone
fill 1250 -51 2 1250 -51 28 minecraft:glowstone
fill 1233 -51 2 1249 -51 2 minecraft:glowstone
fill 1233 -51 28 1249 -51 28 minecraft:glowstone
fill 1233 -51 3 1233 -51 27 minecraft:glowstone
fill 1249 -51 3 1249 -51 27 minecraft:glowstone
fill 1234 -51 3 1248 -51 3 minecraft:glowstone
fill 1234 -51 27 1248 -51 27 minecraft:glowstone
fill 1234 -51 4 1234 -51 26 minecraft:glowstone
fill 1248 -51 4 1248 -51 26 minecraft:glowstone
fill 1239 -51 13 1243 -51 17 minecraft:glowstone
fill 1231 -61 0 1251 -58 30 minecraft:white_concrete
fill 1231 -61 0 1251 -58 12 minecraft:white_concrete
fill 1231 -61 17 1251 -58 30 minecraft:white_concrete
fill 1232 -61 13 1250 -58 16 minecraft:air
fill 1231 -61 0 1251 -61 30 minecraft:black_concrete
fill 1239 -58 13 1242 -58 16 minecraft:air
fill 1239 -57 18 1242 -57 18 minecraft:gold_block
setblock 1240 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1240 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1240 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1240 -57 11 minecraft:polished_blackstone_pressure_plate
setblock 1241 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1241 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1241 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1241 -57 11 minecraft:polished_blackstone_pressure_plate
setblock 1242 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1242 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1242 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1242 -57 11 minecraft:polished_blackstone_pressure_plate
setblock 1243 -57 8 minecraft:polished_blackstone_pressure_plate
setblock 1243 -57 9 minecraft:polished_blackstone_pressure_plate
setblock 1243 -57 10 minecraft:polished_blackstone_pressure_plate
setblock 1243 -57 11 minecraft:polished_blackstone_pressure_plate
setblock 1249 -57 11 minecraft:stone_slab[type=bottom]
setblock 1244 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1233 -57 10 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1243 -57 2 minecraft:crafting_table
setblock 1236 -57 2 minecraft:bookshelf

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_easy_12/place_command_blocks
