# Scene: tier_elevator_medium_05
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 5 of 15 with 3-5 decorations.
fill 570 -59 0 592 -59 23 minecraft:white_concrete
fill 570 -58 0 592 -53 23 minecraft:white_concrete
fill 569 -58 0 569 -53 23 minecraft:white_concrete
fill 593 -58 0 593 -53 23 minecraft:white_concrete
fill 569 -58 -1 593 -53 -1 minecraft:white_concrete
fill 569 -58 24 593 -53 24 minecraft:white_concrete
fill 571 -58 1 591 -53 22 minecraft:air
fill 570 -52 0 592 -52 23 minecraft:white_concrete
fill 571 -52 1 591 -52 1 minecraft:glowstone
fill 571 -52 22 591 -52 22 minecraft:glowstone
fill 571 -52 2 571 -52 21 minecraft:glowstone
fill 591 -52 2 591 -52 21 minecraft:glowstone
fill 572 -52 2 590 -52 2 minecraft:glowstone
fill 572 -52 21 590 -52 21 minecraft:glowstone
fill 572 -52 3 572 -52 20 minecraft:glowstone
fill 590 -52 3 590 -52 20 minecraft:glowstone
fill 573 -52 3 589 -52 3 minecraft:glowstone
fill 573 -52 20 589 -52 20 minecraft:glowstone
fill 573 -52 4 573 -52 19 minecraft:glowstone
fill 589 -52 4 589 -52 19 minecraft:glowstone
fill 579 -52 9 583 -52 13 minecraft:glowstone
fill 571 -58 12 591 -53 12 minecraft:white_concrete
fill 581 -58 12 582 -56 12 minecraft:light_blue_concrete
setblock 578 -58 7 minecraft:mangrove_pressure_plate
setblock 578 -58 8 minecraft:mangrove_pressure_plate
setblock 578 -58 9 minecraft:mangrove_pressure_plate
setblock 579 -58 7 minecraft:mangrove_pressure_plate
setblock 579 -58 8 minecraft:mangrove_pressure_plate
setblock 579 -58 9 minecraft:mangrove_pressure_plate
setblock 580 -58 7 minecraft:mangrove_pressure_plate
setblock 580 -58 8 minecraft:mangrove_pressure_plate
setblock 580 -58 9 minecraft:mangrove_pressure_plate
setblock 590 -58 4 minecraft:bookshelf
setblock 581 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 572 -58 2 minecraft:crafting_table

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_05/place_command_blocks
