# Scene: tier_path_hard_14
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 14 of 15 with 3-5 decorations.
fill 2190 -58 0 2212 -58 30 minecraft:white_concrete
fill 2190 -57 0 2212 -52 30 minecraft:white_concrete
fill 2189 -57 0 2189 -52 30 minecraft:white_concrete
fill 2213 -57 0 2213 -52 30 minecraft:white_concrete
fill 2189 -57 -1 2213 -52 -1 minecraft:white_concrete
fill 2189 -57 31 2213 -52 31 minecraft:white_concrete
fill 2191 -57 1 2211 -52 29 minecraft:air
fill 2190 -51 0 2212 -51 30 minecraft:white_concrete
fill 2191 -51 1 2211 -51 1 minecraft:glowstone
fill 2191 -51 29 2211 -51 29 minecraft:glowstone
fill 2191 -51 2 2191 -51 28 minecraft:glowstone
fill 2211 -51 2 2211 -51 28 minecraft:glowstone
fill 2192 -51 2 2210 -51 2 minecraft:glowstone
fill 2192 -51 28 2210 -51 28 minecraft:glowstone
fill 2192 -51 3 2192 -51 27 minecraft:glowstone
fill 2210 -51 3 2210 -51 27 minecraft:glowstone
fill 2193 -51 3 2209 -51 3 minecraft:glowstone
fill 2193 -51 27 2209 -51 27 minecraft:glowstone
fill 2193 -51 4 2193 -51 26 minecraft:glowstone
fill 2209 -51 4 2209 -51 26 minecraft:glowstone
fill 2199 -51 13 2203 -51 17 minecraft:glowstone
fill 2190 -61 0 2212 -58 30 minecraft:white_concrete
fill 2190 -61 0 2212 -58 11 minecraft:white_concrete
fill 2190 -61 18 2212 -58 30 minecraft:white_concrete
fill 2191 -61 12 2211 -58 17 minecraft:air
fill 2190 -61 0 2212 -61 30 minecraft:black_concrete
fill 2200 -58 12 2202 -58 17 minecraft:air
fill 2200 -57 19 2202 -57 19 minecraft:gold_block
setblock 2200 -57 7 minecraft:spruce_pressure_plate
setblock 2200 -57 8 minecraft:spruce_pressure_plate
setblock 2200 -57 9 minecraft:spruce_pressure_plate
setblock 2201 -57 7 minecraft:spruce_pressure_plate
setblock 2201 -57 8 minecraft:spruce_pressure_plate
setblock 2201 -57 9 minecraft:spruce_pressure_plate
setblock 2202 -57 7 minecraft:spruce_pressure_plate
setblock 2202 -57 8 minecraft:spruce_pressure_plate
setblock 2202 -57 9 minecraft:spruce_pressure_plate
setblock 2192 -57 8 minecraft:furnace
setblock 2196 -57 2 minecraft:chest
setblock 2197 -57 2 minecraft:furnace
setblock 2192 -57 7 minecraft:chest
setblock 2192 -57 5 minecraft:stone_slab[type=bottom]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_14/place_command_blocks
