# Scene: picture_medium_09
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3375 -58 0 3391 -58 18 minecraft:white_concrete
fill 3375 -57 0 3391 -49 18 minecraft:white_concrete
fill 3374 -57 0 3374 -49 18 minecraft:white_concrete
fill 3392 -57 0 3392 -49 18 minecraft:white_concrete
fill 3374 -57 -1 3392 -49 -1 minecraft:white_concrete
fill 3374 -57 19 3392 -49 19 minecraft:white_concrete
fill 3376 -57 1 3390 -49 17 minecraft:air
fill 3375 -48 0 3391 -48 18 minecraft:white_concrete
fill 3376 -48 1 3390 -48 1 minecraft:glowstone
fill 3376 -48 17 3390 -48 17 minecraft:glowstone
fill 3376 -48 2 3376 -48 16 minecraft:glowstone
fill 3390 -48 2 3390 -48 16 minecraft:glowstone
fill 3377 -48 2 3389 -48 2 minecraft:glowstone
fill 3377 -48 16 3389 -48 16 minecraft:glowstone
fill 3377 -48 3 3377 -48 15 minecraft:glowstone
fill 3389 -48 3 3389 -48 15 minecraft:glowstone
fill 3378 -48 3 3388 -48 3 minecraft:glowstone
fill 3378 -48 15 3388 -48 15 minecraft:glowstone
fill 3378 -48 4 3378 -48 14 minecraft:glowstone
fill 3388 -48 4 3388 -48 14 minecraft:glowstone
fill 3381 -48 7 3385 -48 11 minecraft:glowstone
fill 3376 -53 1 3390 -53 5 minecraft:glowstone
fill 3376 -52 1 3390 -52 5 minecraft:smooth_stone
fill 3376 -51 6 3390 -51 6 minecraft:oak_fence
fill 3379 -57 2 3382 -57 5 minecraft:purple_concrete
fill 3383 -52 10 3383 -52 10 minecraft:smooth_stone
setblock 3383 -51 5 minecraft:crafting_table
setblock 3389 -51 4 minecraft:crafting_table
setblock 3388 -51 3 minecraft:furnace
setblock 3384 -51 5 minecraft:chest
setblock 3388 -51 4 minecraft:crafting_table
setblock 3390 -51 1 minecraft:bookshelf
setblock 3378 -51 1 minecraft:furnace
