# Scene: truck_medium_01
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2273 -58 0 2296 -58 22 minecraft:white_concrete
fill 2273 -57 0 2296 -52 22 minecraft:white_concrete
fill 2272 -57 0 2272 -52 22 minecraft:white_concrete
fill 2297 -57 0 2297 -52 22 minecraft:white_concrete
fill 2272 -57 -1 2297 -52 -1 minecraft:white_concrete
fill 2272 -57 23 2297 -52 23 minecraft:white_concrete
fill 2274 -57 1 2295 -52 21 minecraft:air
fill 2273 -51 0 2296 -51 22 minecraft:white_concrete
fill 2274 -51 1 2295 -51 1 minecraft:glowstone
fill 2274 -51 21 2295 -51 21 minecraft:glowstone
fill 2274 -51 2 2274 -51 20 minecraft:glowstone
fill 2295 -51 2 2295 -51 20 minecraft:glowstone
fill 2275 -51 2 2294 -51 2 minecraft:glowstone
fill 2275 -51 20 2294 -51 20 minecraft:glowstone
fill 2275 -51 3 2275 -51 19 minecraft:glowstone
fill 2294 -51 3 2294 -51 19 minecraft:glowstone
fill 2276 -51 3 2293 -51 3 minecraft:glowstone
fill 2276 -51 19 2293 -51 19 minecraft:glowstone
fill 2276 -51 4 2276 -51 18 minecraft:glowstone
fill 2293 -51 4 2293 -51 18 minecraft:glowstone
fill 2282 -51 9 2286 -51 13 minecraft:glowstone
fill 2284 -58 10 2286 -58 12 minecraft:red_concrete
setblock 2294 -57 5 minecraft:chest
setblock 2294 -57 12 minecraft:chest
setblock 2275 -57 14 minecraft:chest
setblock 2294 -57 19 minecraft:furnace
setblock 2294 -57 17 minecraft:chest
setblock 2294 -57 16 minecraft:bookshelf
setblock 2294 -57 15 minecraft:stone_slab[type=bottom]
setblock 2294 -57 6 minecraft:bookshelf
setblock 2275 -57 7 minecraft:crafting_table
setblock 2294 -57 8 minecraft:chest
