# Scene: truck_medium_14
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2683 -58 0 2705 -58 23 minecraft:white_concrete
fill 2683 -57 0 2705 -52 23 minecraft:white_concrete
fill 2682 -57 0 2682 -52 23 minecraft:white_concrete
fill 2706 -57 0 2706 -52 23 minecraft:white_concrete
fill 2682 -57 -1 2706 -52 -1 minecraft:white_concrete
fill 2682 -57 24 2706 -52 24 minecraft:white_concrete
fill 2684 -57 1 2704 -52 22 minecraft:air
fill 2683 -51 0 2705 -51 23 minecraft:white_concrete
fill 2684 -51 1 2704 -51 1 minecraft:glowstone
fill 2684 -51 22 2704 -51 22 minecraft:glowstone
fill 2684 -51 2 2684 -51 21 minecraft:glowstone
fill 2704 -51 2 2704 -51 21 minecraft:glowstone
fill 2685 -51 2 2703 -51 2 minecraft:glowstone
fill 2685 -51 21 2703 -51 21 minecraft:glowstone
fill 2685 -51 3 2685 -51 20 minecraft:glowstone
fill 2703 -51 3 2703 -51 20 minecraft:glowstone
fill 2686 -51 3 2702 -51 3 minecraft:glowstone
fill 2686 -51 20 2702 -51 20 minecraft:glowstone
fill 2686 -51 4 2686 -51 19 minecraft:glowstone
fill 2702 -51 4 2702 -51 19 minecraft:glowstone
fill 2692 -51 9 2696 -51 13 minecraft:glowstone
fill 2693 -58 11 2695 -58 13 minecraft:lime_concrete
setblock 2685 -57 7 minecraft:furnace
setblock 2703 -57 7 minecraft:chest
setblock 2703 -57 21 minecraft:bookshelf
setblock 2685 -57 18 minecraft:crafting_table
setblock 2685 -57 4 minecraft:bookshelf
setblock 2685 -57 8 minecraft:crafting_table
setblock 2685 -57 17 minecraft:crafting_table
setblock 2685 -57 12 minecraft:furnace
setblock 2703 -57 9 minecraft:stone_slab[type=bottom]
setblock 2703 -57 3 minecraft:crafting_table
