# Scene: picture_hard_06
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3675 -58 0 3691 -58 18 minecraft:white_concrete
fill 3675 -57 0 3691 -49 18 minecraft:white_concrete
fill 3674 -57 0 3674 -49 18 minecraft:white_concrete
fill 3692 -57 0 3692 -49 18 minecraft:white_concrete
fill 3674 -57 -1 3692 -49 -1 minecraft:white_concrete
fill 3674 -57 19 3692 -49 19 minecraft:white_concrete
fill 3676 -57 1 3690 -49 17 minecraft:air
fill 3675 -48 0 3691 -48 18 minecraft:white_concrete
fill 3676 -48 1 3690 -48 1 minecraft:glowstone
fill 3676 -48 17 3690 -48 17 minecraft:glowstone
fill 3676 -48 2 3676 -48 16 minecraft:glowstone
fill 3690 -48 2 3690 -48 16 minecraft:glowstone
fill 3677 -48 2 3689 -48 2 minecraft:glowstone
fill 3677 -48 16 3689 -48 16 minecraft:glowstone
fill 3677 -48 3 3677 -48 15 minecraft:glowstone
fill 3689 -48 3 3689 -48 15 minecraft:glowstone
fill 3678 -48 3 3688 -48 3 minecraft:glowstone
fill 3678 -48 15 3688 -48 15 minecraft:glowstone
fill 3678 -48 4 3678 -48 14 minecraft:glowstone
fill 3688 -48 4 3688 -48 14 minecraft:glowstone
fill 3681 -48 7 3685 -48 11 minecraft:glowstone
fill 3676 -53 1 3690 -53 5 minecraft:glowstone
fill 3676 -52 1 3690 -52 5 minecraft:smooth_stone
fill 3676 -51 6 3690 -51 6 minecraft:oak_fence
fill 3687 -57 1 3689 -57 3 minecraft:cyan_concrete
fill 3683 -52 10 3683 -52 10 minecraft:smooth_stone
setblock 3681 -51 3 minecraft:chest
setblock 3688 -51 5 minecraft:furnace
setblock 3682 -51 1 minecraft:furnace
setblock 3683 -51 5 minecraft:bookshelf
setblock 3681 -51 5 minecraft:crafting_table
