# Scene: truck_hard_06
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2904 -58 0 2926 -58 23 minecraft:white_concrete
fill 2904 -57 0 2926 -52 23 minecraft:white_concrete
fill 2903 -57 0 2903 -52 23 minecraft:white_concrete
fill 2927 -57 0 2927 -52 23 minecraft:white_concrete
fill 2903 -57 -1 2927 -52 -1 minecraft:white_concrete
fill 2903 -57 24 2927 -52 24 minecraft:white_concrete
fill 2905 -57 1 2925 -52 22 minecraft:air
fill 2904 -51 0 2926 -51 23 minecraft:white_concrete
fill 2905 -51 1 2925 -51 1 minecraft:glowstone
fill 2905 -51 22 2925 -51 22 minecraft:glowstone
fill 2905 -51 2 2905 -51 21 minecraft:glowstone
fill 2925 -51 2 2925 -51 21 minecraft:glowstone
fill 2906 -51 2 2924 -51 2 minecraft:glowstone
fill 2906 -51 21 2924 -51 21 minecraft:glowstone
fill 2906 -51 3 2906 -51 20 minecraft:glowstone
fill 2924 -51 3 2924 -51 20 minecraft:glowstone
fill 2907 -51 3 2923 -51 3 minecraft:glowstone
fill 2907 -51 20 2923 -51 20 minecraft:glowstone
fill 2907 -51 4 2907 -51 19 minecraft:glowstone
fill 2923 -51 4 2923 -51 19 minecraft:glowstone
fill 2913 -51 9 2917 -51 13 minecraft:glowstone
fill 2915 -58 12 2916 -58 13 minecraft:cyan_concrete
setblock 2906 -57 5 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2906 -57 10 minecraft:crafting_table
setblock 2924 -57 10 minecraft:bookshelf
setblock 2924 -57 8 minecraft:bookshelf
setblock 2906 -57 18 minecraft:furnace
setblock 2906 -57 6 minecraft:crafting_table
setblock 2906 -57 9 minecraft:stone_slab[type=bottom]
setblock 2924 -57 9 minecraft:stone_slab[type=bottom]
setblock 2924 -57 6 minecraft:crafting_table
setblock 2924 -57 13 minecraft:furnace
setblock 2924 -57 18 minecraft:bookshelf
setblock 2906 -57 11 minecraft:stone_slab[type=bottom]
setblock 2906 -57 17 minecraft:bookshelf
setblock 2924 -57 17 minecraft:crafting_table
setblock 2924 -57 15 minecraft:crafting_table
