# Scene: tier_elevator_hard_05
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 5 of 15 with 3-5 decorations.
fill 1020 -59 0 1042 -59 23 minecraft:white_concrete
fill 1020 -58 0 1042 -53 23 minecraft:white_concrete
fill 1019 -58 0 1019 -53 23 minecraft:white_concrete
fill 1043 -58 0 1043 -53 23 minecraft:white_concrete
fill 1019 -58 -1 1043 -53 -1 minecraft:white_concrete
fill 1019 -58 24 1043 -53 24 minecraft:white_concrete
fill 1021 -58 1 1041 -53 22 minecraft:air
fill 1020 -52 0 1042 -52 23 minecraft:white_concrete
fill 1021 -52 1 1041 -52 1 minecraft:glowstone
fill 1021 -52 22 1041 -52 22 minecraft:glowstone
fill 1021 -52 2 1021 -52 21 minecraft:glowstone
fill 1041 -52 2 1041 -52 21 minecraft:glowstone
fill 1022 -52 2 1040 -52 2 minecraft:glowstone
fill 1022 -52 21 1040 -52 21 minecraft:glowstone
fill 1022 -52 3 1022 -52 20 minecraft:glowstone
fill 1040 -52 3 1040 -52 20 minecraft:glowstone
fill 1023 -52 3 1039 -52 3 minecraft:glowstone
fill 1023 -52 20 1039 -52 20 minecraft:glowstone
fill 1023 -52 4 1023 -52 19 minecraft:glowstone
fill 1039 -52 4 1039 -52 19 minecraft:glowstone
fill 1029 -52 9 1033 -52 13 minecraft:glowstone
fill 1021 -58 12 1041 -53 12 minecraft:white_concrete
fill 1031 -58 12 1032 -56 12 minecraft:light_blue_concrete
setblock 1028 -58 6 minecraft:mangrove_pressure_plate
setblock 1028 -58 7 minecraft:mangrove_pressure_plate
setblock 1028 -58 8 minecraft:mangrove_pressure_plate
setblock 1029 -58 6 minecraft:mangrove_pressure_plate
setblock 1029 -58 7 minecraft:mangrove_pressure_plate
setblock 1029 -58 8 minecraft:mangrove_pressure_plate
setblock 1030 -58 6 minecraft:mangrove_pressure_plate
setblock 1030 -58 7 minecraft:mangrove_pressure_plate
setblock 1030 -58 8 minecraft:mangrove_pressure_plate
setblock 1022 -58 3 minecraft:stone_slab[type=bottom]
setblock 1022 -58 2 minecraft:furnace
setblock 1031 -58 2 minecraft:furnace
setblock 1022 -58 7 minecraft:furnace
setblock 1040 -58 6 minecraft:chest

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_05/place_command_blocks
