# Scene: tier_path_medium_08
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 8 of 15 with 3-5 decorations.
fill 1560 -58 0 1582 -58 30 minecraft:white_concrete
fill 1560 -57 0 1582 -52 30 minecraft:white_concrete
fill 1559 -57 0 1559 -52 30 minecraft:white_concrete
fill 1583 -57 0 1583 -52 30 minecraft:white_concrete
fill 1559 -57 -1 1583 -52 -1 minecraft:white_concrete
fill 1559 -57 31 1583 -52 31 minecraft:white_concrete
fill 1561 -57 1 1581 -52 29 minecraft:air
fill 1560 -51 0 1582 -51 30 minecraft:white_concrete
fill 1561 -51 1 1581 -51 1 minecraft:glowstone
fill 1561 -51 29 1581 -51 29 minecraft:glowstone
fill 1561 -51 2 1561 -51 28 minecraft:glowstone
fill 1581 -51 2 1581 -51 28 minecraft:glowstone
fill 1562 -51 2 1580 -51 2 minecraft:glowstone
fill 1562 -51 28 1580 -51 28 minecraft:glowstone
fill 1562 -51 3 1562 -51 27 minecraft:glowstone
fill 1580 -51 3 1580 -51 27 minecraft:glowstone
fill 1563 -51 3 1579 -51 3 minecraft:glowstone
fill 1563 -51 27 1579 -51 27 minecraft:glowstone
fill 1563 -51 4 1563 -51 26 minecraft:glowstone
fill 1579 -51 4 1579 -51 26 minecraft:glowstone
fill 1569 -51 13 1573 -51 17 minecraft:glowstone
fill 1560 -61 0 1582 -58 30 minecraft:white_concrete
fill 1560 -61 0 1582 -58 12 minecraft:white_concrete
fill 1560 -61 18 1582 -58 30 minecraft:white_concrete
fill 1561 -61 13 1581 -58 17 minecraft:air
fill 1560 -61 0 1582 -61 30 minecraft:black_concrete
fill 1570 -58 13 1572 -58 17 minecraft:air
fill 1570 -57 19 1572 -57 19 minecraft:gold_block
setblock 1570 -57 8 minecraft:dark_oak_pressure_plate
setblock 1570 -57 9 minecraft:dark_oak_pressure_plate
setblock 1570 -57 10 minecraft:dark_oak_pressure_plate
setblock 1571 -57 8 minecraft:dark_oak_pressure_plate
setblock 1571 -57 9 minecraft:dark_oak_pressure_plate
setblock 1571 -57 10 minecraft:dark_oak_pressure_plate
setblock 1572 -57 8 minecraft:dark_oak_pressure_plate
setblock 1572 -57 9 minecraft:dark_oak_pressure_plate
setblock 1572 -57 10 minecraft:dark_oak_pressure_plate
setblock 1574 -57 2 minecraft:chest
setblock 1570 -57 2 minecraft:bookshelf
setblock 1562 -57 7 minecraft:crafting_table
setblock 1565 -57 2 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_08/place_command_blocks
