# Scene: truck_hard_12
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3093 -58 0 3115 -58 23 minecraft:white_concrete
fill 3093 -57 0 3115 -52 23 minecraft:white_concrete
fill 3092 -57 0 3092 -52 23 minecraft:white_concrete
fill 3116 -57 0 3116 -52 23 minecraft:white_concrete
fill 3092 -57 -1 3116 -52 -1 minecraft:white_concrete
fill 3092 -57 24 3116 -52 24 minecraft:white_concrete
fill 3094 -57 1 3114 -52 22 minecraft:air
fill 3093 -51 0 3115 -51 23 minecraft:white_concrete
fill 3094 -51 1 3114 -51 1 minecraft:glowstone
fill 3094 -51 22 3114 -51 22 minecraft:glowstone
fill 3094 -51 2 3094 -51 21 minecraft:glowstone
fill 3114 -51 2 3114 -51 21 minecraft:glowstone
fill 3095 -51 2 3113 -51 2 minecraft:glowstone
fill 3095 -51 21 3113 -51 21 minecraft:glowstone
fill 3095 -51 3 3095 -51 20 minecraft:glowstone
fill 3113 -51 3 3113 -51 20 minecraft:glowstone
fill 3096 -51 3 3112 -51 3 minecraft:glowstone
fill 3096 -51 20 3112 -51 20 minecraft:glowstone
fill 3096 -51 4 3096 -51 19 minecraft:glowstone
fill 3112 -51 4 3112 -51 19 minecraft:glowstone
fill 3102 -51 9 3106 -51 13 minecraft:glowstone
fill 3104 -58 12 3105 -58 13 minecraft:orange_concrete
setblock 3095 -57 15 minecraft:crafting_table
setblock 3113 -57 19 minecraft:chest
setblock 3113 -57 2 minecraft:furnace
setblock 3113 -57 12 minecraft:chest
setblock 3113 -57 16 minecraft:furnace
setblock 3095 -57 19 minecraft:bookshelf
setblock 3095 -57 6 minecraft:furnace
setblock 3095 -57 7 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3095 -57 20 minecraft:furnace
setblock 3113 -57 9 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3113 -57 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3113 -57 20 minecraft:furnace
