# Scene: tier_elevator_hard_08
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 8 of 15 with 3-5 decorations.
fill 1110 -59 0 1132 -59 22 minecraft:white_concrete
fill 1110 -58 0 1132 -53 22 minecraft:white_concrete
fill 1109 -58 0 1109 -53 22 minecraft:white_concrete
fill 1133 -58 0 1133 -53 22 minecraft:white_concrete
fill 1109 -58 -1 1133 -53 -1 minecraft:white_concrete
fill 1109 -58 23 1133 -53 23 minecraft:white_concrete
fill 1111 -58 1 1131 -53 21 minecraft:air
fill 1110 -52 0 1132 -52 22 minecraft:white_concrete
fill 1111 -52 1 1131 -52 1 minecraft:glowstone
fill 1111 -52 21 1131 -52 21 minecraft:glowstone
fill 1111 -52 2 1111 -52 20 minecraft:glowstone
fill 1131 -52 2 1131 -52 20 minecraft:glowstone
fill 1112 -52 2 1130 -52 2 minecraft:glowstone
fill 1112 -52 20 1130 -52 20 minecraft:glowstone
fill 1112 -52 3 1112 -52 19 minecraft:glowstone
fill 1130 -52 3 1130 -52 19 minecraft:glowstone
fill 1113 -52 3 1129 -52 3 minecraft:glowstone
fill 1113 -52 19 1129 -52 19 minecraft:glowstone
fill 1113 -52 4 1113 -52 18 minecraft:glowstone
fill 1129 -52 4 1129 -52 18 minecraft:glowstone
fill 1119 -52 9 1123 -52 13 minecraft:glowstone
fill 1111 -58 11 1131 -53 11 minecraft:white_concrete
fill 1121 -58 11 1122 -56 11 minecraft:black_concrete
setblock 1119 -58 4 minecraft:jungle_pressure_plate
setblock 1119 -58 5 minecraft:jungle_pressure_plate
setblock 1119 -58 6 minecraft:jungle_pressure_plate
setblock 1120 -58 4 minecraft:jungle_pressure_plate
setblock 1120 -58 5 minecraft:jungle_pressure_plate
setblock 1120 -58 6 minecraft:jungle_pressure_plate
setblock 1121 -58 4 minecraft:jungle_pressure_plate
setblock 1121 -58 5 minecraft:jungle_pressure_plate
setblock 1121 -58 6 minecraft:jungle_pressure_plate
setblock 1113 -58 2 minecraft:furnace
setblock 1112 -58 7 minecraft:furnace
setblock 1130 -58 7 minecraft:bookshelf
setblock 1112 -58 5 minecraft:stone_slab[type=bottom]
setblock 1129 -58 2 minecraft:bookshelf

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_08/place_command_blocks
