# Scene: picture_hard_12
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3825 -58 0 3841 -58 18 minecraft:white_concrete
fill 3825 -57 0 3841 -49 18 minecraft:white_concrete
fill 3824 -57 0 3824 -49 18 minecraft:white_concrete
fill 3842 -57 0 3842 -49 18 minecraft:white_concrete
fill 3824 -57 -1 3842 -49 -1 minecraft:white_concrete
fill 3824 -57 19 3842 -49 19 minecraft:white_concrete
fill 3826 -57 1 3840 -49 17 minecraft:air
fill 3825 -48 0 3841 -48 18 minecraft:white_concrete
fill 3826 -48 1 3840 -48 1 minecraft:glowstone
fill 3826 -48 17 3840 -48 17 minecraft:glowstone
fill 3826 -48 2 3826 -48 16 minecraft:glowstone
fill 3840 -48 2 3840 -48 16 minecraft:glowstone
fill 3827 -48 2 3839 -48 2 minecraft:glowstone
fill 3827 -48 16 3839 -48 16 minecraft:glowstone
fill 3827 -48 3 3827 -48 15 minecraft:glowstone
fill 3839 -48 3 3839 -48 15 minecraft:glowstone
fill 3828 -48 3 3838 -48 3 minecraft:glowstone
fill 3828 -48 15 3838 -48 15 minecraft:glowstone
fill 3828 -48 4 3828 -48 14 minecraft:glowstone
fill 3838 -48 4 3838 -48 14 minecraft:glowstone
fill 3831 -48 7 3835 -48 11 minecraft:glowstone
fill 3826 -53 1 3840 -53 5 minecraft:glowstone
fill 3826 -52 1 3840 -52 5 minecraft:smooth_stone
fill 3826 -51 6 3840 -51 6 minecraft:oak_fence
fill 3835 -57 1 3837 -57 3 minecraft:orange_concrete
fill 3833 -52 10 3833 -52 10 minecraft:smooth_stone
setblock 3837 -51 5 minecraft:chest
setblock 3830 -51 1 minecraft:crafting_table
setblock 3826 -51 3 minecraft:chest
setblock 3833 -51 2 minecraft:crafting_table
setblock 3834 -51 5 minecraft:furnace
setblock 3839 -51 1 minecraft:furnace
