# Scene: truck_hard_04
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2841 -58 0 2863 -58 23 minecraft:white_concrete
fill 2841 -57 0 2863 -52 23 minecraft:white_concrete
fill 2840 -57 0 2840 -52 23 minecraft:white_concrete
fill 2864 -57 0 2864 -52 23 minecraft:white_concrete
fill 2840 -57 -1 2864 -52 -1 minecraft:white_concrete
fill 2840 -57 24 2864 -52 24 minecraft:white_concrete
fill 2842 -57 1 2862 -52 22 minecraft:air
fill 2841 -51 0 2863 -51 23 minecraft:white_concrete
fill 2842 -51 1 2862 -51 1 minecraft:glowstone
fill 2842 -51 22 2862 -51 22 minecraft:glowstone
fill 2842 -51 2 2842 -51 21 minecraft:glowstone
fill 2862 -51 2 2862 -51 21 minecraft:glowstone
fill 2843 -51 2 2861 -51 2 minecraft:glowstone
fill 2843 -51 21 2861 -51 21 minecraft:glowstone
fill 2843 -51 3 2843 -51 20 minecraft:glowstone
fill 2861 -51 3 2861 -51 20 minecraft:glowstone
fill 2844 -51 3 2860 -51 3 minecraft:glowstone
fill 2844 -51 20 2860 -51 20 minecraft:glowstone
fill 2844 -51 4 2844 -51 19 minecraft:glowstone
fill 2860 -51 4 2860 -51 19 minecraft:glowstone
fill 2850 -51 9 2854 -51 13 minecraft:glowstone
fill 2852 -58 12 2853 -58 13 minecraft:lime_concrete
setblock 2843 -57 10 minecraft:furnace
setblock 2843 -57 8 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2861 -57 14 minecraft:chest
setblock 2861 -57 5 minecraft:bookshelf
setblock 2861 -57 20 minecraft:stone_slab[type=bottom]
setblock 2861 -57 12 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2843 -57 17 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2843 -57 19 minecraft:crafting_table
setblock 2843 -57 15 minecraft:chest
setblock 2843 -57 7 minecraft:bookshelf
setblock 2843 -57 12 minecraft:furnace
setblock 2843 -57 13 minecraft:bookshelf
setblock 2843 -57 16 minecraft:bookshelf
setblock 2861 -57 13 minecraft:crafting_table
