# Scene: truck_hard_08
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2967 -58 0 2989 -58 23 minecraft:white_concrete
fill 2967 -57 0 2989 -52 23 minecraft:white_concrete
fill 2966 -57 0 2966 -52 23 minecraft:white_concrete
fill 2990 -57 0 2990 -52 23 minecraft:white_concrete
fill 2966 -57 -1 2990 -52 -1 minecraft:white_concrete
fill 2966 -57 24 2990 -52 24 minecraft:white_concrete
fill 2968 -57 1 2988 -52 22 minecraft:air
fill 2967 -51 0 2989 -51 23 minecraft:white_concrete
fill 2968 -51 1 2988 -51 1 minecraft:glowstone
fill 2968 -51 22 2988 -51 22 minecraft:glowstone
fill 2968 -51 2 2968 -51 21 minecraft:glowstone
fill 2988 -51 2 2988 -51 21 minecraft:glowstone
fill 2969 -51 2 2987 -51 2 minecraft:glowstone
fill 2969 -51 21 2987 -51 21 minecraft:glowstone
fill 2969 -51 3 2969 -51 20 minecraft:glowstone
fill 2987 -51 3 2987 -51 20 minecraft:glowstone
fill 2970 -51 3 2986 -51 3 minecraft:glowstone
fill 2970 -51 20 2986 -51 20 minecraft:glowstone
fill 2970 -51 4 2970 -51 19 minecraft:glowstone
fill 2986 -51 4 2986 -51 19 minecraft:glowstone
fill 2976 -51 9 2980 -51 13 minecraft:glowstone
fill 2978 -58 12 2979 -58 13 minecraft:blue_concrete
setblock 2969 -57 21 minecraft:bookshelf
setblock 2969 -57 6 minecraft:bookshelf
setblock 2987 -57 13 minecraft:crafting_table
setblock 2987 -57 15 minecraft:furnace
setblock 2969 -57 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2987 -57 20 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2969 -57 17 minecraft:stone_slab[type=bottom]
setblock 2969 -57 4 minecraft:furnace
setblock 2969 -57 3 minecraft:stone_slab[type=bottom]
setblock 2987 -57 5 minecraft:crafting_table
