# Scene: picture_hard_05
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3650 -58 0 3666 -58 18 minecraft:white_concrete
fill 3650 -57 0 3666 -49 18 minecraft:white_concrete
fill 3649 -57 0 3649 -49 18 minecraft:white_concrete
fill 3667 -57 0 3667 -49 18 minecraft:white_concrete
fill 3649 -57 -1 3667 -49 -1 minecraft:white_concrete
fill 3649 -57 19 3667 -49 19 minecraft:white_concrete
fill 3651 -57 1 3665 -49 17 minecraft:air
fill 3650 -48 0 3666 -48 18 minecraft:white_concrete
fill 3651 -48 1 3665 -48 1 minecraft:glowstone
fill 3651 -48 17 3665 -48 17 minecraft:glowstone
fill 3651 -48 2 3651 -48 16 minecraft:glowstone
fill 3665 -48 2 3665 -48 16 minecraft:glowstone
fill 3652 -48 2 3664 -48 2 minecraft:glowstone
fill 3652 -48 16 3664 -48 16 minecraft:glowstone
fill 3652 -48 3 3652 -48 15 minecraft:glowstone
fill 3664 -48 3 3664 -48 15 minecraft:glowstone
fill 3653 -48 3 3663 -48 3 minecraft:glowstone
fill 3653 -48 15 3663 -48 15 minecraft:glowstone
fill 3653 -48 4 3653 -48 14 minecraft:glowstone
fill 3663 -48 4 3663 -48 14 minecraft:glowstone
fill 3656 -48 7 3660 -48 11 minecraft:glowstone
fill 3651 -53 1 3665 -53 5 minecraft:glowstone
fill 3651 -52 1 3665 -52 5 minecraft:smooth_stone
fill 3651 -51 6 3665 -51 6 minecraft:oak_fence
fill 3652 -57 2 3654 -57 4 minecraft:green_concrete
fill 3658 -52 10 3658 -52 10 minecraft:smooth_stone
setblock 3661 -51 3 minecraft:chest
setblock 3651 -51 2 minecraft:bookshelf
setblock 3655 -51 5 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3660 -51 3 minecraft:chest
