# Scene: tier_elevator_medium_06
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 6 of 15 with 3-5 decorations.
fill 601 -59 0 621 -59 22 minecraft:white_concrete
fill 601 -58 0 621 -53 22 minecraft:white_concrete
fill 600 -58 0 600 -53 22 minecraft:white_concrete
fill 622 -58 0 622 -53 22 minecraft:white_concrete
fill 600 -58 -1 622 -53 -1 minecraft:white_concrete
fill 600 -58 23 622 -53 23 minecraft:white_concrete
fill 602 -58 1 620 -53 21 minecraft:air
fill 601 -52 0 621 -52 22 minecraft:white_concrete
fill 602 -52 1 620 -52 1 minecraft:glowstone
fill 602 -52 21 620 -52 21 minecraft:glowstone
fill 602 -52 2 602 -52 20 minecraft:glowstone
fill 620 -52 2 620 -52 20 minecraft:glowstone
fill 603 -52 2 619 -52 2 minecraft:glowstone
fill 603 -52 20 619 -52 20 minecraft:glowstone
fill 603 -52 3 603 -52 19 minecraft:glowstone
fill 619 -52 3 619 -52 19 minecraft:glowstone
fill 604 -52 3 618 -52 3 minecraft:glowstone
fill 604 -52 19 618 -52 19 minecraft:glowstone
fill 604 -52 4 604 -52 18 minecraft:glowstone
fill 618 -52 4 618 -52 18 minecraft:glowstone
fill 609 -52 9 613 -52 13 minecraft:glowstone
fill 602 -58 11 620 -53 11 minecraft:white_concrete
fill 609 -58 11 610 -56 11 minecraft:light_gray_concrete
setblock 610 -58 5 minecraft:polished_blackstone_pressure_plate
setblock 610 -58 6 minecraft:polished_blackstone_pressure_plate
setblock 610 -58 7 minecraft:polished_blackstone_pressure_plate
setblock 611 -58 5 minecraft:polished_blackstone_pressure_plate
setblock 611 -58 6 minecraft:polished_blackstone_pressure_plate
setblock 611 -58 7 minecraft:polished_blackstone_pressure_plate
setblock 612 -58 5 minecraft:polished_blackstone_pressure_plate
setblock 612 -58 6 minecraft:polished_blackstone_pressure_plate
setblock 612 -58 7 minecraft:polished_blackstone_pressure_plate
setblock 612 -58 2 minecraft:furnace
setblock 610 -58 2 minecraft:bookshelf
setblock 613 -58 2 minecraft:chest
setblock 603 -58 7 minecraft:crafting_table
setblock 606 -58 2 minecraft:chest

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_06/place_command_blocks
