# Scene: tier_path_easy_13
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 简单 difficulty variant 13 of 15 with 3-5 decorations.
fill 1260 -58 0 1281 -58 31 minecraft:white_concrete
fill 1260 -57 0 1281 -52 31 minecraft:white_concrete
fill 1259 -57 0 1259 -52 31 minecraft:white_concrete
fill 1282 -57 0 1282 -52 31 minecraft:white_concrete
fill 1259 -57 -1 1282 -52 -1 minecraft:white_concrete
fill 1259 -57 32 1282 -52 32 minecraft:white_concrete
fill 1261 -57 1 1280 -52 30 minecraft:air
fill 1260 -51 0 1281 -51 31 minecraft:white_concrete
fill 1261 -51 1 1280 -51 1 minecraft:glowstone
fill 1261 -51 30 1280 -51 30 minecraft:glowstone
fill 1261 -51 2 1261 -51 29 minecraft:glowstone
fill 1280 -51 2 1280 -51 29 minecraft:glowstone
fill 1262 -51 2 1279 -51 2 minecraft:glowstone
fill 1262 -51 29 1279 -51 29 minecraft:glowstone
fill 1262 -51 3 1262 -51 28 minecraft:glowstone
fill 1279 -51 3 1279 -51 28 minecraft:glowstone
fill 1263 -51 3 1278 -51 3 minecraft:glowstone
fill 1263 -51 28 1278 -51 28 minecraft:glowstone
fill 1263 -51 4 1263 -51 27 minecraft:glowstone
fill 1278 -51 4 1278 -51 27 minecraft:glowstone
fill 1268 -51 13 1272 -51 17 minecraft:glowstone
fill 1260 -61 0 1281 -58 31 minecraft:white_concrete
fill 1260 -61 0 1281 -58 13 minecraft:white_concrete
fill 1260 -61 18 1281 -58 31 minecraft:white_concrete
fill 1261 -61 14 1280 -58 17 minecraft:air
fill 1260 -61 0 1281 -61 31 minecraft:black_concrete
fill 1269 -58 14 1272 -58 17 minecraft:air
fill 1269 -57 19 1272 -57 19 minecraft:gold_block
setblock 1270 -57 9 minecraft:oak_pressure_plate
setblock 1270 -57 10 minecraft:oak_pressure_plate
setblock 1270 -57 11 minecraft:oak_pressure_plate
setblock 1270 -57 12 minecraft:oak_pressure_plate
setblock 1271 -57 9 minecraft:oak_pressure_plate
setblock 1271 -57 10 minecraft:oak_pressure_plate
setblock 1271 -57 11 minecraft:oak_pressure_plate
setblock 1271 -57 12 minecraft:oak_pressure_plate
setblock 1272 -57 9 minecraft:oak_pressure_plate
setblock 1272 -57 10 minecraft:oak_pressure_plate
setblock 1272 -57 11 minecraft:oak_pressure_plate
setblock 1272 -57 12 minecraft:oak_pressure_plate
setblock 1273 -57 9 minecraft:oak_pressure_plate
setblock 1273 -57 10 minecraft:oak_pressure_plate
setblock 1273 -57 11 minecraft:oak_pressure_plate
setblock 1273 -57 12 minecraft:oak_pressure_plate
setblock 1262 -57 12 minecraft:chest
setblock 1279 -57 3 minecraft:chest
setblock 1266 -57 2 minecraft:crafting_table

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_easy_13/place_command_blocks
