# Scene: tier_elevator_hard_10
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 10 of 15 with 3-5 decorations.
fill 1170 -59 0 1191 -59 22 minecraft:white_concrete
fill 1170 -58 0 1191 -53 22 minecraft:white_concrete
fill 1169 -58 0 1169 -53 22 minecraft:white_concrete
fill 1192 -58 0 1192 -53 22 minecraft:white_concrete
fill 1169 -58 -1 1192 -53 -1 minecraft:white_concrete
fill 1169 -58 23 1192 -53 23 minecraft:white_concrete
fill 1171 -58 1 1190 -53 21 minecraft:air
fill 1170 -52 0 1191 -52 22 minecraft:white_concrete
fill 1171 -52 1 1190 -52 1 minecraft:glowstone
fill 1171 -52 21 1190 -52 21 minecraft:glowstone
fill 1171 -52 2 1171 -52 20 minecraft:glowstone
fill 1190 -52 2 1190 -52 20 minecraft:glowstone
fill 1172 -52 2 1189 -52 2 minecraft:glowstone
fill 1172 -52 20 1189 -52 20 minecraft:glowstone
fill 1172 -52 3 1172 -52 19 minecraft:glowstone
fill 1189 -52 3 1189 -52 19 minecraft:glowstone
fill 1173 -52 3 1188 -52 3 minecraft:glowstone
fill 1173 -52 19 1188 -52 19 minecraft:glowstone
fill 1173 -52 4 1173 -52 18 minecraft:glowstone
fill 1188 -52 4 1188 -52 18 minecraft:glowstone
fill 1178 -52 9 1182 -52 13 minecraft:glowstone
fill 1171 -58 11 1190 -53 11 minecraft:white_concrete
fill 1180 -58 11 1181 -56 11 minecraft:light_blue_concrete
setblock 1178 -58 4 minecraft:cherry_pressure_plate
setblock 1178 -58 5 minecraft:cherry_pressure_plate
setblock 1178 -58 6 minecraft:cherry_pressure_plate
setblock 1179 -58 4 minecraft:cherry_pressure_plate
setblock 1179 -58 5 minecraft:cherry_pressure_plate
setblock 1179 -58 6 minecraft:cherry_pressure_plate
setblock 1180 -58 4 minecraft:cherry_pressure_plate
setblock 1180 -58 5 minecraft:cherry_pressure_plate
setblock 1180 -58 6 minecraft:cherry_pressure_plate
setblock 1174 -58 2 minecraft:crafting_table
setblock 1189 -58 7 minecraft:bookshelf
setblock 1189 -58 6 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1187 -58 2 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_10/place_command_blocks
