# Scene: tier_path_medium_15
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 15 of 15 with 3-5 decorations.
fill 1771 -58 0 1791 -58 31 minecraft:white_concrete
fill 1771 -57 0 1791 -52 31 minecraft:white_concrete
fill 1770 -57 0 1770 -52 31 minecraft:white_concrete
fill 1792 -57 0 1792 -52 31 minecraft:white_concrete
fill 1770 -57 -1 1792 -52 -1 minecraft:white_concrete
fill 1770 -57 32 1792 -52 32 minecraft:white_concrete
fill 1772 -57 1 1790 -52 30 minecraft:air
fill 1771 -51 0 1791 -51 31 minecraft:white_concrete
fill 1772 -51 1 1790 -51 1 minecraft:glowstone
fill 1772 -51 30 1790 -51 30 minecraft:glowstone
fill 1772 -51 2 1772 -51 29 minecraft:glowstone
fill 1790 -51 2 1790 -51 29 minecraft:glowstone
fill 1773 -51 2 1789 -51 2 minecraft:glowstone
fill 1773 -51 29 1789 -51 29 minecraft:glowstone
fill 1773 -51 3 1773 -51 28 minecraft:glowstone
fill 1789 -51 3 1789 -51 28 minecraft:glowstone
fill 1774 -51 3 1788 -51 3 minecraft:glowstone
fill 1774 -51 28 1788 -51 28 minecraft:glowstone
fill 1774 -51 4 1774 -51 27 minecraft:glowstone
fill 1788 -51 4 1788 -51 27 minecraft:glowstone
fill 1779 -51 13 1783 -51 17 minecraft:glowstone
fill 1771 -61 0 1791 -58 31 minecraft:white_concrete
fill 1771 -61 0 1791 -58 12 minecraft:white_concrete
fill 1771 -61 18 1791 -58 31 minecraft:white_concrete
fill 1772 -61 13 1790 -58 17 minecraft:air
fill 1771 -61 0 1791 -61 31 minecraft:black_concrete
fill 1780 -58 13 1782 -58 17 minecraft:air
fill 1780 -57 19 1782 -57 19 minecraft:gold_block
setblock 1780 -57 8 minecraft:birch_pressure_plate
setblock 1780 -57 9 minecraft:birch_pressure_plate
setblock 1780 -57 10 minecraft:birch_pressure_plate
setblock 1781 -57 8 minecraft:birch_pressure_plate
setblock 1781 -57 9 minecraft:birch_pressure_plate
setblock 1781 -57 10 minecraft:birch_pressure_plate
setblock 1782 -57 8 minecraft:birch_pressure_plate
setblock 1782 -57 9 minecraft:birch_pressure_plate
setblock 1782 -57 10 minecraft:birch_pressure_plate
setblock 1789 -57 3 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 1773 -57 10 minecraft:chest
setblock 1773 -57 8 minecraft:chest

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_medium_15/place_command_blocks
