# Scene: tier_elevator_hard_04
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 4 of 15 with 3-5 decorations.
fill 990 -59 0 1011 -59 22 minecraft:white_concrete
fill 990 -58 0 1011 -53 22 minecraft:white_concrete
fill 989 -58 0 989 -53 22 minecraft:white_concrete
fill 1012 -58 0 1012 -53 22 minecraft:white_concrete
fill 989 -58 -1 1012 -53 -1 minecraft:white_concrete
fill 989 -58 23 1012 -53 23 minecraft:white_concrete
fill 991 -58 1 1010 -53 21 minecraft:air
fill 990 -52 0 1011 -52 22 minecraft:white_concrete
fill 991 -52 1 1010 -52 1 minecraft:glowstone
fill 991 -52 21 1010 -52 21 minecraft:glowstone
fill 991 -52 2 991 -52 20 minecraft:glowstone
fill 1010 -52 2 1010 -52 20 minecraft:glowstone
fill 992 -52 2 1009 -52 2 minecraft:glowstone
fill 992 -52 20 1009 -52 20 minecraft:glowstone
fill 992 -52 3 992 -52 19 minecraft:glowstone
fill 1009 -52 3 1009 -52 19 minecraft:glowstone
fill 993 -52 3 1008 -52 3 minecraft:glowstone
fill 993 -52 19 1008 -52 19 minecraft:glowstone
fill 993 -52 4 993 -52 18 minecraft:glowstone
fill 1008 -52 4 1008 -52 18 minecraft:glowstone
fill 998 -52 9 1002 -52 13 minecraft:glowstone
fill 991 -58 11 1010 -53 11 minecraft:white_concrete
fill 1000 -58 11 1001 -56 11 minecraft:brown_concrete
setblock 1001 -58 4 minecraft:acacia_pressure_plate
setblock 1001 -58 5 minecraft:acacia_pressure_plate
setblock 1001 -58 6 minecraft:acacia_pressure_plate
setblock 1002 -58 4 minecraft:acacia_pressure_plate
setblock 1002 -58 5 minecraft:acacia_pressure_plate
setblock 1002 -58 6 minecraft:acacia_pressure_plate
setblock 1003 -58 4 minecraft:acacia_pressure_plate
setblock 1003 -58 5 minecraft:acacia_pressure_plate
setblock 1003 -58 6 minecraft:acacia_pressure_plate
setblock 992 -58 4 minecraft:crafting_table
setblock 1002 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 996 -58 2 minecraft:bookshelf
setblock 995 -58 2 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 999 -58 2 minecraft:chest

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_04/place_command_blocks
