# Scene: truck_hard_10
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3030 -58 0 3052 -58 23 minecraft:white_concrete
fill 3030 -57 0 3052 -52 23 minecraft:white_concrete
fill 3029 -57 0 3029 -52 23 minecraft:white_concrete
fill 3053 -57 0 3053 -52 23 minecraft:white_concrete
fill 3029 -57 -1 3053 -52 -1 minecraft:white_concrete
fill 3029 -57 24 3053 -52 24 minecraft:white_concrete
fill 3031 -57 1 3051 -52 22 minecraft:air
fill 3030 -51 0 3052 -51 23 minecraft:white_concrete
fill 3031 -51 1 3051 -51 1 minecraft:glowstone
fill 3031 -51 22 3051 -51 22 minecraft:glowstone
fill 3031 -51 2 3031 -51 21 minecraft:glowstone
fill 3051 -51 2 3051 -51 21 minecraft:glowstone
fill 3032 -51 2 3050 -51 2 minecraft:glowstone
fill 3032 -51 21 3050 -51 21 minecraft:glowstone
fill 3032 -51 3 3032 -51 20 minecraft:glowstone
fill 3050 -51 3 3050 -51 20 minecraft:glowstone
fill 3033 -51 3 3049 -51 3 minecraft:glowstone
fill 3033 -51 20 3049 -51 20 minecraft:glowstone
fill 3033 -51 4 3033 -51 19 minecraft:glowstone
fill 3049 -51 4 3049 -51 19 minecraft:glowstone
fill 3039 -51 9 3043 -51 13 minecraft:glowstone
fill 3041 -58 12 3042 -58 13 minecraft:magenta_concrete
setblock 3032 -57 3 minecraft:bookshelf
setblock 3050 -57 16 minecraft:bookshelf
setblock 3032 -57 7 minecraft:bookshelf
setblock 3050 -57 21 minecraft:bookshelf
setblock 3050 -57 19 minecraft:chest
setblock 3050 -57 11 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3032 -57 14 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3032 -57 2 minecraft:stone_slab[type=bottom]
setblock 3032 -57 12 minecraft:chest
setblock 3050 -57 8 minecraft:bookshelf
setblock 3032 -57 20 minecraft:stone_slab[type=bottom]
setblock 3050 -57 6 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 3050 -57 7 minecraft:furnace
setblock 3050 -57 5 minecraft:crafting_table
setblock 3032 -57 5 minecraft:furnace
