# Scene: tier_elevator_hard_06
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 6 of 15 with 3-5 decorations.
fill 1051 -59 0 1071 -59 22 minecraft:white_concrete
fill 1051 -58 0 1071 -53 22 minecraft:white_concrete
fill 1050 -58 0 1050 -53 22 minecraft:white_concrete
fill 1072 -58 0 1072 -53 22 minecraft:white_concrete
fill 1050 -58 -1 1072 -53 -1 minecraft:white_concrete
fill 1050 -58 23 1072 -53 23 minecraft:white_concrete
fill 1052 -58 1 1070 -53 21 minecraft:air
fill 1051 -52 0 1071 -52 22 minecraft:white_concrete
fill 1052 -52 1 1070 -52 1 minecraft:glowstone
fill 1052 -52 21 1070 -52 21 minecraft:glowstone
fill 1052 -52 2 1052 -52 20 minecraft:glowstone
fill 1070 -52 2 1070 -52 20 minecraft:glowstone
fill 1053 -52 2 1069 -52 2 minecraft:glowstone
fill 1053 -52 20 1069 -52 20 minecraft:glowstone
fill 1053 -52 3 1053 -52 19 minecraft:glowstone
fill 1069 -52 3 1069 -52 19 minecraft:glowstone
fill 1054 -52 3 1068 -52 3 minecraft:glowstone
fill 1054 -52 19 1068 -52 19 minecraft:glowstone
fill 1054 -52 4 1054 -52 18 minecraft:glowstone
fill 1068 -52 4 1068 -52 18 minecraft:glowstone
fill 1059 -52 9 1063 -52 13 minecraft:glowstone
fill 1052 -58 11 1070 -53 11 minecraft:white_concrete
fill 1059 -58 11 1060 -56 11 minecraft:light_gray_concrete
setblock 1060 -58 4 minecraft:polished_blackstone_pressure_plate
setblock 1060 -58 5 minecraft:polished_blackstone_pressure_plate
setblock 1060 -58 6 minecraft:polished_blackstone_pressure_plate
setblock 1061 -58 4 minecraft:polished_blackstone_pressure_plate
setblock 1061 -58 5 minecraft:polished_blackstone_pressure_plate
setblock 1061 -58 6 minecraft:polished_blackstone_pressure_plate
setblock 1062 -58 4 minecraft:polished_blackstone_pressure_plate
setblock 1062 -58 5 minecraft:polished_blackstone_pressure_plate
setblock 1062 -58 6 minecraft:polished_blackstone_pressure_plate
setblock 1053 -58 2 minecraft:stone_slab[type=bottom]
setblock 1056 -58 2 minecraft:chest
setblock 1069 -58 7 minecraft:furnace
setblock 1065 -58 2 minecraft:stone_slab[type=bottom]
setblock 1064 -58 2 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_06/place_command_blocks
