# Scene: tier_elevator_medium_10
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 10 of 15 with 3-5 decorations.
fill 720 -59 0 741 -59 22 minecraft:white_concrete
fill 720 -58 0 741 -53 22 minecraft:white_concrete
fill 719 -58 0 719 -53 22 minecraft:white_concrete
fill 742 -58 0 742 -53 22 minecraft:white_concrete
fill 719 -58 -1 742 -53 -1 minecraft:white_concrete
fill 719 -58 23 742 -53 23 minecraft:white_concrete
fill 721 -58 1 740 -53 21 minecraft:air
fill 720 -52 0 741 -52 22 minecraft:white_concrete
fill 721 -52 1 740 -52 1 minecraft:glowstone
fill 721 -52 21 740 -52 21 minecraft:glowstone
fill 721 -52 2 721 -52 20 minecraft:glowstone
fill 740 -52 2 740 -52 20 minecraft:glowstone
fill 722 -52 2 739 -52 2 minecraft:glowstone
fill 722 -52 20 739 -52 20 minecraft:glowstone
fill 722 -52 3 722 -52 19 minecraft:glowstone
fill 739 -52 3 739 -52 19 minecraft:glowstone
fill 723 -52 3 738 -52 3 minecraft:glowstone
fill 723 -52 19 738 -52 19 minecraft:glowstone
fill 723 -52 4 723 -52 18 minecraft:glowstone
fill 738 -52 4 738 -52 18 minecraft:glowstone
fill 728 -52 9 732 -52 13 minecraft:glowstone
fill 721 -58 11 740 -53 11 minecraft:white_concrete
fill 730 -58 11 731 -56 11 minecraft:light_blue_concrete
setblock 728 -58 5 minecraft:cherry_pressure_plate
setblock 728 -58 6 minecraft:cherry_pressure_plate
setblock 728 -58 7 minecraft:cherry_pressure_plate
setblock 729 -58 5 minecraft:cherry_pressure_plate
setblock 729 -58 6 minecraft:cherry_pressure_plate
setblock 729 -58 7 minecraft:cherry_pressure_plate
setblock 730 -58 5 minecraft:cherry_pressure_plate
setblock 730 -58 6 minecraft:cherry_pressure_plate
setblock 730 -58 7 minecraft:cherry_pressure_plate
setblock 739 -58 6 minecraft:stone_slab[type=bottom]
setblock 738 -58 2 minecraft:crafting_table
setblock 737 -58 2 minecraft:chest

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_10/place_command_blocks
