# Scene: truck_hard_09
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2998 -58 0 3021 -58 22 minecraft:white_concrete
fill 2998 -57 0 3021 -52 22 minecraft:white_concrete
fill 2997 -57 0 2997 -52 22 minecraft:white_concrete
fill 3022 -57 0 3022 -52 22 minecraft:white_concrete
fill 2997 -57 -1 3022 -52 -1 minecraft:white_concrete
fill 2997 -57 23 3022 -52 23 minecraft:white_concrete
fill 2999 -57 1 3020 -52 21 minecraft:air
fill 2998 -51 0 3021 -51 22 minecraft:white_concrete
fill 2999 -51 1 3020 -51 1 minecraft:glowstone
fill 2999 -51 21 3020 -51 21 minecraft:glowstone
fill 2999 -51 2 2999 -51 20 minecraft:glowstone
fill 3020 -51 2 3020 -51 20 minecraft:glowstone
fill 3000 -51 2 3019 -51 2 minecraft:glowstone
fill 3000 -51 20 3019 -51 20 minecraft:glowstone
fill 3000 -51 3 3000 -51 19 minecraft:glowstone
fill 3019 -51 3 3019 -51 19 minecraft:glowstone
fill 3001 -51 3 3018 -51 3 minecraft:glowstone
fill 3001 -51 19 3018 -51 19 minecraft:glowstone
fill 3001 -51 4 3001 -51 18 minecraft:glowstone
fill 3018 -51 4 3018 -51 18 minecraft:glowstone
fill 3007 -51 9 3011 -51 13 minecraft:glowstone
fill 3010 -58 11 3011 -58 12 minecraft:purple_concrete
setblock 3019 -57 10 minecraft:stone_slab[type=bottom]
setblock 3000 -57 12 minecraft:crafting_table
setblock 3019 -57 16 minecraft:stone_slab[type=bottom]
setblock 3000 -57 17 minecraft:crafting_table
setblock 3000 -57 5 minecraft:furnace
setblock 3000 -57 3 minecraft:chest
setblock 3000 -57 9 minecraft:crafting_table
setblock 3019 -57 5 minecraft:chest
setblock 3019 -57 20 minecraft:crafting_table
setblock 3019 -57 14 minecraft:stone_slab[type=bottom]
setblock 3000 -57 6 minecraft:stone_slab[type=bottom]
setblock 3019 -57 4 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
