# Scene: tier_elevator_hard_12
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 12 of 15 with 3-5 decorations.
fill 1231 -59 0 1251 -59 22 minecraft:white_concrete
fill 1231 -58 0 1251 -53 22 minecraft:white_concrete
fill 1230 -58 0 1230 -53 22 minecraft:white_concrete
fill 1252 -58 0 1252 -53 22 minecraft:white_concrete
fill 1230 -58 -1 1252 -53 -1 minecraft:white_concrete
fill 1230 -58 23 1252 -53 23 minecraft:white_concrete
fill 1232 -58 1 1250 -53 21 minecraft:air
fill 1231 -52 0 1251 -52 22 minecraft:white_concrete
fill 1232 -52 1 1250 -52 1 minecraft:glowstone
fill 1232 -52 21 1250 -52 21 minecraft:glowstone
fill 1232 -52 2 1232 -52 20 minecraft:glowstone
fill 1250 -52 2 1250 -52 20 minecraft:glowstone
fill 1233 -52 2 1249 -52 2 minecraft:glowstone
fill 1233 -52 20 1249 -52 20 minecraft:glowstone
fill 1233 -52 3 1233 -52 19 minecraft:glowstone
fill 1249 -52 3 1249 -52 19 minecraft:glowstone
fill 1234 -52 3 1248 -52 3 minecraft:glowstone
fill 1234 -52 19 1248 -52 19 minecraft:glowstone
fill 1234 -52 4 1234 -52 18 minecraft:glowstone
fill 1248 -52 4 1248 -52 18 minecraft:glowstone
fill 1239 -52 9 1243 -52 13 minecraft:glowstone
fill 1232 -58 11 1250 -53 11 minecraft:white_concrete
fill 1239 -58 11 1240 -56 11 minecraft:gray_concrete
setblock 1242 -58 4 minecraft:birch_pressure_plate
setblock 1242 -58 5 minecraft:birch_pressure_plate
setblock 1242 -58 6 minecraft:birch_pressure_plate
setblock 1243 -58 4 minecraft:birch_pressure_plate
setblock 1243 -58 5 minecraft:birch_pressure_plate
setblock 1243 -58 6 minecraft:birch_pressure_plate
setblock 1244 -58 4 minecraft:birch_pressure_plate
setblock 1244 -58 5 minecraft:birch_pressure_plate
setblock 1244 -58 6 minecraft:birch_pressure_plate
setblock 1249 -58 8 minecraft:bookshelf
setblock 1243 -58 2 minecraft:furnace
setblock 1241 -58 2 minecraft:furnace

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_12/place_command_blocks
