# Scene: picture_hard_02
# Auto-generated by multiagent/scene/generate_scenes.py
fill 3575 -58 0 3591 -58 18 minecraft:white_concrete
fill 3575 -57 0 3591 -49 18 minecraft:white_concrete
fill 3574 -57 0 3574 -49 18 minecraft:white_concrete
fill 3592 -57 0 3592 -49 18 minecraft:white_concrete
fill 3574 -57 -1 3592 -49 -1 minecraft:white_concrete
fill 3574 -57 19 3592 -49 19 minecraft:white_concrete
fill 3576 -57 1 3590 -49 17 minecraft:air
fill 3575 -48 0 3591 -48 18 minecraft:white_concrete
fill 3576 -48 1 3590 -48 1 minecraft:glowstone
fill 3576 -48 17 3590 -48 17 minecraft:glowstone
fill 3576 -48 2 3576 -48 16 minecraft:glowstone
fill 3590 -48 2 3590 -48 16 minecraft:glowstone
fill 3577 -48 2 3589 -48 2 minecraft:glowstone
fill 3577 -48 16 3589 -48 16 minecraft:glowstone
fill 3577 -48 3 3577 -48 15 minecraft:glowstone
fill 3589 -48 3 3589 -48 15 minecraft:glowstone
fill 3578 -48 3 3588 -48 3 minecraft:glowstone
fill 3578 -48 15 3588 -48 15 minecraft:glowstone
fill 3578 -48 4 3578 -48 14 minecraft:glowstone
fill 3588 -48 4 3588 -48 14 minecraft:glowstone
fill 3581 -48 7 3585 -48 11 minecraft:glowstone
fill 3576 -53 1 3590 -53 5 minecraft:glowstone
fill 3576 -52 1 3590 -52 5 minecraft:smooth_stone
fill 3576 -51 6 3590 -51 6 minecraft:oak_fence
fill 3587 -57 1 3589 -57 3 minecraft:orange_concrete
fill 3583 -52 10 3583 -52 10 minecraft:smooth_stone
setblock 3588 -51 5 minecraft:bookshelf
setblock 3580 -51 5 minecraft:chest
setblock 3578 -51 4 minecraft:bookshelf
setblock 3590 -51 2 minecraft:stone_slab[type=bottom]
setblock 3583 -51 5 minecraft:chest
