# Scene: truck_hard_01
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2746 -58 0 2769 -58 22 minecraft:white_concrete
fill 2746 -57 0 2769 -52 22 minecraft:white_concrete
fill 2745 -57 0 2745 -52 22 minecraft:white_concrete
fill 2770 -57 0 2770 -52 22 minecraft:white_concrete
fill 2745 -57 -1 2770 -52 -1 minecraft:white_concrete
fill 2745 -57 23 2770 -52 23 minecraft:white_concrete
fill 2747 -57 1 2768 -52 21 minecraft:air
fill 2746 -51 0 2769 -51 22 minecraft:white_concrete
fill 2747 -51 1 2768 -51 1 minecraft:glowstone
fill 2747 -51 21 2768 -51 21 minecraft:glowstone
fill 2747 -51 2 2747 -51 20 minecraft:glowstone
fill 2768 -51 2 2768 -51 20 minecraft:glowstone
fill 2748 -51 2 2767 -51 2 minecraft:glowstone
fill 2748 -51 20 2767 -51 20 minecraft:glowstone
fill 2748 -51 3 2748 -51 19 minecraft:glowstone
fill 2767 -51 3 2767 -51 19 minecraft:glowstone
fill 2749 -51 3 2766 -51 3 minecraft:glowstone
fill 2749 -51 19 2766 -51 19 minecraft:glowstone
fill 2749 -51 4 2749 -51 18 minecraft:glowstone
fill 2766 -51 4 2766 -51 18 minecraft:glowstone
fill 2755 -51 9 2759 -51 13 minecraft:glowstone
fill 2758 -58 11 2759 -58 12 minecraft:red_concrete
setblock 2767 -57 7 minecraft:stone_slab[type=bottom]
setblock 2767 -57 10 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2748 -57 14 minecraft:stone_slab[type=bottom]
setblock 2748 -57 5 minecraft:stone_slab[type=bottom]
setblock 2767 -57 13 minecraft:chest
setblock 2767 -57 5 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2748 -57 15 minecraft:furnace
setblock 2748 -57 6 minecraft:furnace
setblock 2748 -57 17 minecraft:furnace
setblock 2767 -57 17 minecraft:stone_slab[type=bottom]
setblock 2748 -57 8 minecraft:crafting_table
setblock 2767 -57 12 minecraft:furnace
