# Scene: tier_path_hard_10
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 10 of 15 with 3-5 decorations.
fill 2070 -58 0 2091 -58 30 minecraft:white_concrete
fill 2070 -57 0 2091 -52 30 minecraft:white_concrete
fill 2069 -57 0 2069 -52 30 minecraft:white_concrete
fill 2092 -57 0 2092 -52 30 minecraft:white_concrete
fill 2069 -57 -1 2092 -52 -1 minecraft:white_concrete
fill 2069 -57 31 2092 -52 31 minecraft:white_concrete
fill 2071 -57 1 2090 -52 29 minecraft:air
fill 2070 -51 0 2091 -51 30 minecraft:white_concrete
fill 2071 -51 1 2090 -51 1 minecraft:glowstone
fill 2071 -51 29 2090 -51 29 minecraft:glowstone
fill 2071 -51 2 2071 -51 28 minecraft:glowstone
fill 2090 -51 2 2090 -51 28 minecraft:glowstone
fill 2072 -51 2 2089 -51 2 minecraft:glowstone
fill 2072 -51 28 2089 -51 28 minecraft:glowstone
fill 2072 -51 3 2072 -51 27 minecraft:glowstone
fill 2089 -51 3 2089 -51 27 minecraft:glowstone
fill 2073 -51 3 2088 -51 3 minecraft:glowstone
fill 2073 -51 27 2088 -51 27 minecraft:glowstone
fill 2073 -51 4 2073 -51 26 minecraft:glowstone
fill 2088 -51 4 2088 -51 26 minecraft:glowstone
fill 2078 -51 13 2082 -51 17 minecraft:glowstone
fill 2070 -61 0 2091 -58 30 minecraft:white_concrete
fill 2070 -61 0 2091 -58 11 minecraft:white_concrete
fill 2070 -61 18 2091 -58 30 minecraft:white_concrete
fill 2071 -61 12 2090 -58 17 minecraft:air
fill 2070 -61 0 2091 -61 30 minecraft:black_concrete
fill 2079 -58 12 2081 -58 17 minecraft:air
fill 2079 -57 19 2081 -57 19 minecraft:gold_block
setblock 2080 -57 7 minecraft:cherry_pressure_plate
setblock 2080 -57 8 minecraft:cherry_pressure_plate
setblock 2080 -57 9 minecraft:cherry_pressure_plate
setblock 2081 -57 7 minecraft:cherry_pressure_plate
setblock 2081 -57 8 minecraft:cherry_pressure_plate
setblock 2081 -57 9 minecraft:cherry_pressure_plate
setblock 2082 -57 7 minecraft:cherry_pressure_plate
setblock 2082 -57 8 minecraft:cherry_pressure_plate
setblock 2082 -57 9 minecraft:cherry_pressure_plate
setblock 2083 -57 2 minecraft:stone_slab[type=bottom]
setblock 2082 -57 2 minecraft:chest
setblock 2076 -57 2 minecraft:bookshelf
setblock 2072 -57 3 minecraft:crafting_table
setblock 2089 -57 8 minecraft:furnace

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_10/place_command_blocks
