# Scene: truck_hard_07
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2935 -58 0 2958 -58 22 minecraft:white_concrete
fill 2935 -57 0 2958 -52 22 minecraft:white_concrete
fill 2934 -57 0 2934 -52 22 minecraft:white_concrete
fill 2959 -57 0 2959 -52 22 minecraft:white_concrete
fill 2934 -57 -1 2959 -52 -1 minecraft:white_concrete
fill 2934 -57 23 2959 -52 23 minecraft:white_concrete
fill 2936 -57 1 2957 -52 21 minecraft:air
fill 2935 -51 0 2958 -51 22 minecraft:white_concrete
fill 2936 -51 1 2957 -51 1 minecraft:glowstone
fill 2936 -51 21 2957 -51 21 minecraft:glowstone
fill 2936 -51 2 2936 -51 20 minecraft:glowstone
fill 2957 -51 2 2957 -51 20 minecraft:glowstone
fill 2937 -51 2 2956 -51 2 minecraft:glowstone
fill 2937 -51 20 2956 -51 20 minecraft:glowstone
fill 2937 -51 3 2937 -51 19 minecraft:glowstone
fill 2956 -51 3 2956 -51 19 minecraft:glowstone
fill 2938 -51 3 2955 -51 3 minecraft:glowstone
fill 2938 -51 19 2955 -51 19 minecraft:glowstone
fill 2938 -51 4 2938 -51 18 minecraft:glowstone
fill 2955 -51 4 2955 -51 18 minecraft:glowstone
fill 2944 -51 9 2948 -51 13 minecraft:glowstone
fill 2947 -58 11 2948 -58 12 minecraft:light_blue_concrete
setblock 2956 -57 20 minecraft:chest
setblock 2937 -57 19 minecraft:furnace
setblock 2956 -57 13 minecraft:stone_slab[type=bottom]
setblock 2956 -57 5 minecraft:furnace
setblock 2956 -57 9 minecraft:furnace
setblock 2956 -57 15 minecraft:furnace
setblock 2937 -57 9 minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
setblock 2937 -57 18 minecraft:chest
setblock 2956 -57 18 minecraft:crafting_table
setblock 2956 -57 16 minecraft:stone_slab[type=bottom]
setblock 2937 -57 20 minecraft:crafting_table
setblock 2937 -57 15 minecraft:crafting_table
setblock 2956 -57 11 minecraft:furnace
setblock 2956 -57 10 minecraft:stone_slab[type=bottom]
setblock 2937 -57 6 minecraft:stone_slab[type=bottom]
