# Scene: tier_path_hard_11
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 11 of 15 with 3-5 decorations.
fill 2100 -58 0 2122 -58 31 minecraft:white_concrete
fill 2100 -57 0 2122 -52 31 minecraft:white_concrete
fill 2099 -57 0 2099 -52 31 minecraft:white_concrete
fill 2123 -57 0 2123 -52 31 minecraft:white_concrete
fill 2099 -57 -1 2123 -52 -1 minecraft:white_concrete
fill 2099 -57 32 2123 -52 32 minecraft:white_concrete
fill 2101 -57 1 2121 -52 30 minecraft:air
fill 2100 -51 0 2122 -51 31 minecraft:white_concrete
fill 2101 -51 1 2121 -51 1 minecraft:glowstone
fill 2101 -51 30 2121 -51 30 minecraft:glowstone
fill 2101 -51 2 2101 -51 29 minecraft:glowstone
fill 2121 -51 2 2121 -51 29 minecraft:glowstone
fill 2102 -51 2 2120 -51 2 minecraft:glowstone
fill 2102 -51 29 2120 -51 29 minecraft:glowstone
fill 2102 -51 3 2102 -51 28 minecraft:glowstone
fill 2120 -51 3 2120 -51 28 minecraft:glowstone
fill 2103 -51 3 2119 -51 3 minecraft:glowstone
fill 2103 -51 28 2119 -51 28 minecraft:glowstone
fill 2103 -51 4 2103 -51 27 minecraft:glowstone
fill 2119 -51 4 2119 -51 27 minecraft:glowstone
fill 2109 -51 13 2113 -51 17 minecraft:glowstone
fill 2100 -61 0 2122 -58 31 minecraft:white_concrete
fill 2100 -61 0 2122 -58 12 minecraft:white_concrete
fill 2100 -61 19 2122 -58 31 minecraft:white_concrete
fill 2101 -61 13 2121 -58 18 minecraft:air
fill 2100 -61 0 2122 -61 31 minecraft:black_concrete
fill 2110 -58 13 2112 -58 18 minecraft:air
fill 2110 -57 20 2112 -57 20 minecraft:gold_block
setblock 2110 -57 8 minecraft:stone_pressure_plate
setblock 2110 -57 9 minecraft:stone_pressure_plate
setblock 2110 -57 10 minecraft:stone_pressure_plate
setblock 2111 -57 8 minecraft:stone_pressure_plate
setblock 2111 -57 9 minecraft:stone_pressure_plate
setblock 2111 -57 10 minecraft:stone_pressure_plate
setblock 2112 -57 8 minecraft:stone_pressure_plate
setblock 2112 -57 9 minecraft:stone_pressure_plate
setblock 2112 -57 10 minecraft:stone_pressure_plate
setblock 2102 -57 9 minecraft:crafting_table
setblock 2120 -57 2 minecraft:stone_slab[type=bottom]
setblock 2108 -57 2 minecraft:stone_slab[type=bottom]

# Command blocks that reveal the middle path while the plate is pressed.
function path:tier_path_hard_11/place_command_blocks
