# Scene: truck_easy_11
# Auto-generated by multiagent/scene/generate_scenes.py
fill 2115 -58 0 2138 -58 22 minecraft:white_concrete
fill 2115 -57 0 2138 -52 22 minecraft:white_concrete
fill 2114 -57 0 2114 -52 22 minecraft:white_concrete
fill 2139 -57 0 2139 -52 22 minecraft:white_concrete
fill 2114 -57 -1 2139 -52 -1 minecraft:white_concrete
fill 2114 -57 23 2139 -52 23 minecraft:white_concrete
fill 2116 -57 1 2137 -52 21 minecraft:air
fill 2115 -51 0 2138 -51 22 minecraft:white_concrete
fill 2116 -51 1 2137 -51 1 minecraft:glowstone
fill 2116 -51 21 2137 -51 21 minecraft:glowstone
fill 2116 -51 2 2116 -51 20 minecraft:glowstone
fill 2137 -51 2 2137 -51 20 minecraft:glowstone
fill 2117 -51 2 2136 -51 2 minecraft:glowstone
fill 2117 -51 20 2136 -51 20 minecraft:glowstone
fill 2117 -51 3 2117 -51 19 minecraft:glowstone
fill 2136 -51 3 2136 -51 19 minecraft:glowstone
fill 2118 -51 3 2135 -51 3 minecraft:glowstone
fill 2118 -51 19 2135 -51 19 minecraft:glowstone
fill 2118 -51 4 2118 -51 18 minecraft:glowstone
fill 2135 -51 4 2135 -51 18 minecraft:glowstone
fill 2124 -51 9 2128 -51 13 minecraft:glowstone
fill 2126 -58 10 2129 -58 13 minecraft:red_concrete
setblock 2136 -57 15 minecraft:stone_slab[type=bottom]
setblock 2136 -57 19 minecraft:bookshelf
setblock 2136 -57 12 minecraft:bookshelf
setblock 2136 -57 17 minecraft:crafting_table
setblock 2117 -57 13 minecraft:bookshelf
setblock 2117 -57 4 minecraft:stone_slab[type=bottom]
setblock 2117 -57 2 minecraft:bookshelf
setblock 2136 -57 2 minecraft:crafting_table
setblock 2117 -57 19 minecraft:bookshelf
setblock 2136 -57 14 minecraft:furnace
setblock 2117 -57 3 minecraft:stone_slab[type=bottom]
setblock 2136 -57 5 minecraft:crafting_table
setblock 2117 -57 16 minecraft:furnace
setblock 2136 -57 10 minecraft:stone_slab[type=bottom]
setblock 2136 -57 6 minecraft:bookshelf
