# Scene: tier_elevator_hard_14
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 14 of 15 with 3-5 decorations.
fill 1290 -59 0 1312 -59 22 minecraft:white_concrete
fill 1290 -58 0 1312 -53 22 minecraft:white_concrete
fill 1289 -58 0 1289 -53 22 minecraft:white_concrete
fill 1313 -58 0 1313 -53 22 minecraft:white_concrete
fill 1289 -58 -1 1313 -53 -1 minecraft:white_concrete
fill 1289 -58 23 1313 -53 23 minecraft:white_concrete
fill 1291 -58 1 1311 -53 21 minecraft:air
fill 1290 -52 0 1312 -52 22 minecraft:white_concrete
fill 1291 -52 1 1311 -52 1 minecraft:glowstone
fill 1291 -52 21 1311 -52 21 minecraft:glowstone
fill 1291 -52 2 1291 -52 20 minecraft:glowstone
fill 1311 -52 2 1311 -52 20 minecraft:glowstone
fill 1292 -52 2 1310 -52 2 minecraft:glowstone
fill 1292 -52 20 1310 -52 20 minecraft:glowstone
fill 1292 -52 3 1292 -52 19 minecraft:glowstone
fill 1310 -52 3 1310 -52 19 minecraft:glowstone
fill 1293 -52 3 1309 -52 3 minecraft:glowstone
fill 1293 -52 19 1309 -52 19 minecraft:glowstone
fill 1293 -52 4 1293 -52 18 minecraft:glowstone
fill 1309 -52 4 1309 -52 18 minecraft:glowstone
fill 1299 -52 9 1303 -52 13 minecraft:glowstone
fill 1291 -58 11 1311 -53 11 minecraft:white_concrete
fill 1301 -58 11 1302 -56 11 minecraft:brown_concrete
setblock 1301 -58 4 minecraft:mangrove_pressure_plate
setblock 1301 -58 5 minecraft:mangrove_pressure_plate
setblock 1301 -58 6 minecraft:mangrove_pressure_plate
setblock 1302 -58 4 minecraft:mangrove_pressure_plate
setblock 1302 -58 5 minecraft:mangrove_pressure_plate
setblock 1302 -58 6 minecraft:mangrove_pressure_plate
setblock 1303 -58 4 minecraft:mangrove_pressure_plate
setblock 1303 -58 5 minecraft:mangrove_pressure_plate
setblock 1303 -58 6 minecraft:mangrove_pressure_plate
setblock 1299 -58 2 minecraft:crafting_table
setblock 1300 -58 2 minecraft:crafting_table
setblock 1292 -58 7 minecraft:chest

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_14/place_command_blocks
