# Scene: tier_elevator_medium_15
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 中等 difficulty variant 15 of 15 with 3-5 decorations.
fill 871 -59 0 891 -59 23 minecraft:white_concrete
fill 871 -58 0 891 -53 23 minecraft:white_concrete
fill 870 -58 0 870 -53 23 minecraft:white_concrete
fill 892 -58 0 892 -53 23 minecraft:white_concrete
fill 870 -58 -1 892 -53 -1 minecraft:white_concrete
fill 870 -58 24 892 -53 24 minecraft:white_concrete
fill 872 -58 1 890 -53 22 minecraft:air
fill 871 -52 0 891 -52 23 minecraft:white_concrete
fill 872 -52 1 890 -52 1 minecraft:glowstone
fill 872 -52 22 890 -52 22 minecraft:glowstone
fill 872 -52 2 872 -52 21 minecraft:glowstone
fill 890 -52 2 890 -52 21 minecraft:glowstone
fill 873 -52 2 889 -52 2 minecraft:glowstone
fill 873 -52 21 889 -52 21 minecraft:glowstone
fill 873 -52 3 873 -52 20 minecraft:glowstone
fill 889 -52 3 889 -52 20 minecraft:glowstone
fill 874 -52 3 888 -52 3 minecraft:glowstone
fill 874 -52 20 888 -52 20 minecraft:glowstone
fill 874 -52 4 874 -52 19 minecraft:glowstone
fill 888 -52 4 888 -52 19 minecraft:glowstone
fill 879 -52 9 883 -52 13 minecraft:glowstone
fill 872 -58 12 890 -53 12 minecraft:white_concrete
fill 879 -58 12 880 -56 12 minecraft:light_blue_concrete
setblock 878 -58 7 minecraft:stone_pressure_plate
setblock 878 -58 8 minecraft:stone_pressure_plate
setblock 878 -58 9 minecraft:stone_pressure_plate
setblock 879 -58 7 minecraft:stone_pressure_plate
setblock 879 -58 8 minecraft:stone_pressure_plate
setblock 879 -58 9 minecraft:stone_pressure_plate
setblock 880 -58 7 minecraft:stone_pressure_plate
setblock 880 -58 8 minecraft:stone_pressure_plate
setblock 880 -58 9 minecraft:stone_pressure_plate
setblock 887 -58 2 minecraft:chest
setblock 889 -58 6 minecraft:stone_slab[type=bottom]
setblock 884 -58 2 minecraft:furnace
setblock 882 -58 2 minecraft:crafting_table
setblock 876 -58 2 minecraft:stone_slab[type=bottom]

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_medium_15/place_command_blocks
