# Scene: tier_elevator_hard_13
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: 困难 difficulty variant 13 of 15 with 3-5 decorations.
fill 1260 -59 0 1281 -59 23 minecraft:white_concrete
fill 1260 -58 0 1281 -53 23 minecraft:white_concrete
fill 1259 -58 0 1259 -53 23 minecraft:white_concrete
fill 1282 -58 0 1282 -53 23 minecraft:white_concrete
fill 1259 -58 -1 1282 -53 -1 minecraft:white_concrete
fill 1259 -58 24 1282 -53 24 minecraft:white_concrete
fill 1261 -58 1 1280 -53 22 minecraft:air
fill 1260 -52 0 1281 -52 23 minecraft:white_concrete
fill 1261 -52 1 1280 -52 1 minecraft:glowstone
fill 1261 -52 22 1280 -52 22 minecraft:glowstone
fill 1261 -52 2 1261 -52 21 minecraft:glowstone
fill 1280 -52 2 1280 -52 21 minecraft:glowstone
fill 1262 -52 2 1279 -52 2 minecraft:glowstone
fill 1262 -52 21 1279 -52 21 minecraft:glowstone
fill 1262 -52 3 1262 -52 20 minecraft:glowstone
fill 1279 -52 3 1279 -52 20 minecraft:glowstone
fill 1263 -52 3 1278 -52 3 minecraft:glowstone
fill 1263 -52 20 1278 -52 20 minecraft:glowstone
fill 1263 -52 4 1263 -52 19 minecraft:glowstone
fill 1278 -52 4 1278 -52 19 minecraft:glowstone
fill 1268 -52 9 1272 -52 13 minecraft:glowstone
fill 1261 -58 12 1280 -53 12 minecraft:white_concrete
fill 1270 -58 12 1271 -56 12 minecraft:black_concrete
setblock 1269 -58 6 minecraft:acacia_pressure_plate
setblock 1269 -58 7 minecraft:acacia_pressure_plate
setblock 1269 -58 8 minecraft:acacia_pressure_plate
setblock 1270 -58 6 minecraft:acacia_pressure_plate
setblock 1270 -58 7 minecraft:acacia_pressure_plate
setblock 1270 -58 8 minecraft:acacia_pressure_plate
setblock 1271 -58 6 minecraft:acacia_pressure_plate
setblock 1271 -58 7 minecraft:acacia_pressure_plate
setblock 1271 -58 8 minecraft:acacia_pressure_plate
setblock 1279 -58 6 minecraft:stone_slab[type=bottom]
setblock 1278 -58 2 minecraft:bookshelf
setblock 1265 -58 2 minecraft:bookshelf
setblock 1279 -58 2 minecraft:crafting_table

# Command blocks that keep the elevator door open while the plate is pressed.
function elevator:tier_elevator_hard_13/place_command_blocks
